-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dut_bitset_49ns_49ns_6ns_1ns_49_1_1 is
generic (
    ADDRWIDTH : INTEGER := 6;
    DATAWIDTH : INTEGER := 49
);
port (

    sel   : in std_logic_vector (ADDRWIDTH-1 downto 0);
    din   : in std_logic_vector (DATAWIDTH-1 downto 0);
    value : in std_logic_vector (0 downto 0);
    dout  : out std_logic_vector (DATAWIDTH-1 downto 0)
);
end entity;

architecture behav of dut_bitset_49ns_49ns_6ns_1ns_49_1_1 is
    signal dout_tmp : std_logic_vector (DATAWIDTH-1 downto 0);



begin

    process(din,sel,value) is
    begin
        dout_tmp <= din;
        if to_integer(unsigned(sel)) >= din'low and to_integer(unsigned(sel)) <= din'high then
            dout_tmp(to_integer(unsigned(sel))) <= value(0);
        end if;
    end process;


    dout <= dout_tmp;






end architecture;
