// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module dut_forward_Pipeline_VITIS_LOOP_140_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        bestChildNode_7,
        this_meanQ_address0,
        this_meanQ_ce0,
        this_meanQ_q0,
        this_visitCounts_address0,
        this_visitCounts_ce0,
        this_visitCounts_q0,
        logVisitCount,
        this_nextSiblings_address0,
        this_nextSiblings_ce0,
        this_nextSiblings_q0,
        bestChildNode_out,
        bestChildNode_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] bestChildNode_7;
output  [12:0] this_meanQ_address0;
output   this_meanQ_ce0;
input  [19:0] this_meanQ_q0;
output  [12:0] this_visitCounts_address0;
output   this_visitCounts_ce0;
input  [31:0] this_visitCounts_q0;
input  [31:0] logVisitCount;
output  [12:0] this_nextSiblings_address0;
output   this_nextSiblings_ce0;
input  [31:0] this_nextSiblings_q0;
output  [31:0] bestChildNode_out;
output   bestChildNode_out_ap_vld;

reg ap_idle;
reg bestChildNode_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_enable_reg_pp0_iter26;
reg    ap_enable_reg_pp0_iter27;
reg    ap_enable_reg_pp0_iter28;
reg    ap_enable_reg_pp0_iter29;
reg    ap_enable_reg_pp0_iter30;
reg    ap_enable_reg_pp0_iter31;
reg    ap_enable_reg_pp0_iter32;
reg    ap_enable_reg_pp0_iter33;
reg    ap_enable_reg_pp0_iter34;
reg    ap_enable_reg_pp0_iter35;
reg    ap_enable_reg_pp0_iter36;
reg    ap_enable_reg_pp0_iter37;
reg    ap_enable_reg_pp0_iter38;
reg    ap_enable_reg_pp0_iter39;
reg    ap_enable_reg_pp0_iter40;
reg    ap_enable_reg_pp0_iter41;
reg    ap_enable_reg_pp0_iter42;
reg    ap_enable_reg_pp0_iter43;
reg    ap_enable_reg_pp0_iter44;
reg    ap_enable_reg_pp0_iter45;
reg    ap_enable_reg_pp0_iter46;
reg    ap_enable_reg_pp0_iter47;
reg    ap_enable_reg_pp0_iter48;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln140_fu_141_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [31:0] childNode_2_reg_268;
reg   [31:0] childNode_2_reg_268_pp0_iter1_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter2_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter3_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter4_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter5_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter6_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter7_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter8_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter9_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter10_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter11_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter12_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter13_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter14_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter15_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter16_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter17_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter18_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter19_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter20_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter21_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter22_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter23_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter24_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter25_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter26_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter27_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter28_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter29_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter30_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter31_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter32_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter33_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter34_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter35_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter36_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter37_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter38_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter39_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter40_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter41_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter42_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter43_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter44_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter45_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter46_reg;
reg   [31:0] childNode_2_reg_268_pp0_iter47_reg;
reg   [0:0] icmp_ln140_reg_273;
reg   [0:0] icmp_ln140_reg_273_pp0_iter1_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter2_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter3_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter4_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter5_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter6_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter7_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter8_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter9_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter10_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter11_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter12_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter13_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter14_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter15_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter16_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter17_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter18_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter19_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter20_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter21_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter22_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter23_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter24_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter25_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter26_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter27_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter28_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter29_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter30_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter31_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter32_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter33_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter34_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter35_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter36_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter37_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter38_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter39_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter40_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter41_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter42_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter43_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter44_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter45_reg;
reg   [0:0] icmp_ln140_reg_273_pp0_iter46_reg;
wire   [63:0] zext_ln141_fu_147_p1;
reg   [63:0] zext_ln141_reg_277;
reg   [63:0] zext_ln141_reg_277_pp0_iter1_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter2_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter3_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter4_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter5_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter6_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter7_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter8_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter9_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter10_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter11_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter12_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter13_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter14_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter15_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter16_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter17_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter18_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter19_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter20_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter21_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter22_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter23_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter24_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter25_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter26_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter27_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter28_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter29_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter30_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter31_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter32_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter33_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter34_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter35_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter36_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter37_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter38_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter39_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter40_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter41_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter42_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter43_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter44_reg;
reg   [63:0] zext_ln141_reg_277_pp0_iter45_reg;
wire   [31:0] grp_fu_153_p2;
reg   [31:0] x_reg_297;
wire   [23:0] grp_sqrt_fixed_32_16_s_fu_118_ap_return;
reg   [23:0] sext_ln_reg_302;
wire    ap_block_pp0_stage0_11001_ignoreCallOp115;
wire    ap_block_pp0_stage0_ignoreCallOp108;
wire    ap_block_pp0_stage0;
reg   [31:0] bestChildNode_fu_48;
wire   [31:0] bestChildNode_5_fu_211_p3;
wire    ap_loop_init;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg    ap_loop_exit_ready_pp0_iter20_reg;
reg    ap_loop_exit_ready_pp0_iter21_reg;
reg    ap_loop_exit_ready_pp0_iter22_reg;
reg    ap_loop_exit_ready_pp0_iter23_reg;
reg    ap_loop_exit_ready_pp0_iter24_reg;
reg    ap_loop_exit_ready_pp0_iter25_reg;
reg    ap_loop_exit_ready_pp0_iter26_reg;
reg    ap_loop_exit_ready_pp0_iter27_reg;
reg    ap_loop_exit_ready_pp0_iter28_reg;
reg    ap_loop_exit_ready_pp0_iter29_reg;
reg    ap_loop_exit_ready_pp0_iter30_reg;
reg    ap_loop_exit_ready_pp0_iter31_reg;
reg    ap_loop_exit_ready_pp0_iter32_reg;
reg    ap_loop_exit_ready_pp0_iter33_reg;
reg    ap_loop_exit_ready_pp0_iter34_reg;
reg    ap_loop_exit_ready_pp0_iter35_reg;
reg    ap_loop_exit_ready_pp0_iter36_reg;
reg    ap_loop_exit_ready_pp0_iter37_reg;
reg    ap_loop_exit_ready_pp0_iter38_reg;
reg    ap_loop_exit_ready_pp0_iter39_reg;
reg    ap_loop_exit_ready_pp0_iter40_reg;
reg    ap_loop_exit_ready_pp0_iter41_reg;
reg    ap_loop_exit_ready_pp0_iter42_reg;
reg    ap_loop_exit_ready_pp0_iter43_reg;
reg    ap_loop_exit_ready_pp0_iter44_reg;
reg    ap_loop_exit_ready_pp0_iter45_reg;
reg    ap_loop_exit_ready_pp0_iter46_reg;
reg    ap_loop_exit_ready_pp0_iter47_reg;
reg   [31:0] bestChildNode_3_fu_52;
reg   [31:0] ap_sig_allocacmp_childNode_2;
reg   [31:0] bestChildUCT_fu_56;
wire   [31:0] bestChildUCT_2_fu_203_p3;
wire    ap_block_pp0_stage0_01001;
reg    this_visitCounts_ce0_local;
reg    this_nextSiblings_ce0_local;
reg    this_meanQ_ce0_local;
wire  signed [35:0] shl_ln_fu_166_p3;
wire  signed [40:0] grp_fu_232_p3;
wire   [25:0] childUCT_fu_184_p4;
wire  signed [31:0] sext_ln144_1_fu_193_p1;
wire   [0:0] icmp_ln145_fu_197_p2;
wire   [23:0] grp_fu_232_p0;
wire   [15:0] grp_fu_232_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [39:0] grp_fu_232_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter26 = 1'b0;
#0 ap_enable_reg_pp0_iter27 = 1'b0;
#0 ap_enable_reg_pp0_iter28 = 1'b0;
#0 ap_enable_reg_pp0_iter29 = 1'b0;
#0 ap_enable_reg_pp0_iter30 = 1'b0;
#0 ap_enable_reg_pp0_iter31 = 1'b0;
#0 ap_enable_reg_pp0_iter32 = 1'b0;
#0 ap_enable_reg_pp0_iter33 = 1'b0;
#0 ap_enable_reg_pp0_iter34 = 1'b0;
#0 ap_enable_reg_pp0_iter35 = 1'b0;
#0 ap_enable_reg_pp0_iter36 = 1'b0;
#0 ap_enable_reg_pp0_iter37 = 1'b0;
#0 ap_enable_reg_pp0_iter38 = 1'b0;
#0 ap_enable_reg_pp0_iter39 = 1'b0;
#0 ap_enable_reg_pp0_iter40 = 1'b0;
#0 ap_enable_reg_pp0_iter41 = 1'b0;
#0 ap_enable_reg_pp0_iter42 = 1'b0;
#0 ap_enable_reg_pp0_iter43 = 1'b0;
#0 ap_enable_reg_pp0_iter44 = 1'b0;
#0 ap_enable_reg_pp0_iter45 = 1'b0;
#0 ap_enable_reg_pp0_iter46 = 1'b0;
#0 ap_enable_reg_pp0_iter47 = 1'b0;
#0 ap_enable_reg_pp0_iter48 = 1'b0;
#0 bestChildNode_fu_48 = 32'd0;
#0 bestChildNode_3_fu_52 = 32'd0;
#0 bestChildUCT_fu_56 = 32'd0;
#0 ap_done_reg = 1'b0;
end

dut_sqrt_fixed_32_16_s grp_sqrt_fixed_32_16_s_fu_118(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .x(x_reg_297),
    .ap_return(grp_sqrt_fixed_32_16_s_fu_118_ap_return)
);

dut_sdiv_32ns_32ns_32_36_1 #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sdiv_32ns_32ns_32_36_1_U75(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(logVisitCount),
    .din1(this_visitCounts_q0),
    .ce(1'b1),
    .dout(grp_fu_153_p2)
);

dut_mac_muladd_24ns_16ns_36s_41_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 41 ))
mac_muladd_24ns_16ns_36s_41_4_1_U76(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_232_p0),
    .din1(grp_fu_232_p1),
    .din2(shl_ln_fu_166_p3),
    .ce(1'b1),
    .dout(grp_fu_232_p3)
);

dut_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter47_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter26 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter27 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter28 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter29 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter30 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter30 <= ap_enable_reg_pp0_iter29;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter31 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter31 <= ap_enable_reg_pp0_iter30;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter32 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter32 <= ap_enable_reg_pp0_iter31;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter33 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter33 <= ap_enable_reg_pp0_iter32;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter34 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter34 <= ap_enable_reg_pp0_iter33;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter35 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter35 <= ap_enable_reg_pp0_iter34;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter36 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter36 <= ap_enable_reg_pp0_iter35;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter37 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter37 <= ap_enable_reg_pp0_iter36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter38 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter38 <= ap_enable_reg_pp0_iter37;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter39 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter39 <= ap_enable_reg_pp0_iter38;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter40 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter40 <= ap_enable_reg_pp0_iter39;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter41 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter41 <= ap_enable_reg_pp0_iter40;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter42 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter42 <= ap_enable_reg_pp0_iter41;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter43 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter43 <= ap_enable_reg_pp0_iter42;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter44 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter44 <= ap_enable_reg_pp0_iter43;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter45 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter45 <= ap_enable_reg_pp0_iter44;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter46 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter46 <= ap_enable_reg_pp0_iter45;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter47 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter47 <= ap_enable_reg_pp0_iter46;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter48 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter48 <= ap_enable_reg_pp0_iter47;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            bestChildNode_3_fu_52 <= bestChildNode_7;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            bestChildNode_3_fu_52 <= this_nextSiblings_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            bestChildNode_fu_48 <= bestChildNode_7;
        end else if ((ap_enable_reg_pp0_iter48 == 1'b1)) begin
            bestChildNode_fu_48 <= bestChildNode_5_fu_211_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            bestChildUCT_fu_56 <= 32'd4288413696;
        end else if ((ap_enable_reg_pp0_iter48 == 1'b1)) begin
            bestChildUCT_fu_56 <= bestChildUCT_2_fu_203_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
        ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
        ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
        ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
        ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
        ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
        ap_loop_exit_ready_pp0_iter25_reg <= ap_loop_exit_ready_pp0_iter24_reg;
        ap_loop_exit_ready_pp0_iter26_reg <= ap_loop_exit_ready_pp0_iter25_reg;
        ap_loop_exit_ready_pp0_iter27_reg <= ap_loop_exit_ready_pp0_iter26_reg;
        ap_loop_exit_ready_pp0_iter28_reg <= ap_loop_exit_ready_pp0_iter27_reg;
        ap_loop_exit_ready_pp0_iter29_reg <= ap_loop_exit_ready_pp0_iter28_reg;
        ap_loop_exit_ready_pp0_iter30_reg <= ap_loop_exit_ready_pp0_iter29_reg;
        ap_loop_exit_ready_pp0_iter31_reg <= ap_loop_exit_ready_pp0_iter30_reg;
        ap_loop_exit_ready_pp0_iter32_reg <= ap_loop_exit_ready_pp0_iter31_reg;
        ap_loop_exit_ready_pp0_iter33_reg <= ap_loop_exit_ready_pp0_iter32_reg;
        ap_loop_exit_ready_pp0_iter34_reg <= ap_loop_exit_ready_pp0_iter33_reg;
        ap_loop_exit_ready_pp0_iter35_reg <= ap_loop_exit_ready_pp0_iter34_reg;
        ap_loop_exit_ready_pp0_iter36_reg <= ap_loop_exit_ready_pp0_iter35_reg;
        ap_loop_exit_ready_pp0_iter37_reg <= ap_loop_exit_ready_pp0_iter36_reg;
        ap_loop_exit_ready_pp0_iter38_reg <= ap_loop_exit_ready_pp0_iter37_reg;
        ap_loop_exit_ready_pp0_iter39_reg <= ap_loop_exit_ready_pp0_iter38_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter40_reg <= ap_loop_exit_ready_pp0_iter39_reg;
        ap_loop_exit_ready_pp0_iter41_reg <= ap_loop_exit_ready_pp0_iter40_reg;
        ap_loop_exit_ready_pp0_iter42_reg <= ap_loop_exit_ready_pp0_iter41_reg;
        ap_loop_exit_ready_pp0_iter43_reg <= ap_loop_exit_ready_pp0_iter42_reg;
        ap_loop_exit_ready_pp0_iter44_reg <= ap_loop_exit_ready_pp0_iter43_reg;
        ap_loop_exit_ready_pp0_iter45_reg <= ap_loop_exit_ready_pp0_iter44_reg;
        ap_loop_exit_ready_pp0_iter46_reg <= ap_loop_exit_ready_pp0_iter45_reg;
        ap_loop_exit_ready_pp0_iter47_reg <= ap_loop_exit_ready_pp0_iter46_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        childNode_2_reg_268_pp0_iter10_reg <= childNode_2_reg_268_pp0_iter9_reg;
        childNode_2_reg_268_pp0_iter11_reg <= childNode_2_reg_268_pp0_iter10_reg;
        childNode_2_reg_268_pp0_iter12_reg <= childNode_2_reg_268_pp0_iter11_reg;
        childNode_2_reg_268_pp0_iter13_reg <= childNode_2_reg_268_pp0_iter12_reg;
        childNode_2_reg_268_pp0_iter14_reg <= childNode_2_reg_268_pp0_iter13_reg;
        childNode_2_reg_268_pp0_iter15_reg <= childNode_2_reg_268_pp0_iter14_reg;
        childNode_2_reg_268_pp0_iter16_reg <= childNode_2_reg_268_pp0_iter15_reg;
        childNode_2_reg_268_pp0_iter17_reg <= childNode_2_reg_268_pp0_iter16_reg;
        childNode_2_reg_268_pp0_iter18_reg <= childNode_2_reg_268_pp0_iter17_reg;
        childNode_2_reg_268_pp0_iter19_reg <= childNode_2_reg_268_pp0_iter18_reg;
        childNode_2_reg_268_pp0_iter20_reg <= childNode_2_reg_268_pp0_iter19_reg;
        childNode_2_reg_268_pp0_iter21_reg <= childNode_2_reg_268_pp0_iter20_reg;
        childNode_2_reg_268_pp0_iter22_reg <= childNode_2_reg_268_pp0_iter21_reg;
        childNode_2_reg_268_pp0_iter23_reg <= childNode_2_reg_268_pp0_iter22_reg;
        childNode_2_reg_268_pp0_iter24_reg <= childNode_2_reg_268_pp0_iter23_reg;
        childNode_2_reg_268_pp0_iter25_reg <= childNode_2_reg_268_pp0_iter24_reg;
        childNode_2_reg_268_pp0_iter26_reg <= childNode_2_reg_268_pp0_iter25_reg;
        childNode_2_reg_268_pp0_iter27_reg <= childNode_2_reg_268_pp0_iter26_reg;
        childNode_2_reg_268_pp0_iter28_reg <= childNode_2_reg_268_pp0_iter27_reg;
        childNode_2_reg_268_pp0_iter29_reg <= childNode_2_reg_268_pp0_iter28_reg;
        childNode_2_reg_268_pp0_iter2_reg <= childNode_2_reg_268_pp0_iter1_reg;
        childNode_2_reg_268_pp0_iter30_reg <= childNode_2_reg_268_pp0_iter29_reg;
        childNode_2_reg_268_pp0_iter31_reg <= childNode_2_reg_268_pp0_iter30_reg;
        childNode_2_reg_268_pp0_iter32_reg <= childNode_2_reg_268_pp0_iter31_reg;
        childNode_2_reg_268_pp0_iter33_reg <= childNode_2_reg_268_pp0_iter32_reg;
        childNode_2_reg_268_pp0_iter34_reg <= childNode_2_reg_268_pp0_iter33_reg;
        childNode_2_reg_268_pp0_iter35_reg <= childNode_2_reg_268_pp0_iter34_reg;
        childNode_2_reg_268_pp0_iter36_reg <= childNode_2_reg_268_pp0_iter35_reg;
        childNode_2_reg_268_pp0_iter37_reg <= childNode_2_reg_268_pp0_iter36_reg;
        childNode_2_reg_268_pp0_iter38_reg <= childNode_2_reg_268_pp0_iter37_reg;
        childNode_2_reg_268_pp0_iter39_reg <= childNode_2_reg_268_pp0_iter38_reg;
        childNode_2_reg_268_pp0_iter3_reg <= childNode_2_reg_268_pp0_iter2_reg;
        childNode_2_reg_268_pp0_iter40_reg <= childNode_2_reg_268_pp0_iter39_reg;
        childNode_2_reg_268_pp0_iter41_reg <= childNode_2_reg_268_pp0_iter40_reg;
        childNode_2_reg_268_pp0_iter42_reg <= childNode_2_reg_268_pp0_iter41_reg;
        childNode_2_reg_268_pp0_iter43_reg <= childNode_2_reg_268_pp0_iter42_reg;
        childNode_2_reg_268_pp0_iter44_reg <= childNode_2_reg_268_pp0_iter43_reg;
        childNode_2_reg_268_pp0_iter45_reg <= childNode_2_reg_268_pp0_iter44_reg;
        childNode_2_reg_268_pp0_iter46_reg <= childNode_2_reg_268_pp0_iter45_reg;
        childNode_2_reg_268_pp0_iter47_reg <= childNode_2_reg_268_pp0_iter46_reg;
        childNode_2_reg_268_pp0_iter4_reg <= childNode_2_reg_268_pp0_iter3_reg;
        childNode_2_reg_268_pp0_iter5_reg <= childNode_2_reg_268_pp0_iter4_reg;
        childNode_2_reg_268_pp0_iter6_reg <= childNode_2_reg_268_pp0_iter5_reg;
        childNode_2_reg_268_pp0_iter7_reg <= childNode_2_reg_268_pp0_iter6_reg;
        childNode_2_reg_268_pp0_iter8_reg <= childNode_2_reg_268_pp0_iter7_reg;
        childNode_2_reg_268_pp0_iter9_reg <= childNode_2_reg_268_pp0_iter8_reg;
        icmp_ln140_reg_273_pp0_iter10_reg <= icmp_ln140_reg_273_pp0_iter9_reg;
        icmp_ln140_reg_273_pp0_iter11_reg <= icmp_ln140_reg_273_pp0_iter10_reg;
        icmp_ln140_reg_273_pp0_iter12_reg <= icmp_ln140_reg_273_pp0_iter11_reg;
        icmp_ln140_reg_273_pp0_iter13_reg <= icmp_ln140_reg_273_pp0_iter12_reg;
        icmp_ln140_reg_273_pp0_iter14_reg <= icmp_ln140_reg_273_pp0_iter13_reg;
        icmp_ln140_reg_273_pp0_iter15_reg <= icmp_ln140_reg_273_pp0_iter14_reg;
        icmp_ln140_reg_273_pp0_iter16_reg <= icmp_ln140_reg_273_pp0_iter15_reg;
        icmp_ln140_reg_273_pp0_iter17_reg <= icmp_ln140_reg_273_pp0_iter16_reg;
        icmp_ln140_reg_273_pp0_iter18_reg <= icmp_ln140_reg_273_pp0_iter17_reg;
        icmp_ln140_reg_273_pp0_iter19_reg <= icmp_ln140_reg_273_pp0_iter18_reg;
        icmp_ln140_reg_273_pp0_iter20_reg <= icmp_ln140_reg_273_pp0_iter19_reg;
        icmp_ln140_reg_273_pp0_iter21_reg <= icmp_ln140_reg_273_pp0_iter20_reg;
        icmp_ln140_reg_273_pp0_iter22_reg <= icmp_ln140_reg_273_pp0_iter21_reg;
        icmp_ln140_reg_273_pp0_iter23_reg <= icmp_ln140_reg_273_pp0_iter22_reg;
        icmp_ln140_reg_273_pp0_iter24_reg <= icmp_ln140_reg_273_pp0_iter23_reg;
        icmp_ln140_reg_273_pp0_iter25_reg <= icmp_ln140_reg_273_pp0_iter24_reg;
        icmp_ln140_reg_273_pp0_iter26_reg <= icmp_ln140_reg_273_pp0_iter25_reg;
        icmp_ln140_reg_273_pp0_iter27_reg <= icmp_ln140_reg_273_pp0_iter26_reg;
        icmp_ln140_reg_273_pp0_iter28_reg <= icmp_ln140_reg_273_pp0_iter27_reg;
        icmp_ln140_reg_273_pp0_iter29_reg <= icmp_ln140_reg_273_pp0_iter28_reg;
        icmp_ln140_reg_273_pp0_iter2_reg <= icmp_ln140_reg_273_pp0_iter1_reg;
        icmp_ln140_reg_273_pp0_iter30_reg <= icmp_ln140_reg_273_pp0_iter29_reg;
        icmp_ln140_reg_273_pp0_iter31_reg <= icmp_ln140_reg_273_pp0_iter30_reg;
        icmp_ln140_reg_273_pp0_iter32_reg <= icmp_ln140_reg_273_pp0_iter31_reg;
        icmp_ln140_reg_273_pp0_iter33_reg <= icmp_ln140_reg_273_pp0_iter32_reg;
        icmp_ln140_reg_273_pp0_iter34_reg <= icmp_ln140_reg_273_pp0_iter33_reg;
        icmp_ln140_reg_273_pp0_iter35_reg <= icmp_ln140_reg_273_pp0_iter34_reg;
        icmp_ln140_reg_273_pp0_iter36_reg <= icmp_ln140_reg_273_pp0_iter35_reg;
        icmp_ln140_reg_273_pp0_iter37_reg <= icmp_ln140_reg_273_pp0_iter36_reg;
        icmp_ln140_reg_273_pp0_iter38_reg <= icmp_ln140_reg_273_pp0_iter37_reg;
        icmp_ln140_reg_273_pp0_iter39_reg <= icmp_ln140_reg_273_pp0_iter38_reg;
        icmp_ln140_reg_273_pp0_iter3_reg <= icmp_ln140_reg_273_pp0_iter2_reg;
        icmp_ln140_reg_273_pp0_iter40_reg <= icmp_ln140_reg_273_pp0_iter39_reg;
        icmp_ln140_reg_273_pp0_iter41_reg <= icmp_ln140_reg_273_pp0_iter40_reg;
        icmp_ln140_reg_273_pp0_iter42_reg <= icmp_ln140_reg_273_pp0_iter41_reg;
        icmp_ln140_reg_273_pp0_iter43_reg <= icmp_ln140_reg_273_pp0_iter42_reg;
        icmp_ln140_reg_273_pp0_iter44_reg <= icmp_ln140_reg_273_pp0_iter43_reg;
        icmp_ln140_reg_273_pp0_iter45_reg <= icmp_ln140_reg_273_pp0_iter44_reg;
        icmp_ln140_reg_273_pp0_iter46_reg <= icmp_ln140_reg_273_pp0_iter45_reg;
        icmp_ln140_reg_273_pp0_iter4_reg <= icmp_ln140_reg_273_pp0_iter3_reg;
        icmp_ln140_reg_273_pp0_iter5_reg <= icmp_ln140_reg_273_pp0_iter4_reg;
        icmp_ln140_reg_273_pp0_iter6_reg <= icmp_ln140_reg_273_pp0_iter5_reg;
        icmp_ln140_reg_273_pp0_iter7_reg <= icmp_ln140_reg_273_pp0_iter6_reg;
        icmp_ln140_reg_273_pp0_iter8_reg <= icmp_ln140_reg_273_pp0_iter7_reg;
        icmp_ln140_reg_273_pp0_iter9_reg <= icmp_ln140_reg_273_pp0_iter8_reg;
        x_reg_297 <= grp_fu_153_p2;
        zext_ln141_reg_277_pp0_iter10_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter9_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter11_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter10_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter12_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter11_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter13_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter12_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter14_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter13_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter15_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter14_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter16_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter15_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter17_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter16_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter18_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter17_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter19_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter18_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter20_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter19_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter21_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter20_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter22_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter21_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter23_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter22_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter24_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter23_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter25_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter24_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter26_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter25_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter27_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter26_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter28_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter27_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter29_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter28_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter2_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter1_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter30_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter29_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter31_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter30_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter32_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter31_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter33_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter32_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter34_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter33_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter35_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter34_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter36_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter35_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter37_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter36_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter38_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter37_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter39_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter38_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter3_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter2_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter40_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter39_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter41_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter40_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter42_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter41_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter43_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter42_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter44_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter43_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter45_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter44_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter4_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter3_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter5_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter4_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter6_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter5_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter7_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter6_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter8_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter7_reg[31 : 0];
        zext_ln141_reg_277_pp0_iter9_reg[31 : 0] <= zext_ln141_reg_277_pp0_iter8_reg[31 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        childNode_2_reg_268 <= ap_sig_allocacmp_childNode_2;
        childNode_2_reg_268_pp0_iter1_reg <= childNode_2_reg_268;
        icmp_ln140_reg_273 <= icmp_ln140_fu_141_p2;
        icmp_ln140_reg_273_pp0_iter1_reg <= icmp_ln140_reg_273;
        zext_ln141_reg_277[31 : 0] <= zext_ln141_fu_147_p1[31 : 0];
        zext_ln141_reg_277_pp0_iter1_reg[31 : 0] <= zext_ln141_reg_277[31 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp115)) begin
        sext_ln_reg_302 <= grp_sqrt_fixed_32_16_s_fu_118_ap_return;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln140_fu_141_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter47_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_idle_pp0 == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter48 == 1'b0) 
    & (ap_enable_reg_pp0_iter47 == 1'b0) & (ap_enable_reg_pp0_iter46 == 1'b0) & (ap_enable_reg_pp0_iter45 == 1'b0) & (ap_enable_reg_pp0_iter44 == 1'b0) & (ap_enable_reg_pp0_iter43 == 1'b0) & (ap_enable_reg_pp0_iter42 == 1'b0) & (ap_enable_reg_pp0_iter41 == 1'b0) & (ap_enable_reg_pp0_iter40 == 1'b0) & (ap_enable_reg_pp0_iter39 == 1'b0) & (ap_enable_reg_pp0_iter38 == 1'b0) & (ap_enable_reg_pp0_iter37 == 1'b0) & (ap_enable_reg_pp0_iter36 == 1'b0) & (ap_enable_reg_pp0_iter35 == 1'b0) & (ap_enable_reg_pp0_iter34 == 1'b0) & (ap_enable_reg_pp0_iter33 == 1'b0) & (ap_enable_reg_pp0_iter32 == 1'b0) & (ap_enable_reg_pp0_iter31 == 1'b0) & (ap_enable_reg_pp0_iter30 == 1'b0) & (ap_enable_reg_pp0_iter29 == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ap_sig_allocacmp_childNode_2 = bestChildNode_7;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ap_sig_allocacmp_childNode_2 = this_nextSiblings_q0;
        end else begin
            ap_sig_allocacmp_childNode_2 = bestChildNode_3_fu_52;
        end
    end else begin
        ap_sig_allocacmp_childNode_2 = bestChildNode_3_fu_52;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter47_reg == 1'b1) & (icmp_ln140_reg_273_pp0_iter46_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        bestChildNode_out_ap_vld = 1'b1;
    end else begin
        bestChildNode_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter46 == 1'b1))) begin
        this_meanQ_ce0_local = 1'b1;
    end else begin
        this_meanQ_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        this_nextSiblings_ce0_local = 1'b1;
    end else begin
        this_nextSiblings_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        this_visitCounts_ce0_local = 1'b1;
    end else begin
        this_visitCounts_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp115 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp108 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bestChildNode_5_fu_211_p3 = ((icmp_ln145_fu_197_p2[0:0] == 1'b1) ? childNode_2_reg_268_pp0_iter47_reg : bestChildNode_fu_48);

assign bestChildNode_out = bestChildNode_fu_48;

assign bestChildUCT_2_fu_203_p3 = ((icmp_ln145_fu_197_p2[0:0] == 1'b1) ? sext_ln144_1_fu_193_p1 : bestChildUCT_fu_56);

assign childUCT_fu_184_p4 = {{grp_fu_232_p3[40:15]}};

assign grp_fu_232_p0 = grp_fu_232_p00;

assign grp_fu_232_p00 = sext_ln_reg_302;

assign grp_fu_232_p1 = 40'd46202;

assign icmp_ln140_fu_141_p2 = ((ap_sig_allocacmp_childNode_2 == 32'd4294967295) ? 1'b1 : 1'b0);

assign icmp_ln145_fu_197_p2 = (($signed(sext_ln144_1_fu_193_p1) > $signed(bestChildUCT_fu_56)) ? 1'b1 : 1'b0);

assign sext_ln144_1_fu_193_p1 = $signed(childUCT_fu_184_p4);

assign shl_ln_fu_166_p3 = {{this_meanQ_q0}, {16'd0}};

assign this_meanQ_address0 = zext_ln141_reg_277_pp0_iter45_reg;

assign this_meanQ_ce0 = this_meanQ_ce0_local;

assign this_nextSiblings_address0 = zext_ln141_fu_147_p1;

assign this_nextSiblings_ce0 = this_nextSiblings_ce0_local;

assign this_visitCounts_address0 = zext_ln141_fu_147_p1;

assign this_visitCounts_ce0 = this_visitCounts_ce0_local;

assign zext_ln141_fu_147_p1 = ap_sig_allocacmp_childNode_2;

always @ (posedge ap_clk) begin
    zext_ln141_reg_277[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter1_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter2_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter3_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter4_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter5_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter6_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter7_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter8_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter9_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter10_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter11_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter12_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter13_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter14_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter15_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter16_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter17_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter18_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter19_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter20_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter21_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter22_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter23_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter24_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter25_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter26_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter27_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter28_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter29_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter30_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter31_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter32_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter33_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter34_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter35_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter36_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter37_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter38_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter39_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter40_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter41_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter42_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter43_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter44_reg[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln141_reg_277_pp0_iter45_reg[63:32] <= 32'b00000000000000000000000000000000;
end

endmodule //dut_forward_Pipeline_VITIS_LOOP_140_2
