// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module dut_dut_Pipeline_VITIS_LOOP_27_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        strm_in_dout,
        strm_in_empty_n,
        strm_in_read,
        player2_out,
        player2_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 4'd1;
parameter    ap_ST_fsm_pp0_stage1 = 4'd2;
parameter    ap_ST_fsm_pp0_stage2 = 4'd4;
parameter    ap_ST_fsm_pp0_stage3 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] strm_in_dout;
input   strm_in_empty_n;
output   strm_in_read;
output  [48:0] player2_out;
output   player2_out_ap_vld;

reg ap_idle;
reg strm_in_read;
reg player2_out_ap_vld;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln27_fu_204_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg    strm_in_blk_n;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_grp1;
reg   [0:0] icmp_ln27_reg_1231;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] empty_fu_216_p1;
reg   [0:0] empty_reg_1235;
wire   [48:0] player2_12_fu_514_p4;
reg   [48:0] player2_12_reg_1271;
reg    ap_block_state2_pp0_stage1_iter0_grp1;
reg    ap_block_pp0_stage1_11001_grp1;
reg   [0:0] tmp_273_reg_1276;
reg   [0:0] tmp_275_reg_1281;
reg   [0:0] tmp_277_reg_1286;
reg   [0:0] tmp_279_reg_1291;
reg   [0:0] tmp_281_reg_1296;
reg   [0:0] tmp_283_reg_1301;
reg   [0:0] tmp_285_reg_1306;
reg   [0:0] tmp_287_reg_1311;
reg   [0:0] tmp_289_reg_1316;
reg   [0:0] tmp_291_reg_1321;
reg   [0:0] tmp_293_reg_1326;
reg   [0:0] tmp_295_reg_1331;
reg   [0:0] tmp_297_reg_1336;
reg   [0:0] tmp_299_reg_1341;
reg   [0:0] tmp_301_reg_1346;
reg   [0:0] tmp_303_reg_1351;
reg   [0:0] tmp_305_reg_1356;
reg   [0:0] tmp_307_reg_1361;
reg   [0:0] tmp_309_reg_1366;
reg   [0:0] tmp_311_reg_1371;
wire   [48:0] player2_27_fu_905_p3;
reg   [48:0] player2_27_reg_1376;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
wire   [48:0] player2_33_fu_993_p3;
reg   [48:0] player2_33_reg_1382;
wire    ap_block_pp0_stage3_11001;
wire   [5:0] idx_25_fu_1001_p3;
reg   [5:0] idx_25_reg_1388;
wire   [0:0] icmp_ln31_8_fu_1008_p2;
reg   [0:0] icmp_ln31_8_reg_1393;
reg   [48:0] player2_fu_170;
wire   [48:0] player2_47_fu_1199_p3;
wire    ap_block_pp0_stage0;
wire    ap_loop_init;
reg   [1:0] word_fu_174;
wire   [1:0] word_2_fu_210_p2;
reg   [1:0] ap_sig_allocacmp_word_1;
wire    ap_block_pp0_stage0_01001;
wire   [5:0] player2_1_fu_239_p2;
wire   [0:0] player2_1_fu_239_p3;
wire   [48:0] player2_1_fu_239_p4;
wire   [5:0] player2_2_fu_264_p2;
wire   [0:0] player2_2_fu_264_p3;
wire   [48:0] player2_2_fu_264_p4;
wire   [5:0] player2_3_fu_289_p2;
wire   [0:0] player2_3_fu_289_p3;
wire   [48:0] player2_3_fu_289_p4;
wire   [5:0] player2_4_fu_314_p2;
wire   [0:0] player2_4_fu_314_p3;
wire   [48:0] player2_4_fu_314_p4;
wire   [5:0] player2_5_fu_339_p2;
wire   [0:0] player2_5_fu_339_p3;
wire   [48:0] player2_5_fu_339_p4;
wire   [5:0] player2_6_fu_364_p2;
wire   [0:0] player2_6_fu_364_p3;
wire   [48:0] player2_6_fu_364_p4;
wire   [5:0] player2_7_fu_389_p2;
wire   [0:0] player2_7_fu_389_p3;
wire   [48:0] player2_7_fu_389_p4;
wire   [5:0] player2_8_fu_414_p2;
wire   [0:0] player2_8_fu_414_p3;
wire   [48:0] player2_8_fu_414_p4;
wire   [5:0] player2_9_fu_439_p2;
wire   [0:0] player2_9_fu_439_p3;
wire   [48:0] player2_9_fu_439_p4;
wire   [5:0] player2_10_fu_464_p2;
wire   [0:0] player2_10_fu_464_p3;
wire   [48:0] player2_10_fu_464_p4;
wire   [5:0] player2_11_fu_489_p2;
wire   [0:0] player2_11_fu_489_p3;
wire   [48:0] player2_11_fu_489_p4;
wire   [5:0] player2_12_fu_514_p2;
wire   [0:0] player2_12_fu_514_p3;
wire    ap_block_pp0_stage2;
wire   [5:0] player2_13_fu_691_p2;
wire   [48:0] player2_13_fu_691_p4;
wire   [5:0] player2_14_fu_706_p2;
wire   [48:0] player2_14_fu_706_p4;
wire   [5:0] player2_15_fu_722_p2;
wire   [48:0] player2_15_fu_722_p4;
wire   [5:0] player2_16_fu_738_p2;
wire   [48:0] player2_16_fu_738_p4;
wire   [5:0] player2_17_fu_754_p2;
wire   [5:0] idx_17_fu_763_p3;
wire   [48:0] player2_17_fu_754_p4;
wire   [0:0] icmp_ln31_fu_770_p2;
wire   [48:0] player2_18_fu_776_p4;
wire   [5:0] idx_18_fu_793_p3;
wire   [48:0] player2_19_fu_785_p3;
wire   [0:0] icmp_ln31_1_fu_800_p2;
wire   [48:0] player2_20_fu_806_p4;
wire   [5:0] idx_19_fu_823_p3;
wire   [48:0] player2_21_fu_815_p3;
wire   [0:0] icmp_ln31_2_fu_830_p2;
wire   [48:0] player2_22_fu_836_p4;
wire   [5:0] idx_20_fu_853_p3;
wire   [48:0] player2_23_fu_845_p3;
wire   [0:0] icmp_ln31_3_fu_860_p2;
wire   [48:0] player2_24_fu_866_p4;
wire   [5:0] idx_21_fu_883_p3;
wire   [48:0] player2_25_fu_875_p3;
wire   [0:0] icmp_ln31_4_fu_890_p2;
wire   [48:0] player2_26_fu_896_p4;
wire    ap_block_pp0_stage3;
wire   [5:0] idx_22_fu_913_p3;
wire   [0:0] icmp_ln31_5_fu_920_p2;
wire   [48:0] player2_28_fu_926_p4;
wire   [5:0] idx_23_fu_941_p3;
wire   [48:0] player2_29_fu_934_p3;
wire   [0:0] icmp_ln31_6_fu_948_p2;
wire   [48:0] player2_30_fu_954_p4;
wire   [5:0] idx_24_fu_971_p3;
wire   [48:0] player2_31_fu_963_p3;
wire   [0:0] icmp_ln31_7_fu_978_p2;
wire   [48:0] player2_32_fu_984_p4;
wire   [48:0] player2_34_fu_1014_p4;
wire   [5:0] idx_26_fu_1027_p3;
wire   [48:0] player2_35_fu_1021_p3;
wire   [0:0] icmp_ln31_9_fu_1034_p2;
wire   [48:0] player2_36_fu_1040_p4;
wire   [5:0] idx_27_fu_1057_p3;
wire   [48:0] player2_37_fu_1049_p3;
wire   [0:0] icmp_ln31_10_fu_1064_p2;
wire   [48:0] player2_38_fu_1070_p4;
wire   [5:0] idx_28_fu_1087_p3;
wire   [48:0] player2_39_fu_1079_p3;
wire   [0:0] icmp_ln31_11_fu_1094_p2;
wire   [48:0] player2_40_fu_1100_p4;
wire   [5:0] idx_29_fu_1117_p3;
wire   [48:0] player2_41_fu_1109_p3;
wire   [0:0] icmp_ln31_12_fu_1124_p2;
wire   [48:0] player2_42_fu_1130_p4;
wire   [5:0] idx_30_fu_1147_p3;
wire   [48:0] player2_43_fu_1139_p3;
wire   [0:0] icmp_ln31_13_fu_1154_p2;
wire   [48:0] player2_44_fu_1160_p4;
wire   [5:0] idx_31_fu_1177_p3;
wire   [48:0] player2_45_fu_1169_p3;
wire   [0:0] icmp_ln31_14_fu_1184_p2;
wire   [48:0] player2_46_fu_1190_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0_1to1;
reg    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [48:0] player2_1_fu_239_p0;
wire   [48:0] player2_2_fu_264_p0;
wire   [48:0] player2_3_fu_289_p0;
wire   [48:0] player2_4_fu_314_p0;
wire   [48:0] player2_5_fu_339_p0;
wire   [48:0] player2_6_fu_364_p0;
wire   [48:0] player2_7_fu_389_p0;
wire   [48:0] player2_8_fu_414_p0;
wire   [48:0] player2_9_fu_439_p0;
wire   [48:0] player2_10_fu_464_p0;
wire   [48:0] player2_11_fu_489_p0;
wire   [48:0] player2_12_fu_514_p0;
wire   [48:0] player2_13_fu_691_p0;
wire   [48:0] player2_14_fu_706_p0;
wire   [48:0] player2_15_fu_722_p0;
wire   [48:0] player2_16_fu_738_p0;
wire   [48:0] player2_17_fu_754_p0;
wire   [48:0] player2_18_fu_776_p0;
wire   [48:0] player2_20_fu_806_p0;
wire   [48:0] player2_22_fu_836_p0;
wire   [48:0] player2_24_fu_866_p0;
wire   [48:0] player2_26_fu_896_p0;
wire   [48:0] player2_28_fu_926_p0;
wire   [48:0] player2_30_fu_954_p0;
wire   [48:0] player2_32_fu_984_p0;
wire   [48:0] player2_34_fu_1014_p0;
wire   [48:0] player2_36_fu_1040_p0;
wire   [48:0] player2_38_fu_1070_p0;
wire   [48:0] player2_40_fu_1100_p0;
wire   [48:0] player2_42_fu_1130_p0;
wire   [48:0] player2_44_fu_1160_p0;
wire   [48:0] player2_46_fu_1190_p0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 player2_fu_170 = 49'd0;
#0 word_fu_174 = 2'd0;
#0 ap_done_reg = 1'b0;
end

dut_bitset_49ns_49ns_6ns_1ns_49_1_1 #(
    .DATAWIDTH( 49 ),
    .ADDRWIDTH( 6 ))
bitset_49ns_49ns_6ns_1ns_49_1_1_U36(
    .din(player2_fu_170),
    .sel(player2_1_fu_239_p2),
    .value(player2_1_fu_239_p3),
    .dout(player2_1_fu_239_p4)
);

dut_bitset_49ns_49ns_6ns_1ns_49_1_1 #(
    .DATAWIDTH( 49 ),
    .ADDRWIDTH( 6 ))
bitset_49ns_49ns_6ns_1ns_49_1_1_U37(
    .din(player2_1_fu_239_p4),
    .sel(player2_2_fu_264_p2),
    .value(player2_2_fu_264_p3),
    .dout(player2_2_fu_264_p4)
);

dut_bitset_49ns_49ns_6ns_1ns_49_1_1 #(
    .DATAWIDTH( 49 ),
    .ADDRWIDTH( 6 ))
bitset_49ns_49ns_6ns_1ns_49_1_1_U38(
    .din(player2_2_fu_264_p4),
    .sel(player2_3_fu_289_p2),
    .value(player2_3_fu_289_p3),
    .dout(player2_3_fu_289_p4)
);

dut_bitset_49ns_49ns_6ns_1ns_49_1_1 #(
    .DATAWIDTH( 49 ),
    .ADDRWIDTH( 6 ))
bitset_49ns_49ns_6ns_1ns_49_1_1_U39(
    .din(player2_3_fu_289_p4),
    .sel(player2_4_fu_314_p2),
    .value(player2_4_fu_314_p3),
    .dout(player2_4_fu_314_p4)
);

dut_bitset_49ns_49ns_6ns_1ns_49_1_1 #(
    .DATAWIDTH( 49 ),
    .ADDRWIDTH( 6 ))
bitset_49ns_49ns_6ns_1ns_49_1_1_U40(
    .din(player2_4_fu_314_p4),
    .sel(player2_5_fu_339_p2),
    .value(player2_5_fu_339_p3),
    .dout(player2_5_fu_339_p4)
);

dut_bitset_49ns_49ns_6ns_1ns_49_1_1 #(
    .DATAWIDTH( 49 ),
    .ADDRWIDTH( 6 ))
bitset_49ns_49ns_6ns_1ns_49_1_1_U41(
    .din(player2_5_fu_339_p4),
    .sel(player2_6_fu_364_p2),
    .value(player2_6_fu_364_p3),
    .dout(player2_6_fu_364_p4)
);

dut_bitset_49ns_49ns_6ns_1ns_49_1_1 #(
    .DATAWIDTH( 49 ),
    .ADDRWIDTH( 6 ))
bitset_49ns_49ns_6ns_1ns_49_1_1_U42(
    .din(player2_6_fu_364_p4),
    .sel(player2_7_fu_389_p2),
    .value(player2_7_fu_389_p3),
    .dout(player2_7_fu_389_p4)
);

dut_bitset_49ns_49ns_6ns_1ns_49_1_1 #(
    .DATAWIDTH( 49 ),
    .ADDRWIDTH( 6 ))
bitset_49ns_49ns_6ns_1ns_49_1_1_U43(
    .din(player2_7_fu_389_p4),
    .sel(player2_8_fu_414_p2),
    .value(player2_8_fu_414_p3),
    .dout(player2_8_fu_414_p4)
);

dut_bitset_49ns_49ns_6ns_1ns_49_1_1 #(
    .DATAWIDTH( 49 ),
    .ADDRWIDTH( 6 ))
bitset_49ns_49ns_6ns_1ns_49_1_1_U44(
    .din(player2_8_fu_414_p4),
    .sel(player2_9_fu_439_p2),
    .value(player2_9_fu_439_p3),
    .dout(player2_9_fu_439_p4)
);

dut_bitset_49ns_49ns_6ns_1ns_49_1_1 #(
    .DATAWIDTH( 49 ),
    .ADDRWIDTH( 6 ))
bitset_49ns_49ns_6ns_1ns_49_1_1_U45(
    .din(player2_9_fu_439_p4),
    .sel(player2_10_fu_464_p2),
    .value(player2_10_fu_464_p3),
    .dout(player2_10_fu_464_p4)
);

dut_bitset_49ns_49ns_6ns_1ns_49_1_1 #(
    .DATAWIDTH( 49 ),
    .ADDRWIDTH( 6 ))
bitset_49ns_49ns_6ns_1ns_49_1_1_U46(
    .din(player2_10_fu_464_p4),
    .sel(player2_11_fu_489_p2),
    .value(player2_11_fu_489_p3),
    .dout(player2_11_fu_489_p4)
);

dut_bitset_49ns_49ns_6ns_1ns_49_1_1 #(
    .DATAWIDTH( 49 ),
    .ADDRWIDTH( 6 ))
bitset_49ns_49ns_6ns_1ns_49_1_1_U47(
    .din(player2_11_fu_489_p4),
    .sel(player2_12_fu_514_p2),
    .value(player2_12_fu_514_p3),
    .dout(player2_12_fu_514_p4)
);

dut_bitset_49ns_49ns_6ns_1ns_49_1_1 #(
    .DATAWIDTH( 49 ),
    .ADDRWIDTH( 6 ))
bitset_49ns_49ns_6ns_1ns_49_1_1_U48(
    .din(player2_12_reg_1271),
    .sel(player2_13_fu_691_p2),
    .value(tmp_273_reg_1276),
    .dout(player2_13_fu_691_p4)
);

dut_bitset_49ns_49ns_6ns_1ns_49_1_1 #(
    .DATAWIDTH( 49 ),
    .ADDRWIDTH( 6 ))
bitset_49ns_49ns_6ns_1ns_49_1_1_U49(
    .din(player2_13_fu_691_p4),
    .sel(player2_14_fu_706_p2),
    .value(tmp_275_reg_1281),
    .dout(player2_14_fu_706_p4)
);

dut_bitset_49ns_49ns_6ns_1ns_49_1_1 #(
    .DATAWIDTH( 49 ),
    .ADDRWIDTH( 6 ))
bitset_49ns_49ns_6ns_1ns_49_1_1_U50(
    .din(player2_14_fu_706_p4),
    .sel(player2_15_fu_722_p2),
    .value(tmp_277_reg_1286),
    .dout(player2_15_fu_722_p4)
);

dut_bitset_49ns_49ns_6ns_1ns_49_1_1 #(
    .DATAWIDTH( 49 ),
    .ADDRWIDTH( 6 ))
bitset_49ns_49ns_6ns_1ns_49_1_1_U51(
    .din(player2_15_fu_722_p4),
    .sel(player2_16_fu_738_p2),
    .value(tmp_279_reg_1291),
    .dout(player2_16_fu_738_p4)
);

dut_bitset_49ns_49ns_6ns_1ns_49_1_1 #(
    .DATAWIDTH( 49 ),
    .ADDRWIDTH( 6 ))
bitset_49ns_49ns_6ns_1ns_49_1_1_U52(
    .din(player2_16_fu_738_p4),
    .sel(player2_17_fu_754_p2),
    .value(tmp_281_reg_1296),
    .dout(player2_17_fu_754_p4)
);

dut_bitset_49ns_49ns_6ns_1ns_49_1_1 #(
    .DATAWIDTH( 49 ),
    .ADDRWIDTH( 6 ))
bitset_49ns_49ns_6ns_1ns_49_1_1_U53(
    .din(player2_17_fu_754_p4),
    .sel(idx_17_fu_763_p3),
    .value(tmp_283_reg_1301),
    .dout(player2_18_fu_776_p4)
);

dut_bitset_49ns_49ns_6ns_1ns_49_1_1 #(
    .DATAWIDTH( 49 ),
    .ADDRWIDTH( 6 ))
bitset_49ns_49ns_6ns_1ns_49_1_1_U54(
    .din(player2_19_fu_785_p3),
    .sel(idx_18_fu_793_p3),
    .value(tmp_285_reg_1306),
    .dout(player2_20_fu_806_p4)
);

dut_bitset_49ns_49ns_6ns_1ns_49_1_1 #(
    .DATAWIDTH( 49 ),
    .ADDRWIDTH( 6 ))
bitset_49ns_49ns_6ns_1ns_49_1_1_U55(
    .din(player2_21_fu_815_p3),
    .sel(idx_19_fu_823_p3),
    .value(tmp_287_reg_1311),
    .dout(player2_22_fu_836_p4)
);

dut_bitset_49ns_49ns_6ns_1ns_49_1_1 #(
    .DATAWIDTH( 49 ),
    .ADDRWIDTH( 6 ))
bitset_49ns_49ns_6ns_1ns_49_1_1_U56(
    .din(player2_23_fu_845_p3),
    .sel(idx_20_fu_853_p3),
    .value(tmp_289_reg_1316),
    .dout(player2_24_fu_866_p4)
);

dut_bitset_49ns_49ns_6ns_1ns_49_1_1 #(
    .DATAWIDTH( 49 ),
    .ADDRWIDTH( 6 ))
bitset_49ns_49ns_6ns_1ns_49_1_1_U57(
    .din(player2_25_fu_875_p3),
    .sel(idx_21_fu_883_p3),
    .value(tmp_291_reg_1321),
    .dout(player2_26_fu_896_p4)
);

dut_bitset_49ns_49ns_6ns_1ns_49_1_1 #(
    .DATAWIDTH( 49 ),
    .ADDRWIDTH( 6 ))
bitset_49ns_49ns_6ns_1ns_49_1_1_U58(
    .din(player2_27_reg_1376),
    .sel(idx_22_fu_913_p3),
    .value(tmp_293_reg_1326),
    .dout(player2_28_fu_926_p4)
);

dut_bitset_49ns_49ns_6ns_1ns_49_1_1 #(
    .DATAWIDTH( 49 ),
    .ADDRWIDTH( 6 ))
bitset_49ns_49ns_6ns_1ns_49_1_1_U59(
    .din(player2_29_fu_934_p3),
    .sel(idx_23_fu_941_p3),
    .value(tmp_295_reg_1331),
    .dout(player2_30_fu_954_p4)
);

dut_bitset_49ns_49ns_6ns_1ns_49_1_1 #(
    .DATAWIDTH( 49 ),
    .ADDRWIDTH( 6 ))
bitset_49ns_49ns_6ns_1ns_49_1_1_U60(
    .din(player2_31_fu_963_p3),
    .sel(idx_24_fu_971_p3),
    .value(tmp_297_reg_1336),
    .dout(player2_32_fu_984_p4)
);

dut_bitset_49ns_49ns_6ns_1ns_49_1_1 #(
    .DATAWIDTH( 49 ),
    .ADDRWIDTH( 6 ))
bitset_49ns_49ns_6ns_1ns_49_1_1_U61(
    .din(player2_33_reg_1382),
    .sel(idx_25_reg_1388),
    .value(tmp_299_reg_1341),
    .dout(player2_34_fu_1014_p4)
);

dut_bitset_49ns_49ns_6ns_1ns_49_1_1 #(
    .DATAWIDTH( 49 ),
    .ADDRWIDTH( 6 ))
bitset_49ns_49ns_6ns_1ns_49_1_1_U62(
    .din(player2_35_fu_1021_p3),
    .sel(idx_26_fu_1027_p3),
    .value(tmp_301_reg_1346),
    .dout(player2_36_fu_1040_p4)
);

dut_bitset_49ns_49ns_6ns_1ns_49_1_1 #(
    .DATAWIDTH( 49 ),
    .ADDRWIDTH( 6 ))
bitset_49ns_49ns_6ns_1ns_49_1_1_U63(
    .din(player2_37_fu_1049_p3),
    .sel(idx_27_fu_1057_p3),
    .value(tmp_303_reg_1351),
    .dout(player2_38_fu_1070_p4)
);

dut_bitset_49ns_49ns_6ns_1ns_49_1_1 #(
    .DATAWIDTH( 49 ),
    .ADDRWIDTH( 6 ))
bitset_49ns_49ns_6ns_1ns_49_1_1_U64(
    .din(player2_39_fu_1079_p3),
    .sel(idx_28_fu_1087_p3),
    .value(tmp_305_reg_1356),
    .dout(player2_40_fu_1100_p4)
);

dut_bitset_49ns_49ns_6ns_1ns_49_1_1 #(
    .DATAWIDTH( 49 ),
    .ADDRWIDTH( 6 ))
bitset_49ns_49ns_6ns_1ns_49_1_1_U65(
    .din(player2_41_fu_1109_p3),
    .sel(idx_29_fu_1117_p3),
    .value(tmp_307_reg_1361),
    .dout(player2_42_fu_1130_p4)
);

dut_bitset_49ns_49ns_6ns_1ns_49_1_1 #(
    .DATAWIDTH( 49 ),
    .ADDRWIDTH( 6 ))
bitset_49ns_49ns_6ns_1ns_49_1_1_U66(
    .din(player2_43_fu_1139_p3),
    .sel(idx_30_fu_1147_p3),
    .value(tmp_309_reg_1366),
    .dout(player2_44_fu_1160_p4)
);

dut_bitset_49ns_49ns_6ns_1ns_49_1_1 #(
    .DATAWIDTH( 49 ),
    .ADDRWIDTH( 6 ))
bitset_49ns_49ns_6ns_1ns_49_1_1_U67(
    .din(player2_45_fu_1169_p3),
    .sel(idx_31_fu_1177_p3),
    .value(tmp_311_reg_1371),
    .dout(player2_46_fu_1190_p4)
);

dut_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            player2_fu_170 <= 49'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            player2_fu_170 <= player2_47_fu_1199_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln27_fu_204_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            word_fu_174 <= word_2_fu_210_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            word_fu_174 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_reg_1235 <= empty_fu_216_p1;
        icmp_ln27_reg_1231 <= icmp_ln27_fu_204_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        icmp_ln31_8_reg_1393 <= icmp_ln31_8_fu_1008_p2;
        idx_25_reg_1388[5] <= idx_25_fu_1001_p3[5];
        player2_33_reg_1382 <= player2_33_fu_993_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        player2_12_reg_1271 <= player2_12_fu_514_p4;
        tmp_273_reg_1276 <= strm_in_dout[32'd12];
        tmp_275_reg_1281 <= strm_in_dout[32'd13];
        tmp_277_reg_1286 <= strm_in_dout[32'd14];
        tmp_279_reg_1291 <= strm_in_dout[32'd15];
        tmp_281_reg_1296 <= strm_in_dout[32'd16];
        tmp_283_reg_1301 <= strm_in_dout[32'd17];
        tmp_285_reg_1306 <= strm_in_dout[32'd18];
        tmp_287_reg_1311 <= strm_in_dout[32'd19];
        tmp_289_reg_1316 <= strm_in_dout[32'd20];
        tmp_291_reg_1321 <= strm_in_dout[32'd21];
        tmp_293_reg_1326 <= strm_in_dout[32'd22];
        tmp_295_reg_1331 <= strm_in_dout[32'd23];
        tmp_297_reg_1336 <= strm_in_dout[32'd24];
        tmp_299_reg_1341 <= strm_in_dout[32'd25];
        tmp_301_reg_1346 <= strm_in_dout[32'd26];
        tmp_303_reg_1351 <= strm_in_dout[32'd27];
        tmp_305_reg_1356 <= strm_in_dout[32'd28];
        tmp_307_reg_1361 <= strm_in_dout[32'd29];
        tmp_309_reg_1366 <= strm_in_dout[32'd30];
        tmp_311_reg_1371 <= strm_in_dout[32'd31];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        player2_27_reg_1376 <= player2_27_fu_905_p3;
    end
end

always @ (*) begin
    if (((icmp_ln27_fu_204_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_word_1 = 2'd0;
    end else begin
        ap_sig_allocacmp_word_1 = word_fu_174;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln27_fu_204_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        player2_out_ap_vld = 1'b1;
    end else begin
        player2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln27_reg_1231 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        strm_in_blk_n = strm_in_empty_n;
    end else begin
        strm_in_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln27_reg_1231 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        strm_in_read = 1'b1;
    end else begin
        strm_in_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001_grp1 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state2_pp0_stage1_iter0_grp1));
end

assign ap_block_pp0_stage1_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state2_pp0_stage1_iter0_grp1));
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0_grp1 = ((icmp_ln27_reg_1231 == 1'd0) & (strm_in_empty_n == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign empty_fu_216_p1 = ap_sig_allocacmp_word_1[0:0];

assign icmp_ln27_fu_204_p2 = ((ap_sig_allocacmp_word_1 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln31_10_fu_1064_p2 = ((idx_27_fu_1057_p3 < 6'd49) ? 1'b1 : 1'b0);

assign icmp_ln31_11_fu_1094_p2 = ((idx_28_fu_1087_p3 < 6'd49) ? 1'b1 : 1'b0);

assign icmp_ln31_12_fu_1124_p2 = ((idx_29_fu_1117_p3 < 6'd49) ? 1'b1 : 1'b0);

assign icmp_ln31_13_fu_1154_p2 = ((idx_30_fu_1147_p3 < 6'd49) ? 1'b1 : 1'b0);

assign icmp_ln31_14_fu_1184_p2 = ((idx_31_fu_1177_p3 < 6'd49) ? 1'b1 : 1'b0);

assign icmp_ln31_1_fu_800_p2 = ((idx_18_fu_793_p3 < 6'd49) ? 1'b1 : 1'b0);

assign icmp_ln31_2_fu_830_p2 = ((idx_19_fu_823_p3 < 6'd49) ? 1'b1 : 1'b0);

assign icmp_ln31_3_fu_860_p2 = ((idx_20_fu_853_p3 < 6'd49) ? 1'b1 : 1'b0);

assign icmp_ln31_4_fu_890_p2 = ((idx_21_fu_883_p3 < 6'd49) ? 1'b1 : 1'b0);

assign icmp_ln31_5_fu_920_p2 = ((idx_22_fu_913_p3 < 6'd49) ? 1'b1 : 1'b0);

assign icmp_ln31_6_fu_948_p2 = ((idx_23_fu_941_p3 < 6'd49) ? 1'b1 : 1'b0);

assign icmp_ln31_7_fu_978_p2 = ((idx_24_fu_971_p3 < 6'd49) ? 1'b1 : 1'b0);

assign icmp_ln31_8_fu_1008_p2 = ((idx_25_fu_1001_p3 < 6'd49) ? 1'b1 : 1'b0);

assign icmp_ln31_9_fu_1034_p2 = ((idx_26_fu_1027_p3 < 6'd49) ? 1'b1 : 1'b0);

assign icmp_ln31_fu_770_p2 = ((idx_17_fu_763_p3 != 6'd49) ? 1'b1 : 1'b0);

assign idx_17_fu_763_p3 = {{empty_reg_1235}, {5'd17}};

assign idx_18_fu_793_p3 = {{empty_reg_1235}, {5'd18}};

assign idx_19_fu_823_p3 = {{empty_reg_1235}, {5'd19}};

assign idx_20_fu_853_p3 = {{empty_reg_1235}, {5'd20}};

assign idx_21_fu_883_p3 = {{empty_reg_1235}, {5'd21}};

assign idx_22_fu_913_p3 = {{empty_reg_1235}, {5'd22}};

assign idx_23_fu_941_p3 = {{empty_reg_1235}, {5'd23}};

assign idx_24_fu_971_p3 = {{empty_reg_1235}, {5'd24}};

assign idx_25_fu_1001_p3 = {{empty_reg_1235}, {5'd25}};

assign idx_26_fu_1027_p3 = {{empty_reg_1235}, {5'd26}};

assign idx_27_fu_1057_p3 = {{empty_reg_1235}, {5'd27}};

assign idx_28_fu_1087_p3 = {{empty_reg_1235}, {5'd28}};

assign idx_29_fu_1117_p3 = {{empty_reg_1235}, {5'd29}};

assign idx_30_fu_1147_p3 = {{empty_reg_1235}, {5'd30}};

assign idx_31_fu_1177_p3 = {{empty_reg_1235}, {5'd31}};

assign player2_10_fu_464_p2 = {{empty_reg_1235}, {5'd9}};

assign player2_10_fu_464_p3 = strm_in_dout[32'd9];

assign player2_11_fu_489_p2 = {{empty_reg_1235}, {5'd10}};

assign player2_11_fu_489_p3 = strm_in_dout[32'd10];

assign player2_12_fu_514_p2 = {{empty_reg_1235}, {5'd11}};

assign player2_12_fu_514_p3 = strm_in_dout[32'd11];

assign player2_13_fu_691_p2 = {{empty_reg_1235}, {5'd12}};

assign player2_14_fu_706_p2 = {{empty_reg_1235}, {5'd13}};

assign player2_15_fu_722_p2 = {{empty_reg_1235}, {5'd14}};

assign player2_16_fu_738_p2 = {{empty_reg_1235}, {5'd15}};

assign player2_17_fu_754_p2 = {{empty_reg_1235}, {5'd16}};

assign player2_19_fu_785_p3 = ((icmp_ln31_fu_770_p2[0:0] == 1'b1) ? player2_18_fu_776_p4 : player2_17_fu_754_p4);

assign player2_1_fu_239_p2 = {{empty_reg_1235}, {5'd0}};

assign player2_1_fu_239_p3 = strm_in_dout[0:0];

assign player2_21_fu_815_p3 = ((icmp_ln31_1_fu_800_p2[0:0] == 1'b1) ? player2_20_fu_806_p4 : player2_19_fu_785_p3);

assign player2_23_fu_845_p3 = ((icmp_ln31_2_fu_830_p2[0:0] == 1'b1) ? player2_22_fu_836_p4 : player2_21_fu_815_p3);

assign player2_25_fu_875_p3 = ((icmp_ln31_3_fu_860_p2[0:0] == 1'b1) ? player2_24_fu_866_p4 : player2_23_fu_845_p3);

assign player2_27_fu_905_p3 = ((icmp_ln31_4_fu_890_p2[0:0] == 1'b1) ? player2_26_fu_896_p4 : player2_25_fu_875_p3);

assign player2_29_fu_934_p3 = ((icmp_ln31_5_fu_920_p2[0:0] == 1'b1) ? player2_28_fu_926_p4 : player2_27_reg_1376);

assign player2_2_fu_264_p2 = {{empty_reg_1235}, {5'd1}};

assign player2_2_fu_264_p3 = strm_in_dout[32'd1];

assign player2_31_fu_963_p3 = ((icmp_ln31_6_fu_948_p2[0:0] == 1'b1) ? player2_30_fu_954_p4 : player2_29_fu_934_p3);

assign player2_33_fu_993_p3 = ((icmp_ln31_7_fu_978_p2[0:0] == 1'b1) ? player2_32_fu_984_p4 : player2_31_fu_963_p3);

assign player2_35_fu_1021_p3 = ((icmp_ln31_8_reg_1393[0:0] == 1'b1) ? player2_34_fu_1014_p4 : player2_33_reg_1382);

assign player2_37_fu_1049_p3 = ((icmp_ln31_9_fu_1034_p2[0:0] == 1'b1) ? player2_36_fu_1040_p4 : player2_35_fu_1021_p3);

assign player2_39_fu_1079_p3 = ((icmp_ln31_10_fu_1064_p2[0:0] == 1'b1) ? player2_38_fu_1070_p4 : player2_37_fu_1049_p3);

assign player2_3_fu_289_p2 = {{empty_reg_1235}, {5'd2}};

assign player2_3_fu_289_p3 = strm_in_dout[32'd2];

assign player2_41_fu_1109_p3 = ((icmp_ln31_11_fu_1094_p2[0:0] == 1'b1) ? player2_40_fu_1100_p4 : player2_39_fu_1079_p3);

assign player2_43_fu_1139_p3 = ((icmp_ln31_12_fu_1124_p2[0:0] == 1'b1) ? player2_42_fu_1130_p4 : player2_41_fu_1109_p3);

assign player2_45_fu_1169_p3 = ((icmp_ln31_13_fu_1154_p2[0:0] == 1'b1) ? player2_44_fu_1160_p4 : player2_43_fu_1139_p3);

assign player2_47_fu_1199_p3 = ((icmp_ln31_14_fu_1184_p2[0:0] == 1'b1) ? player2_46_fu_1190_p4 : player2_45_fu_1169_p3);

assign player2_4_fu_314_p2 = {{empty_reg_1235}, {5'd3}};

assign player2_4_fu_314_p3 = strm_in_dout[32'd3];

assign player2_5_fu_339_p2 = {{empty_reg_1235}, {5'd4}};

assign player2_5_fu_339_p3 = strm_in_dout[32'd4];

assign player2_6_fu_364_p2 = {{empty_reg_1235}, {5'd5}};

assign player2_6_fu_364_p3 = strm_in_dout[32'd5];

assign player2_7_fu_389_p2 = {{empty_reg_1235}, {5'd6}};

assign player2_7_fu_389_p3 = strm_in_dout[32'd6];

assign player2_8_fu_414_p2 = {{empty_reg_1235}, {5'd7}};

assign player2_8_fu_414_p3 = strm_in_dout[32'd7];

assign player2_9_fu_439_p2 = {{empty_reg_1235}, {5'd8}};

assign player2_9_fu_439_p3 = strm_in_dout[32'd8];

assign player2_out = player2_fu_170;

assign word_2_fu_210_p2 = (ap_sig_allocacmp_word_1 + 2'd1);

always @ (posedge ap_clk) begin
    idx_25_reg_1388[4:0] <= 5'b11001;
end

endmodule //dut_dut_Pipeline_VITIS_LOOP_27_3
