// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module dut_forward_Pipeline_VITIS_LOOP_114_16 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        connected_12,
        gameState_hexGame_player2_8,
        prev_10_out,
        prev_10_out_ap_vld,
        p_out,
        p_out_ap_vld,
        p_out1,
        p_out1_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [48:0] connected_12;
input  [48:0] gameState_hexGame_player2_8;
output  [42:0] prev_10_out;
output   prev_10_out_ap_vld;
output  [0:0] p_out;
output   p_out_ap_vld;
output  [0:0] p_out1;
output   p_out1_ap_vld;

reg ap_idle;
reg prev_10_out_ap_vld;
reg p_out_ap_vld;
reg p_out1_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln125_fu_527_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [48:0] prev_fu_108;
wire   [48:0] or_ln123_16_fu_521_p2;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
wire    ap_block_pp0_stage0_01001;
wire   [0:0] tmp_fu_328_p3;
wire   [0:0] tmp_219_fu_365_p3;
wire   [5:0] tmp_117_fu_168_p4;
wire   [5:0] tmp_118_fu_178_p4;
wire   [5:0] tmp_119_fu_188_p4;
wire   [5:0] tmp_120_fu_198_p4;
wire   [5:0] tmp_121_fu_208_p4;
wire   [40:0] tmp_130_fu_312_p4;
wire   [40:0] tmp_129_fu_288_p11;
wire   [5:0] tmp_s_fu_158_p4;
wire   [40:0] or_ln123_fu_322_p2;
wire   [40:0] trunc_ln123_fu_347_p1;
wire   [47:0] shl_ln123_5_fu_351_p3;
wire   [47:0] or_ln123_s_fu_337_p4;
wire   [47:0] or_ln123_12_fu_359_p2;
wire   [4:0] tmp_127_fu_268_p4;
wire   [5:0] tmp_122_fu_218_p4;
wire   [5:0] tmp_123_fu_228_p4;
wire   [5:0] tmp_124_fu_238_p4;
wire   [5:0] tmp_125_fu_248_p4;
wire   [5:0] tmp_126_fu_258_p4;
wire   [40:0] tmp_131_fu_408_p13;
wire   [40:0] and_ln123_s_fu_382_p12;
wire   [5:0] tmp_128_fu_278_p4;
wire   [0:0] tmp_220_fu_442_p3;
wire   [40:0] or_ln123_13_fu_436_p2;
wire   [5:0] trunc_ln123_5_fu_460_p1;
wire   [47:0] and_ln123_1_fu_464_p15;
wire   [47:0] tmp18_fu_450_p4;
wire   [47:0] or_ln123_14_fu_496_p2;
wire   [48:0] tmp17_fu_502_p3;
wire   [48:0] tmp15_fu_374_p3;
wire   [48:0] or_ln123_15_fu_510_p2;
wire   [48:0] and_ln123_fu_516_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 prev_fu_108 = 49'd0;
#0 ap_done_reg = 1'b0;
end

dut_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            prev_fu_108 <= connected_12;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            prev_fu_108 <= or_ln123_16_fu_521_p2;
        end
    end
end

always @ (*) begin
    if (((icmp_ln125_fu_527_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln125_fu_527_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out1_ap_vld = 1'b1;
    end else begin
        p_out1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln125_fu_527_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_out_ap_vld = 1'b1;
    end else begin
        p_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln125_fu_527_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        prev_10_out_ap_vld = 1'b1;
    end else begin
        prev_10_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign and_ln123_1_fu_464_p15 = {{{{{{{{{{{{{{tmp_127_fu_268_p4}, {1'd0}}, {tmp_122_fu_218_p4}}, {1'd0}}, {tmp_123_fu_228_p4}}, {1'd0}}, {tmp_124_fu_238_p4}}, {1'd0}}, {tmp_125_fu_248_p4}}, {1'd0}}, {tmp_126_fu_258_p4}}, {1'd0}}, {trunc_ln123_5_fu_460_p1}}, {1'd0}};

assign and_ln123_fu_516_p2 = (or_ln123_15_fu_510_p2 & gameState_hexGame_player2_8);

assign and_ln123_s_fu_382_p12 = {{{{{{{{{{{tmp_s_fu_158_p4}, {1'd0}}, {tmp_117_fu_168_p4}}, {1'd0}}, {tmp_118_fu_178_p4}}, {1'd0}}, {tmp_119_fu_188_p4}}, {1'd0}}, {tmp_120_fu_198_p4}}, {1'd0}}, {tmp_121_fu_208_p4}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln125_fu_527_p2 = ((or_ln123_16_fu_521_p2 == prev_fu_108) ? 1'b1 : 1'b0);

assign or_ln123_12_fu_359_p2 = (shl_ln123_5_fu_351_p3 | or_ln123_s_fu_337_p4);

assign or_ln123_13_fu_436_p2 = (tmp_131_fu_408_p13 | and_ln123_s_fu_382_p12);

assign or_ln123_14_fu_496_p2 = (tmp18_fu_450_p4 | and_ln123_1_fu_464_p15);

assign or_ln123_15_fu_510_p2 = (tmp17_fu_502_p3 | tmp15_fu_374_p3);

assign or_ln123_16_fu_521_p2 = (prev_fu_108 | and_ln123_fu_516_p2);

assign or_ln123_fu_322_p2 = (tmp_130_fu_312_p4 | tmp_129_fu_288_p11);

assign or_ln123_s_fu_337_p4 = {{{tmp_s_fu_158_p4}, {tmp_fu_328_p3}}, {or_ln123_fu_322_p2}};

assign p_out = prev_fu_108[32'd48];

assign p_out1 = prev_fu_108[32'd41];

assign prev_10_out = prev_fu_108[42:0];

assign shl_ln123_5_fu_351_p3 = {{trunc_ln123_fu_347_p1}, {7'd0}};

assign tmp15_fu_374_p3 = {{tmp_219_fu_365_p3}, {or_ln123_12_fu_359_p2}};

assign tmp17_fu_502_p3 = {{tmp_220_fu_442_p3}, {or_ln123_14_fu_496_p2}};

assign tmp18_fu_450_p4 = {{{tmp_128_fu_278_p4}, {tmp_220_fu_442_p3}}, {or_ln123_13_fu_436_p2}};

assign tmp_117_fu_168_p4 = {{prev_fu_108[34:29]}};

assign tmp_118_fu_178_p4 = {{prev_fu_108[27:22]}};

assign tmp_119_fu_188_p4 = {{prev_fu_108[20:15]}};

assign tmp_120_fu_198_p4 = {{prev_fu_108[13:8]}};

assign tmp_121_fu_208_p4 = {{prev_fu_108[6:1]}};

assign tmp_122_fu_218_p4 = {{prev_fu_108[40:35]}};

assign tmp_123_fu_228_p4 = {{prev_fu_108[33:28]}};

assign tmp_124_fu_238_p4 = {{prev_fu_108[26:21]}};

assign tmp_125_fu_248_p4 = {{prev_fu_108[19:14]}};

assign tmp_126_fu_258_p4 = {{prev_fu_108[12:7]}};

assign tmp_127_fu_268_p4 = {{prev_fu_108[46:42]}};

assign tmp_128_fu_278_p4 = {{prev_fu_108[48:43]}};

assign tmp_129_fu_288_p11 = {{{{{{{{{{tmp_117_fu_168_p4}, {1'd0}}, {tmp_118_fu_178_p4}}, {1'd0}}, {tmp_119_fu_188_p4}}, {1'd0}}, {tmp_120_fu_198_p4}}, {1'd0}}, {tmp_121_fu_208_p4}}, {7'd0}};

assign tmp_130_fu_312_p4 = {{prev_fu_108[47:7]}};

assign tmp_131_fu_408_p13 = {{{{{{{{{{{{tmp_127_fu_268_p4}, {1'd0}}, {tmp_122_fu_218_p4}}, {1'd0}}, {tmp_123_fu_228_p4}}, {1'd0}}, {tmp_124_fu_238_p4}}, {1'd0}}, {tmp_125_fu_248_p4}}, {1'd0}}, {tmp_126_fu_258_p4}}, {1'd0}};

assign tmp_219_fu_365_p3 = prev_fu_108[32'd41];

assign tmp_220_fu_442_p3 = prev_fu_108[32'd47];

assign tmp_fu_328_p3 = prev_fu_108[32'd48];

assign tmp_s_fu_158_p4 = {{prev_fu_108[41:36]}};

assign trunc_ln123_5_fu_460_p1 = prev_fu_108[5:0];

assign trunc_ln123_fu_347_p1 = prev_fu_108[40:0];

endmodule //dut_forward_Pipeline_VITIS_LOOP_114_16
