// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module dut_forward (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        this_visitCounts_address0,
        this_visitCounts_ce0,
        this_visitCounts_we0,
        this_visitCounts_d0,
        this_visitCounts_q0,
        this_meanQ_address0,
        this_meanQ_ce0,
        this_meanQ_we0,
        this_meanQ_d0,
        this_meanQ_q0,
        this_parents_address0,
        this_parents_ce0,
        this_parents_we0,
        this_parents_d0,
        this_parents_q0,
        this_firstChilds_address0,
        this_firstChilds_ce0,
        this_firstChilds_we0,
        this_firstChilds_d0,
        this_firstChilds_q0,
        this_numChildren_address0,
        this_numChildren_ce0,
        this_numChildren_we0,
        this_numChildren_d0,
        this_numChildren_q0,
        this_nextSiblings_address0,
        this_nextSiblings_ce0,
        this_nextSiblings_we0,
        this_nextSiblings_d0,
        this_nextSiblings_q0,
        this_numLegalActions_address0,
        this_numLegalActions_ce0,
        this_numLegalActions_we0,
        this_numLegalActions_d0,
        this_numLegalActions_q0,
        this_terminals_address0,
        this_terminals_ce0,
        this_terminals_we0,
        this_terminals_d0,
        this_terminals_q0,
        this_childActions_address0,
        this_childActions_ce0,
        this_childActions_we0,
        this_childActions_d0,
        this_childActions_q0,
        this_triedMask_address0,
        this_triedMask_ce0,
        this_triedMask_we0,
        this_triedMask_d0,
        this_triedMask_q0,
        this_isREDs_address0,
        this_isREDs_ce0,
        this_isREDs_we0,
        this_isREDs_d0,
        this_isREDs_q0,
        this_logVisitCounts_address0,
        this_logVisitCounts_ce0,
        this_logVisitCounts_we0,
        this_logVisitCounts_d0,
        this_logVisitCounts_q0,
        this_nextFree_read,
        this_rng_read,
        gameState_legalActionMap,
        gameState_hexGame_isPlayer1Turn_s,
        gameState_hexGame_lastMove_s,
        gameState_hexGame_player1_s,
        gameState_hexGame_player2_s,
        ap_return_0,
        ap_return_1
);

parameter    ap_ST_fsm_state1 = 28'd1;
parameter    ap_ST_fsm_state2 = 28'd2;
parameter    ap_ST_fsm_state3 = 28'd4;
parameter    ap_ST_fsm_state4 = 28'd8;
parameter    ap_ST_fsm_state5 = 28'd16;
parameter    ap_ST_fsm_state6 = 28'd32;
parameter    ap_ST_fsm_state7 = 28'd64;
parameter    ap_ST_fsm_state8 = 28'd128;
parameter    ap_ST_fsm_state9 = 28'd256;
parameter    ap_ST_fsm_state10 = 28'd512;
parameter    ap_ST_fsm_state11 = 28'd1024;
parameter    ap_ST_fsm_state12 = 28'd2048;
parameter    ap_ST_fsm_state13 = 28'd4096;
parameter    ap_ST_fsm_state14 = 28'd8192;
parameter    ap_ST_fsm_state15 = 28'd16384;
parameter    ap_ST_fsm_state16 = 28'd32768;
parameter    ap_ST_fsm_state17 = 28'd65536;
parameter    ap_ST_fsm_state18 = 28'd131072;
parameter    ap_ST_fsm_state19 = 28'd262144;
parameter    ap_ST_fsm_state20 = 28'd524288;
parameter    ap_ST_fsm_state21 = 28'd1048576;
parameter    ap_ST_fsm_state22 = 28'd2097152;
parameter    ap_ST_fsm_state23 = 28'd4194304;
parameter    ap_ST_fsm_state24 = 28'd8388608;
parameter    ap_ST_fsm_state25 = 28'd16777216;
parameter    ap_ST_fsm_state26 = 28'd33554432;
parameter    ap_ST_fsm_state27 = 28'd67108864;
parameter    ap_ST_fsm_state28 = 28'd134217728;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [12:0] this_visitCounts_address0;
output   this_visitCounts_ce0;
output   this_visitCounts_we0;
output  [31:0] this_visitCounts_d0;
input  [31:0] this_visitCounts_q0;
output  [12:0] this_meanQ_address0;
output   this_meanQ_ce0;
output   this_meanQ_we0;
output  [19:0] this_meanQ_d0;
input  [19:0] this_meanQ_q0;
output  [12:0] this_parents_address0;
output   this_parents_ce0;
output   this_parents_we0;
output  [31:0] this_parents_d0;
input  [31:0] this_parents_q0;
output  [12:0] this_firstChilds_address0;
output   this_firstChilds_ce0;
output   this_firstChilds_we0;
output  [31:0] this_firstChilds_d0;
input  [31:0] this_firstChilds_q0;
output  [12:0] this_numChildren_address0;
output   this_numChildren_ce0;
output   this_numChildren_we0;
output  [31:0] this_numChildren_d0;
input  [31:0] this_numChildren_q0;
output  [12:0] this_nextSiblings_address0;
output   this_nextSiblings_ce0;
output   this_nextSiblings_we0;
output  [31:0] this_nextSiblings_d0;
input  [31:0] this_nextSiblings_q0;
output  [12:0] this_numLegalActions_address0;
output   this_numLegalActions_ce0;
output   this_numLegalActions_we0;
output  [31:0] this_numLegalActions_d0;
input  [31:0] this_numLegalActions_q0;
output  [12:0] this_terminals_address0;
output   this_terminals_ce0;
output   this_terminals_we0;
output  [0:0] this_terminals_d0;
input  [0:0] this_terminals_q0;
output  [12:0] this_childActions_address0;
output   this_childActions_ce0;
output   this_childActions_we0;
output  [5:0] this_childActions_d0;
input  [5:0] this_childActions_q0;
output  [12:0] this_triedMask_address0;
output   this_triedMask_ce0;
output   this_triedMask_we0;
output  [48:0] this_triedMask_d0;
input  [48:0] this_triedMask_q0;
output  [12:0] this_isREDs_address0;
output   this_isREDs_ce0;
output   this_isREDs_we0;
output  [0:0] this_isREDs_d0;
input  [0:0] this_isREDs_q0;
output  [12:0] this_logVisitCounts_address0;
output   this_logVisitCounts_ce0;
output   this_logVisitCounts_we0;
output  [31:0] this_logVisitCounts_d0;
input  [31:0] this_logVisitCounts_q0;
input  [31:0] this_nextFree_read;
input  [63:0] this_rng_read;
input  [48:0] gameState_legalActionMap;
input  [0:0] gameState_hexGame_isPlayer1Turn_s;
input  [31:0] gameState_hexGame_lastMove_s;
input  [48:0] gameState_hexGame_player1_s;
input  [48:0] gameState_hexGame_player2_s;
output  [31:0] ap_return_0;
output  [63:0] ap_return_1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[12:0] this_visitCounts_address0;
reg this_visitCounts_ce0;
reg this_visitCounts_we0;
reg[31:0] this_visitCounts_d0;
reg[12:0] this_meanQ_address0;
reg this_meanQ_ce0;
reg this_meanQ_we0;
reg[19:0] this_meanQ_d0;
reg[12:0] this_parents_address0;
reg this_parents_ce0;
reg[12:0] this_nextSiblings_address0;
reg this_nextSiblings_ce0;
reg[12:0] this_isREDs_address0;
reg this_isREDs_ce0;
reg[12:0] this_logVisitCounts_address0;
reg this_logVisitCounts_ce0;
reg this_logVisitCounts_we0;
reg[31:0] ap_return_0;
reg[63:0] ap_return_1;

(* fsm_encoding = "none" *) reg   [27:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [63:0] reg_829;
wire    ap_CS_fsm_state20;
wire    grp_rollout_fu_751_ap_done;
wire    ap_CS_fsm_state21;
wire    ap_CS_fsm_state22;
reg   [31:0] node_5_reg_1772;
wire    ap_CS_fsm_state2;
wire   [63:0] zext_ln127_fu_862_p1;
reg   [63:0] zext_ln127_reg_1779;
reg   [12:0] this_numChildren_addr_reg_1794;
reg   [48:0] gameState_legalActionMap_4_reg_1799;
wire    ap_CS_fsm_state3;
reg   [48:0] gameState_hexGame_player2_4_reg_1806;
reg   [48:0] gameState_hexGame_player1_4_reg_1813;
reg   [31:0] gameState_hexGame_lastMove_4_reg_1820;
reg   [31:0] this_numLegalActions_load_reg_1826;
reg   [31:0] this_numChildren_load_reg_1831;
wire   [0:0] icmp_ln127_fu_880_p2;
reg   [0:0] icmp_ln127_reg_1836;
wire   [0:0] icmp_ln54_fu_886_p2;
reg   [0:0] icmp_ln54_reg_1845;
reg   [12:0] this_triedMask_addr_reg_1849;
wire    ap_CS_fsm_state4;
wire   [0:0] grp_fu_814_p2;
reg   [0:0] gameState_hexGame_isPlayer1Turn_s_78_reg_1867;
reg   [31:0] bestChildNode_reg_1872;
wire    ap_CS_fsm_state5;
reg   [31:0] logVisitCount_reg_1877;
wire    ap_CS_fsm_state7;
reg   [48:0] this_triedMask_load_reg_1887;
wire    ap_CS_fsm_state9;
wire   [48:0] untried_fu_982_p2;
reg   [48:0] untried_reg_1892;
wire   [0:0] icmp_ln71_fu_988_p2;
reg   [0:0] icmp_ln71_reg_1897;
wire   [0:0] grp_forward_Pipeline_VITIS_LOOP_73_1_fu_729_ap_return;
reg   [0:0] targetBlock_reg_1901;
wire    ap_CS_fsm_state10;
wire   [63:0] zext_ln96_fu_998_p1;
reg   [63:0] zext_ln96_reg_1905;
wire    ap_CS_fsm_state11;
reg   [12:0] this_firstChilds_addr_2_reg_1913;
wire   [0:0] tmp_fu_1049_p3;
reg   [0:0] tmp_reg_1923;
wire    ap_CS_fsm_state13;
wire   [63:0] zext_ln161_fu_1057_p1;
reg   [63:0] zext_ln161_reg_1927;
wire   [31:0] zext_ln12_fu_1062_p1;
reg   [31:0] zext_ln12_reg_1937;
wire    ap_CS_fsm_state14;
reg   [0:0] gameState_hexGame_isPlayer1Turn_4_reg_1942;
wire   [48:0] gameState_hexGame_player1_5_fu_1084_p2;
reg   [48:0] gameState_hexGame_player1_5_reg_1947;
wire   [48:0] gameState_hexGame_player2_5_fu_1098_p2;
reg   [48:0] gameState_hexGame_player2_5_reg_1954;
wire   [48:0] fill_6_fu_1104_p2;
reg   [48:0] fill_6_reg_1961;
wire   [48:0] fill_5_fu_1111_p2;
reg   [48:0] fill_5_reg_1966;
wire   [48:0] gameState_legalActionMap_5_fu_1342_p2;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state18;
wire   [0:0] this_terminals_q0_local;
reg   [0:0] this_terminals_load_1_reg_1987;
wire    ap_CS_fsm_state19;
wire   [0:0] tmp_239_fu_1353_p3;
reg   [0:0] tmp_239_reg_1991;
wire   [48:0] connected_fu_1371_p2;
reg   [48:0] connected_reg_1995;
wire   [48:0] connected_8_fu_1378_p2;
reg   [48:0] connected_8_reg_2000;
reg   [19:0] reward_reg_2005;
reg   [19:0] ref_tmp57_assign_5_reg_2010;
wire   [19:0] grp_rollout_fu_751_ap_return_0;
wire   [63:0] grp_rollout_fu_751_ap_return_1;
reg   [19:0] call_ret_reg_2015_0;
wire    ap_CS_fsm_state23;
wire   [31:0] select_ln178_fu_1409_p3;
reg   [31:0] select_ln178_reg_2025;
wire   [19:0] select_ln35_fu_1636_p3;
wire    ap_CS_fsm_state27;
wire    grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714_ap_start;
wire    grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714_ap_done;
wire    grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714_ap_idle;
wire    grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714_ap_ready;
wire   [12:0] grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714_this_meanQ_address0;
wire    grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714_this_meanQ_ce0;
wire   [12:0] grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714_this_visitCounts_address0;
wire    grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714_this_visitCounts_ce0;
wire   [12:0] grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714_this_nextSiblings_address0;
wire    grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714_this_nextSiblings_ce0;
wire   [31:0] grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714_bestChildNode_out;
wire    grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714_bestChildNode_out_ap_vld;
wire    grp_forward_Pipeline_VITIS_LOOP_73_1_fu_729_ap_start;
wire    grp_forward_Pipeline_VITIS_LOOP_73_1_fu_729_ap_done;
wire    grp_forward_Pipeline_VITIS_LOOP_73_1_fu_729_ap_idle;
wire    grp_forward_Pipeline_VITIS_LOOP_73_1_fu_729_ap_ready;
wire   [5:0] grp_forward_Pipeline_VITIS_LOOP_73_1_fu_729_action_out;
wire    grp_forward_Pipeline_VITIS_LOOP_73_1_fu_729_action_out_ap_vld;
wire    grp_forward_Pipeline_VITIS_LOOP_114_14_fu_735_ap_start;
wire    grp_forward_Pipeline_VITIS_LOOP_114_14_fu_735_ap_done;
wire    grp_forward_Pipeline_VITIS_LOOP_114_14_fu_735_ap_idle;
wire    grp_forward_Pipeline_VITIS_LOOP_114_14_fu_735_ap_ready;
wire   [42:0] grp_forward_Pipeline_VITIS_LOOP_114_14_fu_735_prev_8_out;
wire    grp_forward_Pipeline_VITIS_LOOP_114_14_fu_735_prev_8_out_ap_vld;
wire   [0:0] grp_forward_Pipeline_VITIS_LOOP_114_14_fu_735_p_out;
wire    grp_forward_Pipeline_VITIS_LOOP_114_14_fu_735_p_out_ap_vld;
wire   [0:0] grp_forward_Pipeline_VITIS_LOOP_114_14_fu_735_p_out1;
wire    grp_forward_Pipeline_VITIS_LOOP_114_14_fu_735_p_out1_ap_vld;
wire    grp_forward_Pipeline_VITIS_LOOP_114_1_fu_744_ap_start;
wire    grp_forward_Pipeline_VITIS_LOOP_114_1_fu_744_ap_done;
wire    grp_forward_Pipeline_VITIS_LOOP_114_1_fu_744_ap_idle;
wire    grp_forward_Pipeline_VITIS_LOOP_114_1_fu_744_ap_ready;
wire   [48:0] grp_forward_Pipeline_VITIS_LOOP_114_1_fu_744_prev_out;
wire    grp_forward_Pipeline_VITIS_LOOP_114_1_fu_744_prev_out_ap_vld;
wire    grp_rollout_fu_751_ap_start;
wire    grp_rollout_fu_751_ap_idle;
wire    grp_rollout_fu_751_ap_ready;
reg   [63:0] grp_rollout_fu_751_this_rng_read;
wire    grp_forward_Pipeline_VITIS_LOOP_114_15_fu_766_ap_start;
wire    grp_forward_Pipeline_VITIS_LOOP_114_15_fu_766_ap_done;
wire    grp_forward_Pipeline_VITIS_LOOP_114_15_fu_766_ap_idle;
wire    grp_forward_Pipeline_VITIS_LOOP_114_15_fu_766_ap_ready;
wire   [48:0] grp_forward_Pipeline_VITIS_LOOP_114_15_fu_766_prev_9_out;
wire    grp_forward_Pipeline_VITIS_LOOP_114_15_fu_766_prev_9_out_ap_vld;
wire    grp_forward_Pipeline_VITIS_LOOP_114_16_fu_774_ap_start;
wire    grp_forward_Pipeline_VITIS_LOOP_114_16_fu_774_ap_done;
wire    grp_forward_Pipeline_VITIS_LOOP_114_16_fu_774_ap_idle;
wire    grp_forward_Pipeline_VITIS_LOOP_114_16_fu_774_ap_ready;
wire   [42:0] grp_forward_Pipeline_VITIS_LOOP_114_16_fu_774_prev_10_out;
wire    grp_forward_Pipeline_VITIS_LOOP_114_16_fu_774_prev_10_out_ap_vld;
wire   [0:0] grp_forward_Pipeline_VITIS_LOOP_114_16_fu_774_p_out;
wire    grp_forward_Pipeline_VITIS_LOOP_114_16_fu_774_p_out_ap_vld;
wire   [0:0] grp_forward_Pipeline_VITIS_LOOP_114_16_fu_774_p_out1;
wire    grp_forward_Pipeline_VITIS_LOOP_114_16_fu_774_p_out1_ap_vld;
wire    grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_ap_start;
wire    grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_ap_done;
wire    grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_ap_idle;
wire    grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_ap_ready;
wire   [12:0] grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_visitCounts_address0;
wire    grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_visitCounts_ce0;
wire    grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_visitCounts_we0;
wire   [31:0] grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_visitCounts_d0;
wire   [12:0] grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_meanQ_address0;
wire    grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_meanQ_ce0;
wire    grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_meanQ_we0;
wire   [19:0] grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_meanQ_d0;
wire   [12:0] grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_logVisitCounts_address0;
wire    grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_logVisitCounts_ce0;
wire    grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_logVisitCounts_we0;
wire   [31:0] grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_logVisitCounts_d0;
wire   [12:0] grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_parents_address0;
wire    grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_parents_ce0;
wire   [12:0] grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_isREDs_address0;
wire    grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_isREDs_ce0;
reg   [0:0] gameState_hexGame_isPlayer1Turn_5_reg_501;
wire    ap_CS_fsm_state8;
reg   [0:0] ap_phi_mux_write_flag_0_phi_fu_515_p8;
reg   [0:0] write_flag_0_reg_511;
wire   [31:0] add_ln119_fu_1043_p2;
reg   [31:0] ap_phi_mux_this_nextFree_02_phi_fu_534_p8;
reg   [31:0] this_nextFree_02_reg_530;
reg   [31:0] ap_phi_mux_child_phi_fu_552_p8;
reg   [31:0] child_reg_548;
reg   [31:0] gameState_hexGame_lastMove_3_reg_566;
reg   [48:0] gameState_hexGame_player1_6_reg_578;
reg   [48:0] gameState_hexGame_player2_6_reg_590;
reg   [0:0] gameState_hexGame_isPlayer1Turn_3_reg_602;
reg   [48:0] gameState_legalActionMap_3_reg_616;
reg   [31:0] node_4_reg_628;
reg   [0:0] write_flag_1_reg_641;
reg   [31:0] this_nextFree_1_reg_657;
reg   [19:0] reward_1_reg_673;
wire    ap_CS_fsm_state25;
wire   [0:0] and_ln80_3_fu_1630_p2;
wire   [0:0] and_ln77_2_fu_1445_p2;
wire   [19:0] add_ln171_fu_1402_p2;
reg    ap_block_state23_on_subcall_done;
reg   [2:0] visitCount_reg_687;
reg   [63:0] this_rng_0_reg_703;
reg    grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714_ap_start_reg;
wire    ap_CS_fsm_state6;
reg    grp_forward_Pipeline_VITIS_LOOP_73_1_fu_729_ap_start_reg;
reg   [5:0] action_loc_fu_200;
reg    grp_forward_Pipeline_VITIS_LOOP_114_14_fu_735_ap_start_reg;
wire    ap_CS_fsm_state15;
reg   [42:0] prev_8_loc_fu_192;
reg   [0:0] p_loc_fu_188;
reg   [0:0] p_loc43_fu_184;
reg    grp_forward_Pipeline_VITIS_LOOP_114_1_fu_744_ap_start_reg;
wire    ap_CS_fsm_state17;
reg   [48:0] prev_loc_fu_196;
reg    grp_rollout_fu_751_ap_start_reg;
reg    grp_forward_Pipeline_VITIS_LOOP_114_15_fu_766_ap_start_reg;
wire    ap_CS_fsm_state24;
reg   [48:0] prev_9_loc_fu_180;
reg    grp_forward_Pipeline_VITIS_LOOP_114_16_fu_774_ap_start_reg;
wire    ap_CS_fsm_state26;
reg   [42:0] prev_10_loc_fu_176;
reg   [0:0] p_loc47_fu_172;
reg   [0:0] p_loc48_fu_168;
reg    grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_ap_start_reg;
wire    ap_CS_fsm_state28;
wire    this_visitCounts_we0_out;
wire    this_meanQ_we0_out;
wire   [63:0] zext_ln152_fu_894_p1;
wire    ap_CS_fsm_state12;
wire   [0:0] and_ln77_fu_1332_p2;
wire   [0:0] and_ln80_fu_1297_p2;
wire   [63:0] zext_ln167_fu_1348_p1;
reg   [31:0] parent_fu_148;
reg   [48:0] boardState_legalActionMap_fu_152;
wire   [48:0] gameState_legalActionMap_79_fu_950_p2;
reg   [48:0] boardState_hexGame_player2_s_fu_156;
wire   [48:0] gameState_hexGame_player2_s_77_fu_939_p2;
reg   [48:0] boardState_hexGame_player1_s_fu_160;
wire   [48:0] gameState_hexGame_player1_s_76_fu_926_p2;
reg   [31:0] boardState_hexGame_lastMove_s_fu_164;
wire   [31:0] zext_ln152_1_fu_904_p1;
reg    this_numLegalActions_ce0_local;
reg   [12:0] this_numLegalActions_address0_local;
reg    this_numLegalActions_we0_local;
wire   [31:0] numLegalActionsHere_fu_1030_p2;
reg    this_numChildren_ce0_local;
reg   [12:0] this_numChildren_address0_local;
reg    this_numChildren_we0_local;
reg   [31:0] this_numChildren_d0_local;
wire   [31:0] add_ln101_fu_1008_p2;
reg    this_terminals_ce0_local;
reg   [12:0] this_terminals_address0_local;
reg    this_terminals_we0_local;
reg   [0:0] this_terminals_d0_local;
reg    this_triedMask_ce0_local;
reg   [12:0] this_triedMask_address0_local;
reg    this_triedMask_we0_local;
reg   [48:0] this_triedMask_d0_local;
wire   [48:0] or_ln102_fu_1024_p2;
reg    this_firstChilds_ce0_local;
reg   [12:0] this_firstChilds_address0_local;
reg    this_firstChilds_we0_local;
reg   [31:0] this_firstChilds_d0_local;
reg    this_logVisitCounts_ce0_local;
reg    this_childActions_ce0_local;
reg   [12:0] this_childActions_address0_local;
reg    this_childActions_we0_local;
reg    this_parents_we0_local;
reg    this_parents_ce0_local;
reg    this_visitCounts_we0_local;
reg    this_visitCounts_ce0_local;
reg    this_meanQ_we0_local;
reg    this_meanQ_ce0_local;
reg    this_isREDs_ce0_local;
reg   [12:0] this_isREDs_address0_local;
reg    this_isREDs_we0_local;
wire   [0:0] xor_ln118_fu_1036_p2;
reg    this_nextSiblings_we0_local;
reg    this_nextSiblings_ce0_local;
wire   [48:0] zext_ln56_fu_908_p1;
wire   [48:0] bit_fu_912_p2;
wire   [48:0] select_ln58_fu_918_p3;
wire   [48:0] select_ln58_2_fu_931_p3;
wire   [48:0] or_ln14_fu_944_p2;
wire   [48:0] xor_ln70_fu_976_p2;
wire   [48:0] zext_ln102_fu_1014_p1;
wire   [48:0] shl_ln102_fu_1018_p2;
wire   [48:0] zext_ln56_2_fu_1066_p1;
wire   [48:0] bit_2_fu_1070_p2;
wire   [48:0] select_ln58_3_fu_1076_p3;
wire   [48:0] select_ln58_4_fu_1090_p3;
wire   [48:0] prev_8_reload_cast52_fu_1121_p1;
wire   [0:0] tmp_228_fu_1131_p3;
wire   [0:0] tmp_229_fu_1139_p3;
wire   [0:0] tmp_230_fu_1147_p3;
wire   [0:0] tmp_231_fu_1155_p3;
wire   [0:0] tmp_232_fu_1163_p3;
wire   [0:0] tmp_233_fu_1171_p3;
wire   [0:0] trunc_ln80_fu_1179_p1;
wire   [42:0] and_ln_fu_1183_p14;
wire   [0:0] tmp_234_fu_1219_p3;
wire   [0:0] tmp_235_fu_1227_p3;
wire   [0:0] tmp_236_fu_1235_p3;
wire   [0:0] tmp_237_fu_1243_p3;
wire   [0:0] tmp_238_fu_1251_p3;
wire   [48:0] and_ln80_6_fu_1259_p15;
wire   [0:0] icmp_ln80_fu_1213_p2;
wire   [0:0] icmp_ln80_4_fu_1291_p2;
wire   [6:0] trunc_ln112_fu_1306_p1;
wire   [6:0] tmp_227_fu_1316_p4;
wire   [0:0] icmp_ln77_fu_1310_p2;
wire   [0:0] icmp_ln77_4_fu_1326_p2;
wire   [48:0] or_ln14_1_fu_1338_p2;
wire   [48:0] zext_ln73_fu_1361_p1;
wire   [48:0] seed_1_fu_1365_p2;
wire   [19:0] add_ln171_2_fu_1396_p2;
wire   [19:0] add_ln171_1_fu_1392_p2;
wire   [6:0] trunc_ln112_2_fu_1419_p1;
wire   [6:0] tmp_251_fu_1429_p4;
wire   [0:0] icmp_ln77_5_fu_1423_p2;
wire   [0:0] icmp_ln77_6_fu_1439_p2;
wire   [48:0] prev_10_reload_cast53_fu_1454_p1;
wire   [0:0] tmp_240_fu_1464_p3;
wire   [0:0] tmp_241_fu_1472_p3;
wire   [0:0] tmp_242_fu_1480_p3;
wire   [0:0] tmp_243_fu_1488_p3;
wire   [0:0] tmp_244_fu_1496_p3;
wire   [0:0] tmp_245_fu_1504_p3;
wire   [0:0] trunc_ln80_2_fu_1512_p1;
wire   [42:0] and_ln80_8_fu_1516_p14;
wire   [0:0] tmp_246_fu_1552_p3;
wire   [0:0] tmp_247_fu_1560_p3;
wire   [0:0] tmp_248_fu_1568_p3;
wire   [0:0] tmp_249_fu_1576_p3;
wire   [0:0] tmp_250_fu_1584_p3;
wire   [48:0] and_ln80_9_fu_1592_p15;
wire   [0:0] icmp_ln80_5_fu_1546_p2;
wire   [0:0] icmp_ln80_6_fu_1624_p2;
reg   [31:0] ap_return_0_preg;
reg   [63:0] ap_return_1_preg;
reg   [27:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
reg    ap_ST_fsm_state20_blk;
reg    ap_ST_fsm_state21_blk;
reg    ap_ST_fsm_state22_blk;
reg    ap_ST_fsm_state23_blk;
reg    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
reg    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
reg    ap_ST_fsm_state28_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 28'd1;
#0 grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714_ap_start_reg = 1'b0;
#0 grp_forward_Pipeline_VITIS_LOOP_73_1_fu_729_ap_start_reg = 1'b0;
#0 grp_forward_Pipeline_VITIS_LOOP_114_14_fu_735_ap_start_reg = 1'b0;
#0 grp_forward_Pipeline_VITIS_LOOP_114_1_fu_744_ap_start_reg = 1'b0;
#0 grp_rollout_fu_751_ap_start_reg = 1'b0;
#0 grp_forward_Pipeline_VITIS_LOOP_114_15_fu_766_ap_start_reg = 1'b0;
#0 grp_forward_Pipeline_VITIS_LOOP_114_16_fu_774_ap_start_reg = 1'b0;
#0 grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_ap_start_reg = 1'b0;
#0 parent_fu_148 = 32'd0;
#0 boardState_legalActionMap_fu_152 = 49'd0;
#0 boardState_hexGame_player2_s_fu_156 = 49'd0;
#0 boardState_hexGame_player1_s_fu_160 = 49'd0;
#0 boardState_hexGame_lastMove_s_fu_164 = 32'd0;
#0 ap_return_0_preg = 32'd0;
#0 ap_return_1_preg = 64'd0;
end

dut_forward_Pipeline_VITIS_LOOP_140_2 grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714_ap_start),
    .ap_done(grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714_ap_done),
    .ap_idle(grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714_ap_idle),
    .ap_ready(grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714_ap_ready),
    .bestChildNode_7(bestChildNode_reg_1872),
    .this_meanQ_address0(grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714_this_meanQ_address0),
    .this_meanQ_ce0(grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714_this_meanQ_ce0),
    .this_meanQ_q0(this_meanQ_q0),
    .this_visitCounts_address0(grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714_this_visitCounts_address0),
    .this_visitCounts_ce0(grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714_this_visitCounts_ce0),
    .this_visitCounts_q0(this_visitCounts_q0),
    .logVisitCount(logVisitCount_reg_1877),
    .this_nextSiblings_address0(grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714_this_nextSiblings_address0),
    .this_nextSiblings_ce0(grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714_this_nextSiblings_ce0),
    .this_nextSiblings_q0(this_nextSiblings_q0),
    .bestChildNode_out(grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714_bestChildNode_out),
    .bestChildNode_out_ap_vld(grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714_bestChildNode_out_ap_vld)
);

dut_forward_Pipeline_VITIS_LOOP_73_1 grp_forward_Pipeline_VITIS_LOOP_73_1_fu_729(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_forward_Pipeline_VITIS_LOOP_73_1_fu_729_ap_start),
    .ap_done(grp_forward_Pipeline_VITIS_LOOP_73_1_fu_729_ap_done),
    .ap_idle(grp_forward_Pipeline_VITIS_LOOP_73_1_fu_729_ap_idle),
    .ap_ready(grp_forward_Pipeline_VITIS_LOOP_73_1_fu_729_ap_ready),
    .untried(untried_reg_1892),
    .action_out(grp_forward_Pipeline_VITIS_LOOP_73_1_fu_729_action_out),
    .action_out_ap_vld(grp_forward_Pipeline_VITIS_LOOP_73_1_fu_729_action_out_ap_vld),
    .ap_return(grp_forward_Pipeline_VITIS_LOOP_73_1_fu_729_ap_return)
);

dut_forward_Pipeline_VITIS_LOOP_114_14 grp_forward_Pipeline_VITIS_LOOP_114_14_fu_735(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_forward_Pipeline_VITIS_LOOP_114_14_fu_735_ap_start),
    .ap_done(grp_forward_Pipeline_VITIS_LOOP_114_14_fu_735_ap_done),
    .ap_idle(grp_forward_Pipeline_VITIS_LOOP_114_14_fu_735_ap_idle),
    .ap_ready(grp_forward_Pipeline_VITIS_LOOP_114_14_fu_735_ap_ready),
    .fill_10(fill_6_reg_1961),
    .gameState_hexGame_player2_7(gameState_hexGame_player2_5_reg_1954),
    .prev_8_out(grp_forward_Pipeline_VITIS_LOOP_114_14_fu_735_prev_8_out),
    .prev_8_out_ap_vld(grp_forward_Pipeline_VITIS_LOOP_114_14_fu_735_prev_8_out_ap_vld),
    .p_out(grp_forward_Pipeline_VITIS_LOOP_114_14_fu_735_p_out),
    .p_out_ap_vld(grp_forward_Pipeline_VITIS_LOOP_114_14_fu_735_p_out_ap_vld),
    .p_out1(grp_forward_Pipeline_VITIS_LOOP_114_14_fu_735_p_out1),
    .p_out1_ap_vld(grp_forward_Pipeline_VITIS_LOOP_114_14_fu_735_p_out1_ap_vld)
);

dut_forward_Pipeline_VITIS_LOOP_114_1 grp_forward_Pipeline_VITIS_LOOP_114_1_fu_744(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_forward_Pipeline_VITIS_LOOP_114_1_fu_744_ap_start),
    .ap_done(grp_forward_Pipeline_VITIS_LOOP_114_1_fu_744_ap_done),
    .ap_idle(grp_forward_Pipeline_VITIS_LOOP_114_1_fu_744_ap_idle),
    .ap_ready(grp_forward_Pipeline_VITIS_LOOP_114_1_fu_744_ap_ready),
    .fill_9(fill_5_reg_1966),
    .gameState_hexGame_player1_7(gameState_hexGame_player1_5_reg_1947),
    .prev_out(grp_forward_Pipeline_VITIS_LOOP_114_1_fu_744_prev_out),
    .prev_out_ap_vld(grp_forward_Pipeline_VITIS_LOOP_114_1_fu_744_prev_out_ap_vld)
);

dut_rollout grp_rollout_fu_751(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_rollout_fu_751_ap_start),
    .ap_done(grp_rollout_fu_751_ap_done),
    .ap_idle(grp_rollout_fu_751_ap_idle),
    .ap_ready(grp_rollout_fu_751_ap_ready),
    .this_rng_read(grp_rollout_fu_751_this_rng_read),
    .gameState_legalActionMap(gameState_legalActionMap_3_reg_616),
    .gameState_hexGame_isPlayer1Turn_s(gameState_hexGame_isPlayer1Turn_3_reg_602),
    .gameState_hexGame_lastMove_s(gameState_hexGame_lastMove_3_reg_566),
    .gameState_hexGame_player1_s(gameState_hexGame_player1_6_reg_578),
    .gameState_hexGame_player2_s(gameState_hexGame_player2_6_reg_590),
    .ap_return_0(grp_rollout_fu_751_ap_return_0),
    .ap_return_1(grp_rollout_fu_751_ap_return_1)
);

dut_forward_Pipeline_VITIS_LOOP_114_15 grp_forward_Pipeline_VITIS_LOOP_114_15_fu_766(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_forward_Pipeline_VITIS_LOOP_114_15_fu_766_ap_start),
    .ap_done(grp_forward_Pipeline_VITIS_LOOP_114_15_fu_766_ap_done),
    .ap_idle(grp_forward_Pipeline_VITIS_LOOP_114_15_fu_766_ap_idle),
    .ap_ready(grp_forward_Pipeline_VITIS_LOOP_114_15_fu_766_ap_ready),
    .connected(connected_reg_1995),
    .gameState_hexGame_player1_8(gameState_hexGame_player1_6_reg_578),
    .prev_9_out(grp_forward_Pipeline_VITIS_LOOP_114_15_fu_766_prev_9_out),
    .prev_9_out_ap_vld(grp_forward_Pipeline_VITIS_LOOP_114_15_fu_766_prev_9_out_ap_vld)
);

dut_forward_Pipeline_VITIS_LOOP_114_16 grp_forward_Pipeline_VITIS_LOOP_114_16_fu_774(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_forward_Pipeline_VITIS_LOOP_114_16_fu_774_ap_start),
    .ap_done(grp_forward_Pipeline_VITIS_LOOP_114_16_fu_774_ap_done),
    .ap_idle(grp_forward_Pipeline_VITIS_LOOP_114_16_fu_774_ap_idle),
    .ap_ready(grp_forward_Pipeline_VITIS_LOOP_114_16_fu_774_ap_ready),
    .connected_12(connected_8_reg_2000),
    .gameState_hexGame_player2_8(gameState_hexGame_player2_6_reg_590),
    .prev_10_out(grp_forward_Pipeline_VITIS_LOOP_114_16_fu_774_prev_10_out),
    .prev_10_out_ap_vld(grp_forward_Pipeline_VITIS_LOOP_114_16_fu_774_prev_10_out_ap_vld),
    .p_out(grp_forward_Pipeline_VITIS_LOOP_114_16_fu_774_p_out),
    .p_out_ap_vld(grp_forward_Pipeline_VITIS_LOOP_114_16_fu_774_p_out_ap_vld),
    .p_out1(grp_forward_Pipeline_VITIS_LOOP_114_16_fu_774_p_out1),
    .p_out1_ap_vld(grp_forward_Pipeline_VITIS_LOOP_114_16_fu_774_p_out1_ap_vld)
);

dut_forward_Pipeline_VITIS_LOOP_259_1 grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_ap_start),
    .ap_done(grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_ap_done),
    .ap_idle(grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_ap_idle),
    .ap_ready(grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_ap_ready),
    .node_2(node_4_reg_628),
    .reward_2(reward_1_reg_673),
    .this_visitCounts_address0(grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_visitCounts_address0),
    .this_visitCounts_ce0(grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_visitCounts_ce0),
    .this_visitCounts_we0(grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_visitCounts_we0),
    .this_visitCounts_d0(grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_visitCounts_d0),
    .this_visitCounts_q0(this_visitCounts_q0),
    .zext_ln125(visitCount_reg_687),
    .this_meanQ_address0(grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_meanQ_address0),
    .this_meanQ_ce0(grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_meanQ_ce0),
    .this_meanQ_we0(grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_meanQ_we0),
    .this_meanQ_d0(grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_meanQ_d0),
    .this_meanQ_q0(this_meanQ_q0),
    .visitCount_cast3(visitCount_reg_687),
    .this_logVisitCounts_address0(grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_logVisitCounts_address0),
    .this_logVisitCounts_ce0(grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_logVisitCounts_ce0),
    .this_logVisitCounts_we0(grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_logVisitCounts_we0),
    .this_logVisitCounts_d0(grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_logVisitCounts_d0),
    .this_parents_address0(grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_parents_address0),
    .this_parents_ce0(grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_parents_ce0),
    .this_parents_q0(this_parents_q0),
    .this_isREDs_address0(grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_isREDs_address0),
    .this_isREDs_ce0(grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_isREDs_ce0),
    .this_isREDs_q0(this_isREDs_q0),
    .conv7_i_i159_i(visitCount_reg_687)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 32'd0;
    end else begin
        if (((grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state28))) begin
            ap_return_0_preg <= select_ln178_reg_2025;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 64'd0;
    end else begin
        if (((grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state28))) begin
            ap_return_1_preg <= this_rng_0_reg_703;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_forward_Pipeline_VITIS_LOOP_114_14_fu_735_ap_start_reg <= 1'b0;
    end else begin
        if (((gameState_hexGame_isPlayer1Turn_5_reg_501 == 1'd0) & (1'b1 == ap_CS_fsm_state14))) begin
            grp_forward_Pipeline_VITIS_LOOP_114_14_fu_735_ap_start_reg <= 1'b1;
        end else if ((grp_forward_Pipeline_VITIS_LOOP_114_14_fu_735_ap_ready == 1'b1)) begin
            grp_forward_Pipeline_VITIS_LOOP_114_14_fu_735_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_forward_Pipeline_VITIS_LOOP_114_15_fu_766_ap_start_reg <= 1'b0;
    end else begin
        if (((gameState_hexGame_isPlayer1Turn_3_reg_602 == 1'd0) & (tmp_239_fu_1353_p3 == 1'd0) & (this_terminals_q0_local == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
            grp_forward_Pipeline_VITIS_LOOP_114_15_fu_766_ap_start_reg <= 1'b1;
        end else if ((grp_forward_Pipeline_VITIS_LOOP_114_15_fu_766_ap_ready == 1'b1)) begin
            grp_forward_Pipeline_VITIS_LOOP_114_15_fu_766_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_forward_Pipeline_VITIS_LOOP_114_16_fu_774_ap_start_reg <= 1'b0;
    end else begin
        if (((gameState_hexGame_isPlayer1Turn_3_reg_602 == 1'd1) & (tmp_239_fu_1353_p3 == 1'd0) & (this_terminals_q0_local == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
            grp_forward_Pipeline_VITIS_LOOP_114_16_fu_774_ap_start_reg <= 1'b1;
        end else if ((grp_forward_Pipeline_VITIS_LOOP_114_16_fu_774_ap_ready == 1'b1)) begin
            grp_forward_Pipeline_VITIS_LOOP_114_16_fu_774_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_forward_Pipeline_VITIS_LOOP_114_1_fu_744_ap_start_reg <= 1'b0;
    end else begin
        if (((gameState_hexGame_isPlayer1Turn_5_reg_501 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
            grp_forward_Pipeline_VITIS_LOOP_114_1_fu_744_ap_start_reg <= 1'b1;
        end else if ((grp_forward_Pipeline_VITIS_LOOP_114_1_fu_744_ap_ready == 1'b1)) begin
            grp_forward_Pipeline_VITIS_LOOP_114_1_fu_744_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714_ap_start_reg <= 1'b1;
        end else if ((grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714_ap_ready == 1'b1)) begin
            grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state23_on_subcall_done) & (1'b1 == ap_CS_fsm_state23))) begin
            grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_ap_start_reg <= 1'b1;
        end else if ((grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_ap_ready == 1'b1)) begin
            grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_forward_Pipeline_VITIS_LOOP_73_1_fu_729_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln71_fu_988_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
            grp_forward_Pipeline_VITIS_LOOP_73_1_fu_729_ap_start_reg <= 1'b1;
        end else if ((grp_forward_Pipeline_VITIS_LOOP_73_1_fu_729_ap_ready == 1'b1)) begin
            grp_forward_Pipeline_VITIS_LOOP_73_1_fu_729_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_rollout_fu_751_ap_start_reg <= 1'b0;
    end else begin
        if ((((this_terminals_q0_local == 1'd0) & (1'b1 == ap_CS_fsm_state19)) | ((1'b1 == ap_CS_fsm_state22) & (grp_rollout_fu_751_ap_done == 1'b1)) | ((1'b1 == ap_CS_fsm_state21) & (grp_rollout_fu_751_ap_done == 1'b1)) | ((1'b1 == ap_CS_fsm_state20) & (grp_rollout_fu_751_ap_done == 1'b1)))) begin
            grp_rollout_fu_751_ap_start_reg <= 1'b1;
        end else if ((grp_rollout_fu_751_ap_ready == 1'b1)) begin
            grp_rollout_fu_751_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        boardState_hexGame_lastMove_s_fu_164 <= gameState_hexGame_lastMove_s;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        boardState_hexGame_lastMove_s_fu_164 <= zext_ln152_1_fu_904_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        boardState_hexGame_player1_s_fu_160 <= gameState_hexGame_player1_s;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        boardState_hexGame_player1_s_fu_160 <= gameState_hexGame_player1_s_76_fu_926_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        boardState_hexGame_player2_s_fu_156 <= gameState_hexGame_player2_s;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        boardState_hexGame_player2_s_fu_156 <= gameState_hexGame_player2_s_77_fu_939_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        boardState_legalActionMap_fu_152 <= gameState_legalActionMap;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        boardState_legalActionMap_fu_152 <= gameState_legalActionMap_79_fu_950_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((targetBlock_reg_1901 == 1'd0) & (icmp_ln71_reg_1897 == 1'd0) & (icmp_ln54_reg_1845 == 1'd0) & (1'b1 == ap_CS_fsm_state13))) begin
        child_reg_548 <= this_nextFree_read;
    end else if ((((targetBlock_reg_1901 == 1'd1) & (1'b1 == ap_CS_fsm_state11)) | ((icmp_ln71_fu_988_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9)) | ((icmp_ln54_fu_886_p2 == 1'd1) & (icmp_ln127_fu_880_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        child_reg_548 <= 32'd4294967295;
    end
end

always @ (posedge ap_clk) begin
    if ((((this_terminals_q0_local == 1'd1) & (1'b1 == ap_CS_fsm_state4)) | ((tmp_fu_1049_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state13)))) begin
        gameState_hexGame_isPlayer1Turn_3_reg_602 <= gameState_hexGame_isPlayer1Turn_5_reg_501;
    end else if (((tmp_reg_1923 == 1'd0) & (icmp_ln127_reg_1836 == 1'd0) & (1'b1 == ap_CS_fsm_state16))) begin
        gameState_hexGame_isPlayer1Turn_3_reg_602 <= gameState_hexGame_isPlayer1Turn_4_reg_1942;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        gameState_hexGame_isPlayer1Turn_5_reg_501 <= gameState_hexGame_isPlayer1Turn_s_78_reg_1867;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        gameState_hexGame_isPlayer1Turn_5_reg_501 <= gameState_hexGame_isPlayer1Turn_s;
    end
end

always @ (posedge ap_clk) begin
    if ((((this_terminals_q0_local == 1'd1) & (1'b1 == ap_CS_fsm_state4)) | ((tmp_fu_1049_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state13)))) begin
        gameState_hexGame_lastMove_3_reg_566 <= gameState_hexGame_lastMove_4_reg_1820;
    end else if (((tmp_reg_1923 == 1'd0) & (icmp_ln127_reg_1836 == 1'd0) & (1'b1 == ap_CS_fsm_state16))) begin
        gameState_hexGame_lastMove_3_reg_566 <= zext_ln12_reg_1937;
    end
end

always @ (posedge ap_clk) begin
    if ((((this_terminals_q0_local == 1'd1) & (1'b1 == ap_CS_fsm_state4)) | ((tmp_fu_1049_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state13)))) begin
        gameState_hexGame_player1_6_reg_578 <= gameState_hexGame_player1_4_reg_1813;
    end else if (((tmp_reg_1923 == 1'd0) & (icmp_ln127_reg_1836 == 1'd0) & (1'b1 == ap_CS_fsm_state16))) begin
        gameState_hexGame_player1_6_reg_578 <= gameState_hexGame_player1_5_reg_1947;
    end
end

always @ (posedge ap_clk) begin
    if ((((this_terminals_q0_local == 1'd1) & (1'b1 == ap_CS_fsm_state4)) | ((tmp_fu_1049_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state13)))) begin
        gameState_hexGame_player2_6_reg_590 <= gameState_hexGame_player2_4_reg_1806;
    end else if (((tmp_reg_1923 == 1'd0) & (icmp_ln127_reg_1836 == 1'd0) & (1'b1 == ap_CS_fsm_state16))) begin
        gameState_hexGame_player2_6_reg_590 <= gameState_hexGame_player2_5_reg_1954;
    end
end

always @ (posedge ap_clk) begin
    if ((((this_terminals_q0_local == 1'd1) & (1'b1 == ap_CS_fsm_state4)) | ((tmp_fu_1049_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state13)))) begin
        gameState_legalActionMap_3_reg_616 <= gameState_legalActionMap_4_reg_1799;
    end else if (((tmp_reg_1923 == 1'd0) & (icmp_ln127_reg_1836 == 1'd0) & (1'b1 == ap_CS_fsm_state16))) begin
        gameState_legalActionMap_3_reg_616 <= gameState_legalActionMap_5_fu_1342_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((this_terminals_q0_local == 1'd1) & (1'b1 == ap_CS_fsm_state4)) | ((tmp_fu_1049_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state13)))) begin
        node_4_reg_628 <= node_5_reg_1772;
    end else if (((tmp_reg_1923 == 1'd0) & (icmp_ln127_reg_1836 == 1'd0) & (1'b1 == ap_CS_fsm_state16))) begin
        node_4_reg_628 <= child_reg_548;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        parent_fu_148 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        parent_fu_148 <= grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714_bestChildNode_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state23_on_subcall_done) & (this_terminals_load_1_reg_1987 == 1'd0) & (1'b1 == ap_CS_fsm_state23))) begin
        reward_1_reg_673 <= add_ln171_fu_1402_p2;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        reward_1_reg_673 <= select_ln35_fu_1636_p3;
    end else if (((1'b1 == ap_CS_fsm_state25) & ((tmp_239_reg_1991 == 1'd1) | (((gameState_hexGame_isPlayer1Turn_3_reg_602 == 1'd0) & (1'd0 == and_ln77_2_fu_1445_p2)) | ((gameState_hexGame_isPlayer1Turn_3_reg_602 == 1'd1) & (1'd0 == and_ln80_3_fu_1630_p2)))))) begin
        reward_1_reg_673 <= 20'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_1049_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state13))) begin
        this_nextFree_1_reg_657 <= ap_phi_mux_this_nextFree_02_phi_fu_534_p8;
    end else if (((tmp_reg_1923 == 1'd0) & (icmp_ln127_reg_1836 == 1'd0) & (1'b1 == ap_CS_fsm_state16))) begin
        this_nextFree_1_reg_657 <= this_nextFree_02_reg_530;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state23_on_subcall_done) & (this_terminals_load_1_reg_1987 == 1'd0) & (1'b1 == ap_CS_fsm_state23))) begin
        this_rng_0_reg_703 <= grp_rollout_fu_751_ap_return_1;
    end else if (((1'b1 == ap_CS_fsm_state27) | ((1'b1 == ap_CS_fsm_state25) & ((tmp_239_reg_1991 == 1'd1) | (((gameState_hexGame_isPlayer1Turn_3_reg_602 == 1'd0) & (1'd0 == and_ln77_2_fu_1445_p2)) | ((gameState_hexGame_isPlayer1Turn_3_reg_602 == 1'd1) & (1'd0 == and_ln80_3_fu_1630_p2))))))) begin
        this_rng_0_reg_703 <= this_rng_read;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state23_on_subcall_done) & (this_terminals_load_1_reg_1987 == 1'd0) & (1'b1 == ap_CS_fsm_state23))) begin
                visitCount_reg_687[0] <= 1'b0;
        visitCount_reg_687[2] <= 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state27) | ((1'b1 == ap_CS_fsm_state25) & ((tmp_239_reg_1991 == 1'd1) | (((gameState_hexGame_isPlayer1Turn_3_reg_602 == 1'd0) & (1'd0 == and_ln77_2_fu_1445_p2)) | ((gameState_hexGame_isPlayer1Turn_3_reg_602 == 1'd1) & (1'd0 == and_ln80_3_fu_1630_p2))))))) begin
                visitCount_reg_687[0] <= 1'b1;
        visitCount_reg_687[2] <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if (((targetBlock_reg_1901 == 1'd0) & (icmp_ln71_reg_1897 == 1'd0) & (icmp_ln54_reg_1845 == 1'd0) & (1'b1 == ap_CS_fsm_state13))) begin
        write_flag_0_reg_511 <= 1'd1;
    end else if ((((targetBlock_reg_1901 == 1'd1) & (1'b1 == ap_CS_fsm_state11)) | ((icmp_ln71_fu_988_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9)) | ((icmp_ln54_fu_886_p2 == 1'd1) & (icmp_ln127_fu_880_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        write_flag_0_reg_511 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((this_terminals_q0_local == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        write_flag_1_reg_641 <= 1'd0;
    end else if (((tmp_fu_1049_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state13))) begin
        write_flag_1_reg_641 <= ap_phi_mux_write_flag_0_phi_fu_515_p8;
    end else if (((tmp_reg_1923 == 1'd0) & (icmp_ln127_reg_1836 == 1'd0) & (1'b1 == ap_CS_fsm_state16))) begin
        write_flag_1_reg_641 <= write_flag_0_reg_511;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forward_Pipeline_VITIS_LOOP_73_1_fu_729_action_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        action_loc_fu_200 <= grp_forward_Pipeline_VITIS_LOOP_73_1_fu_729_action_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        bestChildNode_reg_1872 <= this_firstChilds_q0;
        logVisitCount_reg_1877 <= this_logVisitCounts_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        call_ret_reg_2015_0 <= grp_rollout_fu_751_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        connected_8_reg_2000 <= connected_8_fu_1378_p2;
        connected_reg_1995 <= connected_fu_1371_p2;
        this_terminals_load_1_reg_1987 <= this_terminals_q0;
        tmp_239_reg_1991 <= gameState_hexGame_lastMove_3_reg_566[32'd31];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        fill_5_reg_1966 <= fill_5_fu_1111_p2;
        fill_6_reg_1961 <= fill_6_fu_1104_p2;
        gameState_hexGame_isPlayer1Turn_4_reg_1942 <= grp_fu_814_p2;
        gameState_hexGame_player1_5_reg_1947 <= gameState_hexGame_player1_5_fu_1084_p2;
        gameState_hexGame_player2_5_reg_1954 <= gameState_hexGame_player2_5_fu_1098_p2;
        zext_ln12_reg_1937[5 : 0] <= zext_ln12_fu_1062_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        gameState_hexGame_isPlayer1Turn_s_78_reg_1867 <= grp_fu_814_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        gameState_hexGame_lastMove_4_reg_1820 <= boardState_hexGame_lastMove_s_fu_164;
        gameState_hexGame_player1_4_reg_1813 <= boardState_hexGame_player1_s_fu_160;
        gameState_hexGame_player2_4_reg_1806 <= boardState_hexGame_player2_s_fu_156;
        gameState_legalActionMap_4_reg_1799 <= boardState_legalActionMap_fu_152;
        icmp_ln127_reg_1836 <= icmp_ln127_fu_880_p2;
        icmp_ln54_reg_1845 <= icmp_ln54_fu_886_p2;
        this_numChildren_load_reg_1831 <= this_numChildren_q0;
        this_numLegalActions_load_reg_1826 <= this_numLegalActions_q0;
        this_triedMask_addr_reg_1849 <= zext_ln127_reg_1779;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        icmp_ln71_reg_1897 <= icmp_ln71_fu_988_p2;
        this_triedMask_load_reg_1887 <= this_triedMask_q0;
        untried_reg_1892 <= untried_fu_982_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        node_5_reg_1772 <= parent_fu_148;
        this_numChildren_addr_reg_1794 <= zext_ln127_fu_862_p1;
        zext_ln127_reg_1779[31 : 0] <= zext_ln127_fu_862_p1[31 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forward_Pipeline_VITIS_LOOP_114_14_fu_735_p_out1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        p_loc43_fu_184 <= grp_forward_Pipeline_VITIS_LOOP_114_14_fu_735_p_out1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forward_Pipeline_VITIS_LOOP_114_16_fu_774_p_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state26))) begin
        p_loc47_fu_172 <= grp_forward_Pipeline_VITIS_LOOP_114_16_fu_774_p_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forward_Pipeline_VITIS_LOOP_114_16_fu_774_p_out1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state26))) begin
        p_loc48_fu_168 <= grp_forward_Pipeline_VITIS_LOOP_114_16_fu_774_p_out1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forward_Pipeline_VITIS_LOOP_114_14_fu_735_p_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        p_loc_fu_188 <= grp_forward_Pipeline_VITIS_LOOP_114_14_fu_735_p_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forward_Pipeline_VITIS_LOOP_114_16_fu_774_prev_10_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state26))) begin
        prev_10_loc_fu_176 <= grp_forward_Pipeline_VITIS_LOOP_114_16_fu_774_prev_10_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forward_Pipeline_VITIS_LOOP_114_14_fu_735_prev_8_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        prev_8_loc_fu_192 <= grp_forward_Pipeline_VITIS_LOOP_114_14_fu_735_prev_8_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forward_Pipeline_VITIS_LOOP_114_15_fu_766_prev_9_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state24))) begin
        prev_9_loc_fu_180 <= grp_forward_Pipeline_VITIS_LOOP_114_15_fu_766_prev_9_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_forward_Pipeline_VITIS_LOOP_114_1_fu_744_prev_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
        prev_loc_fu_196 <= grp_forward_Pipeline_VITIS_LOOP_114_1_fu_744_prev_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        ref_tmp57_assign_5_reg_2010 <= grp_rollout_fu_751_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state22) & (grp_rollout_fu_751_ap_done == 1'b1)) | ((1'b1 == ap_CS_fsm_state21) & (grp_rollout_fu_751_ap_done == 1'b1)) | ((1'b1 == ap_CS_fsm_state20) & (grp_rollout_fu_751_ap_done == 1'b1)))) begin
        reg_829 <= grp_rollout_fu_751_ap_return_1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        reward_reg_2005 <= grp_rollout_fu_751_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        select_ln178_reg_2025 <= select_ln178_fu_1409_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        targetBlock_reg_1901 <= grp_forward_Pipeline_VITIS_LOOP_73_1_fu_729_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        this_firstChilds_addr_2_reg_1913 <= zext_ln127_reg_1779;
        zext_ln96_reg_1905[31 : 0] <= zext_ln96_fu_998_p1[31 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((targetBlock_reg_1901 == 1'd0) & (icmp_ln71_reg_1897 == 1'd0) & (icmp_ln54_reg_1845 == 1'd0) & (1'b1 == ap_CS_fsm_state13))) begin
        this_nextFree_02_reg_530 <= add_ln119_fu_1043_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        tmp_reg_1923 <= ap_phi_mux_child_phi_fu_552_p8[32'd31];
        zext_ln161_reg_1927[31 : 0] <= zext_ln161_fu_1057_p1[31 : 0];
    end
end

always @ (*) begin
    if ((grp_forward_Pipeline_VITIS_LOOP_73_1_fu_729_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((grp_forward_Pipeline_VITIS_LOOP_114_14_fu_735_ap_done == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

assign ap_ST_fsm_state16_blk = 1'b0;

always @ (*) begin
    if ((grp_forward_Pipeline_VITIS_LOOP_114_1_fu_744_ap_done == 1'b0)) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_rollout_fu_751_ap_done == 1'b0)) begin
        ap_ST_fsm_state20_blk = 1'b1;
    end else begin
        ap_ST_fsm_state20_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_rollout_fu_751_ap_done == 1'b0)) begin
        ap_ST_fsm_state21_blk = 1'b1;
    end else begin
        ap_ST_fsm_state21_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_rollout_fu_751_ap_done == 1'b0)) begin
        ap_ST_fsm_state22_blk = 1'b1;
    end else begin
        ap_ST_fsm_state22_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state23_on_subcall_done)) begin
        ap_ST_fsm_state23_blk = 1'b1;
    end else begin
        ap_ST_fsm_state23_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_forward_Pipeline_VITIS_LOOP_114_15_fu_766_ap_done == 1'b0)) begin
        ap_ST_fsm_state24_blk = 1'b1;
    end else begin
        ap_ST_fsm_state24_blk = 1'b0;
    end
end

assign ap_ST_fsm_state25_blk = 1'b0;

always @ (*) begin
    if ((grp_forward_Pipeline_VITIS_LOOP_114_16_fu_774_ap_done == 1'b0)) begin
        ap_ST_fsm_state26_blk = 1'b1;
    end else begin
        ap_ST_fsm_state26_blk = 1'b0;
    end
end

assign ap_ST_fsm_state27_blk = 1'b0;

always @ (*) begin
    if ((grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_ap_done == 1'b0)) begin
        ap_ST_fsm_state28_blk = 1'b1;
    end else begin
        ap_ST_fsm_state28_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state28)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((targetBlock_reg_1901 == 1'd0) & (icmp_ln71_reg_1897 == 1'd0) & (icmp_ln54_reg_1845 == 1'd0) & (1'b1 == ap_CS_fsm_state13))) begin
        ap_phi_mux_child_phi_fu_552_p8 = this_nextFree_read;
    end else begin
        ap_phi_mux_child_phi_fu_552_p8 = child_reg_548;
    end
end

always @ (*) begin
    if (((targetBlock_reg_1901 == 1'd0) & (icmp_ln71_reg_1897 == 1'd0) & (icmp_ln54_reg_1845 == 1'd0) & (1'b1 == ap_CS_fsm_state13))) begin
        ap_phi_mux_this_nextFree_02_phi_fu_534_p8 = add_ln119_fu_1043_p2;
    end else begin
        ap_phi_mux_this_nextFree_02_phi_fu_534_p8 = this_nextFree_02_reg_530;
    end
end

always @ (*) begin
    if (((targetBlock_reg_1901 == 1'd0) & (icmp_ln71_reg_1897 == 1'd0) & (icmp_ln54_reg_1845 == 1'd0) & (1'b1 == ap_CS_fsm_state13))) begin
        ap_phi_mux_write_flag_0_phi_fu_515_p8 = 1'd1;
    end else begin
        ap_phi_mux_write_flag_0_phi_fu_515_p8 = write_flag_0_reg_511;
    end
end

always @ (*) begin
    if (((grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state28))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state28))) begin
        ap_return_0 = select_ln178_reg_2025;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if (((grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state28))) begin
        ap_return_1 = this_rng_0_reg_703;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | ((this_terminals_load_1_reg_1987 == 1'd0) & (1'b1 == ap_CS_fsm_state23)))) begin
        grp_rollout_fu_751_this_rng_read = reg_829;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_rollout_fu_751_this_rng_read = this_rng_read;
    end else begin
        grp_rollout_fu_751_this_rng_read = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        this_childActions_address0_local = zext_ln161_fu_1057_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        this_childActions_address0_local = zext_ln96_fu_998_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        this_childActions_address0_local = zext_ln152_fu_894_p1;
    end else begin
        this_childActions_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state7))) begin
        this_childActions_ce0_local = 1'b1;
    end else begin
        this_childActions_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((targetBlock_reg_1901 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        this_childActions_we0_local = 1'b1;
    end else begin
        this_childActions_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        this_firstChilds_address0_local = this_firstChilds_addr_2_reg_1913;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        this_firstChilds_address0_local = zext_ln96_fu_998_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        this_firstChilds_address0_local = zext_ln127_reg_1779;
    end else begin
        this_firstChilds_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state4))) begin
        this_firstChilds_ce0_local = 1'b1;
    end else begin
        this_firstChilds_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        this_firstChilds_d0_local = this_nextFree_read;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        this_firstChilds_d0_local = 32'd4294967295;
    end else begin
        this_firstChilds_d0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | ((targetBlock_reg_1901 == 1'd0) & (1'b1 == ap_CS_fsm_state11)))) begin
        this_firstChilds_we0_local = 1'b1;
    end else begin
        this_firstChilds_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        this_isREDs_address0 = grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_isREDs_address0;
    end else begin
        this_isREDs_address0 = this_isREDs_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        this_isREDs_address0_local = zext_ln96_reg_1905;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        this_isREDs_address0_local = zext_ln127_reg_1779;
    end else begin
        this_isREDs_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        this_isREDs_ce0 = grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_isREDs_ce0;
    end else begin
        this_isREDs_ce0 = this_isREDs_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        this_isREDs_ce0_local = 1'b1;
    end else begin
        this_isREDs_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        this_isREDs_we0_local = 1'b1;
    end else begin
        this_isREDs_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        this_logVisitCounts_address0 = grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_logVisitCounts_address0;
    end else begin
        this_logVisitCounts_address0 = zext_ln127_reg_1779;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        this_logVisitCounts_ce0 = grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_logVisitCounts_ce0;
    end else begin
        this_logVisitCounts_ce0 = this_logVisitCounts_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        this_logVisitCounts_ce0_local = 1'b1;
    end else begin
        this_logVisitCounts_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        this_logVisitCounts_we0 = grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_logVisitCounts_we0;
    end else begin
        this_logVisitCounts_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        this_meanQ_address0 = grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_meanQ_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        this_meanQ_address0 = grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714_this_meanQ_address0;
    end else begin
        this_meanQ_address0 = zext_ln96_fu_998_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        this_meanQ_ce0 = grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_meanQ_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        this_meanQ_ce0 = grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714_this_meanQ_ce0;
    end else begin
        this_meanQ_ce0 = this_meanQ_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        this_meanQ_ce0_local = 1'b1;
    end else begin
        this_meanQ_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        this_meanQ_d0 = grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_meanQ_d0;
    end else begin
        this_meanQ_d0 = 20'd0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        this_meanQ_we0 = grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_meanQ_we0;
    end else begin
        this_meanQ_we0 = (this_meanQ_we0_out | 1'b0);
    end
end

always @ (*) begin
    if (((targetBlock_reg_1901 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        this_meanQ_we0_local = 1'b1;
    end else begin
        this_meanQ_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        this_nextSiblings_address0 = grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714_this_nextSiblings_address0;
    end else begin
        this_nextSiblings_address0 = zext_ln96_reg_1905;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        this_nextSiblings_ce0 = grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714_this_nextSiblings_ce0;
    end else begin
        this_nextSiblings_ce0 = this_nextSiblings_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        this_nextSiblings_ce0_local = 1'b1;
    end else begin
        this_nextSiblings_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((targetBlock_reg_1901 == 1'd0) & (icmp_ln71_reg_1897 == 1'd0) & (icmp_ln54_reg_1845 == 1'd0) & (1'b1 == ap_CS_fsm_state13))) begin
        this_nextSiblings_we0_local = 1'b1;
    end else begin
        this_nextSiblings_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        this_numChildren_address0_local = zext_ln96_reg_1905;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        this_numChildren_address0_local = this_numChildren_addr_reg_1794;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        this_numChildren_address0_local = zext_ln127_fu_862_p1;
    end else begin
        this_numChildren_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state2))) begin
        this_numChildren_ce0_local = 1'b1;
    end else begin
        this_numChildren_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        this_numChildren_d0_local = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        this_numChildren_d0_local = add_ln101_fu_1008_p2;
    end else begin
        this_numChildren_d0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | ((targetBlock_reg_1901 == 1'd0) & (1'b1 == ap_CS_fsm_state11)))) begin
        this_numChildren_we0_local = 1'b1;
    end else begin
        this_numChildren_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        this_numLegalActions_address0_local = zext_ln96_fu_998_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        this_numLegalActions_address0_local = zext_ln127_fu_862_p1;
    end else begin
        this_numLegalActions_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state2))) begin
        this_numLegalActions_ce0_local = 1'b1;
    end else begin
        this_numLegalActions_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((targetBlock_reg_1901 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        this_numLegalActions_we0_local = 1'b1;
    end else begin
        this_numLegalActions_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        this_parents_address0 = grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_parents_address0;
    end else begin
        this_parents_address0 = zext_ln96_fu_998_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        this_parents_ce0 = grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_parents_ce0;
    end else begin
        this_parents_ce0 = this_parents_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        this_parents_ce0_local = 1'b1;
    end else begin
        this_parents_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((targetBlock_reg_1901 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        this_parents_we0_local = 1'b1;
    end else begin
        this_parents_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        this_terminals_address0_local = zext_ln167_fu_1348_p1;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        this_terminals_address0_local = zext_ln161_reg_1927;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        this_terminals_address0_local = zext_ln96_fu_998_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        this_terminals_address0_local = zext_ln127_reg_1779;
    end else begin
        this_terminals_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state3))) begin
        this_terminals_ce0_local = 1'b1;
    end else begin
        this_terminals_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        this_terminals_d0_local = 1'd1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        this_terminals_d0_local = 1'd0;
    end else begin
        this_terminals_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((targetBlock_reg_1901 == 1'd0) & (1'b1 == ap_CS_fsm_state11)) | ((1'b1 == ap_CS_fsm_state16) & (((1'd1 == and_ln80_fu_1297_p2) & (gameState_hexGame_isPlayer1Turn_5_reg_501 == 1'd0) & (tmp_reg_1923 == 1'd0) & (icmp_ln127_reg_1836 == 1'd0)) | ((1'd1 == and_ln77_fu_1332_p2) & (gameState_hexGame_isPlayer1Turn_5_reg_501 == 1'd1) & (tmp_reg_1923 == 1'd0) & (icmp_ln127_reg_1836 == 1'd0)))))) begin
        this_terminals_we0_local = 1'b1;
    end else begin
        this_terminals_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        this_triedMask_address0_local = zext_ln96_reg_1905;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        this_triedMask_address0_local = this_triedMask_addr_reg_1849;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        this_triedMask_address0_local = zext_ln127_reg_1779;
    end else begin
        this_triedMask_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state3))) begin
        this_triedMask_ce0_local = 1'b1;
    end else begin
        this_triedMask_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        this_triedMask_d0_local = 49'd0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        this_triedMask_d0_local = or_ln102_fu_1024_p2;
    end else begin
        this_triedMask_d0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | ((targetBlock_reg_1901 == 1'd0) & (1'b1 == ap_CS_fsm_state11)))) begin
        this_triedMask_we0_local = 1'b1;
    end else begin
        this_triedMask_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        this_visitCounts_address0 = grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_visitCounts_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        this_visitCounts_address0 = grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714_this_visitCounts_address0;
    end else begin
        this_visitCounts_address0 = zext_ln96_fu_998_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        this_visitCounts_ce0 = grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_visitCounts_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        this_visitCounts_ce0 = grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714_this_visitCounts_ce0;
    end else begin
        this_visitCounts_ce0 = this_visitCounts_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        this_visitCounts_ce0_local = 1'b1;
    end else begin
        this_visitCounts_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        this_visitCounts_d0 = grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_visitCounts_d0;
    end else begin
        this_visitCounts_d0 = 32'd0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        this_visitCounts_we0 = grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_visitCounts_we0;
    end else begin
        this_visitCounts_we0 = (this_visitCounts_we0_out | 1'b0);
    end
end

always @ (*) begin
    if (((targetBlock_reg_1901 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        this_visitCounts_we0_local = 1'b1;
    end else begin
        this_visitCounts_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln54_fu_886_p2 == 1'd1) & (icmp_ln127_fu_880_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else if (((icmp_ln54_fu_886_p2 == 1'd0) & (icmp_ln127_fu_880_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((this_terminals_q0_local == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state9 : begin
            if (((icmp_ln71_fu_988_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((grp_forward_Pipeline_VITIS_LOOP_73_1_fu_729_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((targetBlock_reg_1901 == 1'd1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((tmp_fu_1049_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state14 : begin
            if (((gameState_hexGame_isPlayer1Turn_5_reg_501 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state15 : begin
            if (((grp_forward_Pipeline_VITIS_LOOP_114_14_fu_735_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state17 : begin
            if (((grp_forward_Pipeline_VITIS_LOOP_114_1_fu_744_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            if (((gameState_hexGame_isPlayer1Turn_3_reg_602 == 1'd1) & (tmp_239_fu_1353_p3 == 1'd0) & (this_terminals_q0_local == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end else if (((gameState_hexGame_isPlayer1Turn_3_reg_602 == 1'd0) & (tmp_239_fu_1353_p3 == 1'd0) & (this_terminals_q0_local == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end else if (((tmp_239_fu_1353_p3 == 1'd1) & (this_terminals_q0_local == 1'd1) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state20 : begin
            if (((1'b1 == ap_CS_fsm_state20) & (grp_rollout_fu_751_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state21 : begin
            if (((1'b1 == ap_CS_fsm_state21) & (grp_rollout_fu_751_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state22 : begin
            if (((1'b1 == ap_CS_fsm_state22) & (grp_rollout_fu_751_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end
        end
        ap_ST_fsm_state23 : begin
            if (((1'b0 == ap_block_state23_on_subcall_done) & (1'b1 == ap_CS_fsm_state23))) begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end
        end
        ap_ST_fsm_state24 : begin
            if (((grp_forward_Pipeline_VITIS_LOOP_114_15_fu_766_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state24))) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        ap_ST_fsm_state25 : begin
            if (((1'b1 == ap_CS_fsm_state25) & ((tmp_239_reg_1991 == 1'd1) | (((gameState_hexGame_isPlayer1Turn_3_reg_602 == 1'd0) & (1'd0 == and_ln77_2_fu_1445_p2)) | ((gameState_hexGame_isPlayer1Turn_3_reg_602 == 1'd1) & (1'd0 == and_ln80_3_fu_1630_p2)))))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end
        end
        ap_ST_fsm_state26 : begin
            if (((grp_forward_Pipeline_VITIS_LOOP_114_16_fu_774_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state26))) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state28 : begin
            if (((grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state28))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln101_fu_1008_p2 = (this_numChildren_load_reg_1831 + 32'd1);

assign add_ln119_fu_1043_p2 = (this_nextFree_read + 32'd1);

assign add_ln171_1_fu_1392_p2 = (ref_tmp57_assign_5_reg_2010 + reward_reg_2005);

assign add_ln171_2_fu_1396_p2 = (call_ret_reg_2015_0 + grp_rollout_fu_751_ap_return_0);

assign add_ln171_fu_1402_p2 = (add_ln171_2_fu_1396_p2 + add_ln171_1_fu_1392_p2);

assign and_ln77_2_fu_1445_p2 = (icmp_ln77_6_fu_1439_p2 & icmp_ln77_5_fu_1423_p2);

assign and_ln77_fu_1332_p2 = (icmp_ln77_fu_1310_p2 & icmp_ln77_4_fu_1326_p2);

assign and_ln80_3_fu_1630_p2 = (icmp_ln80_6_fu_1624_p2 & icmp_ln80_5_fu_1546_p2);

assign and_ln80_6_fu_1259_p15 = {{{{{{{{{{{{{{p_loc_fu_188}, {6'd0}}, {p_loc43_fu_184}}, {6'd0}}, {tmp_234_fu_1219_p3}}, {6'd0}}, {tmp_235_fu_1227_p3}}, {6'd0}}, {tmp_236_fu_1235_p3}}, {6'd0}}, {tmp_237_fu_1243_p3}}, {6'd0}}, {tmp_238_fu_1251_p3}}, {6'd0}};

assign and_ln80_8_fu_1516_p14 = {{{{{{{{{{{{{tmp_240_fu_1464_p3}, {6'd0}}, {tmp_241_fu_1472_p3}}, {6'd0}}, {tmp_242_fu_1480_p3}}, {6'd0}}, {tmp_243_fu_1488_p3}}, {6'd0}}, {tmp_244_fu_1496_p3}}, {6'd0}}, {tmp_245_fu_1504_p3}}, {6'd0}}, {trunc_ln80_2_fu_1512_p1}};

assign and_ln80_9_fu_1592_p15 = {{{{{{{{{{{{{{p_loc47_fu_172}, {6'd0}}, {p_loc48_fu_168}}, {6'd0}}, {tmp_246_fu_1552_p3}}, {6'd0}}, {tmp_247_fu_1560_p3}}, {6'd0}}, {tmp_248_fu_1568_p3}}, {6'd0}}, {tmp_249_fu_1576_p3}}, {6'd0}}, {tmp_250_fu_1584_p3}}, {6'd0}};

assign and_ln80_fu_1297_p2 = (icmp_ln80_fu_1213_p2 & icmp_ln80_4_fu_1291_p2);

assign and_ln_fu_1183_p14 = {{{{{{{{{{{{{tmp_228_fu_1131_p3}, {6'd0}}, {tmp_229_fu_1139_p3}}, {6'd0}}, {tmp_230_fu_1147_p3}}, {6'd0}}, {tmp_231_fu_1155_p3}}, {6'd0}}, {tmp_232_fu_1163_p3}}, {6'd0}}, {tmp_233_fu_1171_p3}}, {6'd0}}, {trunc_ln80_fu_1179_p1}};

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state23_on_subcall_done = ((this_terminals_load_1_reg_1987 == 1'd0) & (grp_rollout_fu_751_ap_done == 1'b0));
end

assign bit_2_fu_1070_p2 = 49'd1 << zext_ln56_2_fu_1066_p1;

assign bit_fu_912_p2 = 49'd1 << zext_ln56_fu_908_p1;

assign connected_8_fu_1378_p2 = (seed_1_fu_1365_p2 & gameState_hexGame_player2_6_reg_590);

assign connected_fu_1371_p2 = (seed_1_fu_1365_p2 & gameState_hexGame_player1_6_reg_578);

assign fill_5_fu_1111_p2 = (gameState_hexGame_player1_5_fu_1084_p2 & bit_2_fu_1070_p2);

assign fill_6_fu_1104_p2 = (gameState_hexGame_player2_5_fu_1098_p2 & bit_2_fu_1070_p2);

assign gameState_hexGame_player1_5_fu_1084_p2 = (select_ln58_3_fu_1076_p3 | gameState_hexGame_player1_4_reg_1813);

assign gameState_hexGame_player1_s_76_fu_926_p2 = (select_ln58_fu_918_p3 | boardState_hexGame_player1_s_fu_160);

assign gameState_hexGame_player2_5_fu_1098_p2 = (select_ln58_4_fu_1090_p3 | gameState_hexGame_player2_4_reg_1806);

assign gameState_hexGame_player2_s_77_fu_939_p2 = (select_ln58_2_fu_931_p3 | boardState_hexGame_player2_s_fu_156);

assign gameState_legalActionMap_5_fu_1342_p2 = (or_ln14_1_fu_1338_p2 ^ 49'd562949953421311);

assign gameState_legalActionMap_79_fu_950_p2 = (or_ln14_fu_944_p2 ^ 49'd562949953421311);

assign grp_forward_Pipeline_VITIS_LOOP_114_14_fu_735_ap_start = grp_forward_Pipeline_VITIS_LOOP_114_14_fu_735_ap_start_reg;

assign grp_forward_Pipeline_VITIS_LOOP_114_15_fu_766_ap_start = grp_forward_Pipeline_VITIS_LOOP_114_15_fu_766_ap_start_reg;

assign grp_forward_Pipeline_VITIS_LOOP_114_16_fu_774_ap_start = grp_forward_Pipeline_VITIS_LOOP_114_16_fu_774_ap_start_reg;

assign grp_forward_Pipeline_VITIS_LOOP_114_1_fu_744_ap_start = grp_forward_Pipeline_VITIS_LOOP_114_1_fu_744_ap_start_reg;

assign grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714_ap_start = grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714_ap_start_reg;

assign grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_ap_start = grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_ap_start_reg;

assign grp_forward_Pipeline_VITIS_LOOP_73_1_fu_729_ap_start = grp_forward_Pipeline_VITIS_LOOP_73_1_fu_729_ap_start_reg;

assign grp_fu_814_p2 = (gameState_hexGame_isPlayer1Turn_5_reg_501 ^ 1'd1);

assign grp_rollout_fu_751_ap_start = grp_rollout_fu_751_ap_start_reg;

assign icmp_ln127_fu_880_p2 = ((this_numLegalActions_q0 == this_numChildren_q0) ? 1'b1 : 1'b0);

assign icmp_ln54_fu_886_p2 = (($signed(this_nextFree_read) > $signed(32'd5099)) ? 1'b1 : 1'b0);

assign icmp_ln71_fu_988_p2 = ((untried_fu_982_p2 == 49'd0) ? 1'b1 : 1'b0);

assign icmp_ln77_4_fu_1326_p2 = ((tmp_227_fu_1316_p4 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln77_5_fu_1423_p2 = ((trunc_ln112_2_fu_1419_p1 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln77_6_fu_1439_p2 = ((tmp_251_fu_1429_p4 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln77_fu_1310_p2 = ((trunc_ln112_fu_1306_p1 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln80_4_fu_1291_p2 = ((and_ln80_6_fu_1259_p15 != 49'd0) ? 1'b1 : 1'b0);

assign icmp_ln80_5_fu_1546_p2 = ((and_ln80_8_fu_1516_p14 != 43'd0) ? 1'b1 : 1'b0);

assign icmp_ln80_6_fu_1624_p2 = ((and_ln80_9_fu_1592_p15 != 49'd0) ? 1'b1 : 1'b0);

assign icmp_ln80_fu_1213_p2 = ((and_ln_fu_1183_p14 != 43'd0) ? 1'b1 : 1'b0);

assign numLegalActionsHere_fu_1030_p2 = ($signed(this_numLegalActions_load_reg_1826) + $signed(32'd4294967295));

assign or_ln102_fu_1024_p2 = (this_triedMask_load_reg_1887 | shl_ln102_fu_1018_p2);

assign or_ln14_1_fu_1338_p2 = (gameState_hexGame_player2_5_reg_1954 | gameState_hexGame_player1_5_reg_1947);

assign or_ln14_fu_944_p2 = (gameState_hexGame_player2_s_77_fu_939_p2 | gameState_hexGame_player1_s_76_fu_926_p2);

assign prev_10_reload_cast53_fu_1454_p1 = prev_10_loc_fu_176;

assign prev_8_reload_cast52_fu_1121_p1 = prev_8_loc_fu_192;

assign seed_1_fu_1365_p2 = 49'd1 << zext_ln73_fu_1361_p1;

assign select_ln178_fu_1409_p3 = ((write_flag_1_reg_641[0:0] == 1'b1) ? this_nextFree_1_reg_657 : this_nextFree_read);

assign select_ln35_fu_1636_p3 = ((gameState_hexGame_isPlayer1Turn_3_reg_602[0:0] == 1'b1) ? 20'd0 : 20'd32768);

assign select_ln58_2_fu_931_p3 = ((gameState_hexGame_isPlayer1Turn_5_reg_501[0:0] == 1'b1) ? 49'd0 : bit_fu_912_p2);

assign select_ln58_3_fu_1076_p3 = ((gameState_hexGame_isPlayer1Turn_5_reg_501[0:0] == 1'b1) ? bit_2_fu_1070_p2 : 49'd0);

assign select_ln58_4_fu_1090_p3 = ((gameState_hexGame_isPlayer1Turn_5_reg_501[0:0] == 1'b1) ? 49'd0 : bit_2_fu_1070_p2);

assign select_ln58_fu_918_p3 = ((gameState_hexGame_isPlayer1Turn_5_reg_501[0:0] == 1'b1) ? bit_fu_912_p2 : 49'd0);

assign shl_ln102_fu_1018_p2 = 49'd1 << zext_ln102_fu_1014_p1;

assign this_childActions_address0 = this_childActions_address0_local;

assign this_childActions_ce0 = this_childActions_ce0_local;

assign this_childActions_d0 = action_loc_fu_200;

assign this_childActions_we0 = this_childActions_we0_local;

assign this_firstChilds_address0 = this_firstChilds_address0_local;

assign this_firstChilds_ce0 = this_firstChilds_ce0_local;

assign this_firstChilds_d0 = this_firstChilds_d0_local;

assign this_firstChilds_we0 = this_firstChilds_we0_local;

assign this_isREDs_d0 = xor_ln118_fu_1036_p2;

assign this_isREDs_we0 = this_isREDs_we0_local;

assign this_logVisitCounts_d0 = grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784_this_logVisitCounts_d0;

assign this_meanQ_we0_out = this_meanQ_we0_local;

assign this_nextSiblings_d0 = this_firstChilds_q0;

assign this_nextSiblings_we0 = this_nextSiblings_we0_local;

assign this_numChildren_address0 = this_numChildren_address0_local;

assign this_numChildren_ce0 = this_numChildren_ce0_local;

assign this_numChildren_d0 = this_numChildren_d0_local;

assign this_numChildren_we0 = this_numChildren_we0_local;

assign this_numLegalActions_address0 = this_numLegalActions_address0_local;

assign this_numLegalActions_ce0 = this_numLegalActions_ce0_local;

assign this_numLegalActions_d0 = numLegalActionsHere_fu_1030_p2;

assign this_numLegalActions_we0 = this_numLegalActions_we0_local;

assign this_parents_d0 = node_5_reg_1772;

assign this_parents_we0 = this_parents_we0_local;

assign this_terminals_address0 = this_terminals_address0_local;

assign this_terminals_ce0 = this_terminals_ce0_local;

assign this_terminals_d0 = this_terminals_d0_local;

assign this_terminals_q0_local = this_terminals_q0;

assign this_terminals_we0 = this_terminals_we0_local;

assign this_triedMask_address0 = this_triedMask_address0_local;

assign this_triedMask_ce0 = this_triedMask_ce0_local;

assign this_triedMask_d0 = this_triedMask_d0_local;

assign this_triedMask_we0 = this_triedMask_we0_local;

assign this_visitCounts_we0_out = this_visitCounts_we0_local;

assign tmp_227_fu_1316_p4 = {{prev_loc_fu_196[48:42]}};

assign tmp_228_fu_1131_p3 = prev_8_reload_cast52_fu_1121_p1[32'd42];

assign tmp_229_fu_1139_p3 = prev_8_reload_cast52_fu_1121_p1[32'd35];

assign tmp_230_fu_1147_p3 = prev_8_reload_cast52_fu_1121_p1[32'd28];

assign tmp_231_fu_1155_p3 = prev_8_reload_cast52_fu_1121_p1[32'd21];

assign tmp_232_fu_1163_p3 = prev_8_reload_cast52_fu_1121_p1[32'd14];

assign tmp_233_fu_1171_p3 = prev_8_reload_cast52_fu_1121_p1[32'd7];

assign tmp_234_fu_1219_p3 = prev_8_reload_cast52_fu_1121_p1[32'd34];

assign tmp_235_fu_1227_p3 = prev_8_reload_cast52_fu_1121_p1[32'd27];

assign tmp_236_fu_1235_p3 = prev_8_reload_cast52_fu_1121_p1[32'd20];

assign tmp_237_fu_1243_p3 = prev_8_reload_cast52_fu_1121_p1[32'd13];

assign tmp_238_fu_1251_p3 = prev_8_reload_cast52_fu_1121_p1[32'd6];

assign tmp_239_fu_1353_p3 = gameState_hexGame_lastMove_3_reg_566[32'd31];

assign tmp_240_fu_1464_p3 = prev_10_reload_cast53_fu_1454_p1[32'd42];

assign tmp_241_fu_1472_p3 = prev_10_reload_cast53_fu_1454_p1[32'd35];

assign tmp_242_fu_1480_p3 = prev_10_reload_cast53_fu_1454_p1[32'd28];

assign tmp_243_fu_1488_p3 = prev_10_reload_cast53_fu_1454_p1[32'd21];

assign tmp_244_fu_1496_p3 = prev_10_reload_cast53_fu_1454_p1[32'd14];

assign tmp_245_fu_1504_p3 = prev_10_reload_cast53_fu_1454_p1[32'd7];

assign tmp_246_fu_1552_p3 = prev_10_reload_cast53_fu_1454_p1[32'd34];

assign tmp_247_fu_1560_p3 = prev_10_reload_cast53_fu_1454_p1[32'd27];

assign tmp_248_fu_1568_p3 = prev_10_reload_cast53_fu_1454_p1[32'd20];

assign tmp_249_fu_1576_p3 = prev_10_reload_cast53_fu_1454_p1[32'd13];

assign tmp_250_fu_1584_p3 = prev_10_reload_cast53_fu_1454_p1[32'd6];

assign tmp_251_fu_1429_p4 = {{prev_9_loc_fu_180[48:42]}};

assign tmp_fu_1049_p3 = ap_phi_mux_child_phi_fu_552_p8[32'd31];

assign trunc_ln112_2_fu_1419_p1 = prev_9_loc_fu_180[6:0];

assign trunc_ln112_fu_1306_p1 = prev_loc_fu_196[6:0];

assign trunc_ln80_2_fu_1512_p1 = prev_10_loc_fu_176[0:0];

assign trunc_ln80_fu_1179_p1 = prev_8_loc_fu_192[0:0];

assign untried_fu_982_p2 = (xor_ln70_fu_976_p2 & gameState_legalActionMap_4_reg_1799);

assign xor_ln118_fu_1036_p2 = (this_isREDs_q0 ^ 1'd1);

assign xor_ln70_fu_976_p2 = (this_triedMask_q0 ^ 49'd562949953421311);

assign zext_ln102_fu_1014_p1 = action_loc_fu_200;

assign zext_ln127_fu_862_p1 = parent_fu_148;

assign zext_ln12_fu_1062_p1 = this_childActions_q0;

assign zext_ln152_1_fu_904_p1 = this_childActions_q0;

assign zext_ln152_fu_894_p1 = grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714_bestChildNode_out;

assign zext_ln161_fu_1057_p1 = ap_phi_mux_child_phi_fu_552_p8;

assign zext_ln167_fu_1348_p1 = node_4_reg_628;

assign zext_ln56_2_fu_1066_p1 = this_childActions_q0;

assign zext_ln56_fu_908_p1 = this_childActions_q0;

assign zext_ln73_fu_1361_p1 = gameState_hexGame_lastMove_3_reg_566;

assign zext_ln96_fu_998_p1 = this_nextFree_read;

always @ (posedge ap_clk) begin
    zext_ln127_reg_1779[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln96_reg_1905[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln161_reg_1927[63:32] <= 32'b00000000000000000000000000000000;
    zext_ln12_reg_1937[31:6] <= 26'b00000000000000000000000000;
    visitCount_reg_687[1] <= 1'b0;
end

endmodule //dut_forward
