// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="dut_dut,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.167437,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=128,HLS_SYN_DSP=0,HLS_SYN_FF=14889,HLS_SYN_LUT=30730,HLS_VERSION=2025_1}" *)

module dut (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        strm_in_dout,
        strm_in_empty_n,
        strm_in_read,
        strm_out_din,
        strm_out_full_n,
        strm_out_write
);

parameter    ap_ST_fsm_state1 = 12'd1;
parameter    ap_ST_fsm_state2 = 12'd2;
parameter    ap_ST_fsm_state3 = 12'd4;
parameter    ap_ST_fsm_state4 = 12'd8;
parameter    ap_ST_fsm_state5 = 12'd16;
parameter    ap_ST_fsm_state6 = 12'd32;
parameter    ap_ST_fsm_state7 = 12'd64;
parameter    ap_ST_fsm_state8 = 12'd128;
parameter    ap_ST_fsm_state9 = 12'd256;
parameter    ap_ST_fsm_state10 = 12'd512;
parameter    ap_ST_fsm_state11 = 12'd1024;
parameter    ap_ST_fsm_state12 = 12'd2048;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] strm_in_dout;
input   strm_in_empty_n;
output   strm_in_read;
output  [31:0] strm_out_din;
input   strm_out_full_n;
output   strm_out_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg strm_in_read;
reg strm_out_write;

(* fsm_encoding = "none" *) reg   [11:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    strm_in_blk_n;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
reg    strm_out_blk_n;
wire    ap_CS_fsm_state12;
wire   [0:0] grp_fu_277_p2;
reg   [0:0] is_red_reg_315;
reg   [0:0] is_player1_turn_reg_320;
wire   [12:0] this_parents_addr_reg_325;
wire   [12:0] this_firstChilds_addr_reg_330;
wire   [12:0] this_numChildren_addr_reg_335;
wire   [12:0] this_visitCounts_addr_reg_340;
wire   [12:0] this_meanQ_addr_reg_345;
wire   [12:0] this_terminals_addr_reg_350;
wire   [12:0] this_triedMask_addr_reg_355;
wire   [12:0] this_logVisitCounts_addr_reg_360;
wire   [31:0] last_move_fu_291_p2;
reg   [31:0] last_move_reg_371;
reg   [12:0] searcher_visitCounts_address0;
reg    searcher_visitCounts_ce0;
reg    searcher_visitCounts_we0;
reg   [31:0] searcher_visitCounts_d0;
wire   [31:0] searcher_visitCounts_q0;
reg   [12:0] searcher_meanQ_address0;
reg    searcher_meanQ_ce0;
reg    searcher_meanQ_we0;
reg   [19:0] searcher_meanQ_d0;
wire   [19:0] searcher_meanQ_q0;
reg   [12:0] searcher_parents_address0;
reg    searcher_parents_ce0;
reg    searcher_parents_we0;
reg   [31:0] searcher_parents_d0;
wire   [31:0] searcher_parents_q0;
reg   [12:0] searcher_firstChilds_address0;
reg    searcher_firstChilds_ce0;
reg    searcher_firstChilds_we0;
reg   [31:0] searcher_firstChilds_d0;
wire   [31:0] searcher_firstChilds_q0;
reg   [12:0] searcher_numChildren_address0;
reg    searcher_numChildren_ce0;
reg    searcher_numChildren_we0;
reg   [31:0] searcher_numChildren_d0;
wire   [31:0] searcher_numChildren_q0;
reg    searcher_nextSiblings_ce0;
reg    searcher_nextSiblings_we0;
wire   [31:0] searcher_nextSiblings_q0;
reg    searcher_numLegalActions_ce0;
reg    searcher_numLegalActions_we0;
wire   [31:0] searcher_numLegalActions_q0;
reg   [12:0] searcher_terminals_address0;
reg    searcher_terminals_ce0;
reg    searcher_terminals_we0;
reg   [0:0] searcher_terminals_d0;
wire   [0:0] searcher_terminals_q0;
reg    searcher_childActions_ce0;
reg    searcher_childActions_we0;
wire   [5:0] searcher_childActions_q0;
reg   [12:0] searcher_triedMask_address0;
reg    searcher_triedMask_ce0;
reg    searcher_triedMask_we0;
reg   [48:0] searcher_triedMask_d0;
wire   [48:0] searcher_triedMask_q0;
reg    searcher_isREDs_ce0;
reg    searcher_isREDs_we0;
wire   [0:0] searcher_isREDs_q0;
reg   [12:0] searcher_logVisitCounts_address0;
reg    searcher_logVisitCounts_ce0;
reg    searcher_logVisitCounts_we0;
reg   [31:0] searcher_logVisitCounts_d0;
wire   [31:0] searcher_logVisitCounts_q0;
wire    grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_ap_start;
wire    grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_ap_done;
wire    grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_ap_idle;
wire    grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_ap_ready;
wire    grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_strm_in_read;
wire   [48:0] grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_player1_48_out;
wire    grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_player1_48_out_ap_vld;
wire    grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_ap_start;
wire    grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_ap_done;
wire    grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_ap_idle;
wire    grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_ap_ready;
wire    grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_strm_in_read;
wire   [48:0] grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_player2_out;
wire    grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_player2_out_ap_vld;
wire    grp_search_fu_247_ap_start;
wire    grp_search_fu_247_ap_done;
wire    grp_search_fu_247_ap_idle;
wire    grp_search_fu_247_ap_ready;
wire   [12:0] grp_search_fu_247_this_visitCounts_address0;
wire    grp_search_fu_247_this_visitCounts_ce0;
wire    grp_search_fu_247_this_visitCounts_we0;
wire   [31:0] grp_search_fu_247_this_visitCounts_d0;
wire   [12:0] grp_search_fu_247_this_meanQ_address0;
wire    grp_search_fu_247_this_meanQ_ce0;
wire    grp_search_fu_247_this_meanQ_we0;
wire   [19:0] grp_search_fu_247_this_meanQ_d0;
wire   [12:0] grp_search_fu_247_this_parents_address0;
wire    grp_search_fu_247_this_parents_ce0;
wire    grp_search_fu_247_this_parents_we0;
wire   [31:0] grp_search_fu_247_this_parents_d0;
wire   [12:0] grp_search_fu_247_this_firstChilds_address0;
wire    grp_search_fu_247_this_firstChilds_ce0;
wire    grp_search_fu_247_this_firstChilds_we0;
wire   [31:0] grp_search_fu_247_this_firstChilds_d0;
wire   [12:0] grp_search_fu_247_this_numChildren_address0;
wire    grp_search_fu_247_this_numChildren_ce0;
wire    grp_search_fu_247_this_numChildren_we0;
wire   [31:0] grp_search_fu_247_this_numChildren_d0;
wire   [12:0] grp_search_fu_247_this_nextSiblings_address0;
wire    grp_search_fu_247_this_nextSiblings_ce0;
wire    grp_search_fu_247_this_nextSiblings_we0;
wire   [31:0] grp_search_fu_247_this_nextSiblings_d0;
wire   [12:0] grp_search_fu_247_this_numLegalActions_address0;
wire    grp_search_fu_247_this_numLegalActions_ce0;
wire    grp_search_fu_247_this_numLegalActions_we0;
wire   [31:0] grp_search_fu_247_this_numLegalActions_d0;
wire   [12:0] grp_search_fu_247_this_terminals_address0;
wire    grp_search_fu_247_this_terminals_ce0;
wire    grp_search_fu_247_this_terminals_we0;
wire   [0:0] grp_search_fu_247_this_terminals_d0;
wire   [12:0] grp_search_fu_247_this_childActions_address0;
wire    grp_search_fu_247_this_childActions_ce0;
wire    grp_search_fu_247_this_childActions_we0;
wire   [5:0] grp_search_fu_247_this_childActions_d0;
wire   [12:0] grp_search_fu_247_this_triedMask_address0;
wire    grp_search_fu_247_this_triedMask_ce0;
wire    grp_search_fu_247_this_triedMask_we0;
wire   [48:0] grp_search_fu_247_this_triedMask_d0;
wire   [12:0] grp_search_fu_247_this_isREDs_address0;
wire    grp_search_fu_247_this_isREDs_ce0;
wire    grp_search_fu_247_this_isREDs_we0;
wire   [0:0] grp_search_fu_247_this_isREDs_d0;
wire   [12:0] grp_search_fu_247_this_logVisitCounts_address0;
wire    grp_search_fu_247_this_logVisitCounts_ce0;
wire    grp_search_fu_247_this_logVisitCounts_we0;
wire   [31:0] grp_search_fu_247_this_logVisitCounts_d0;
reg   [5:0] grp_search_fu_247_this_rng_read;
wire   [5:0] grp_search_fu_247_ap_return;
reg    grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_search_fu_247_ap_start_reg;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state9;
wire    searcher_visitCounts_we0_out;
wire    searcher_meanQ_we0_out;
wire    searcher_parents_we0_out;
wire    searcher_firstChilds_we0_out;
wire    searcher_numChildren_we0_out;
wire    searcher_terminals_we0_out;
wire    searcher_triedMask_we0_out;
wire    searcher_logVisitCounts_we0_out;
reg    searcher_parents_we0_local;
reg    searcher_parents_ce0_local;
reg   [12:0] searcher_parents_address0_local;
wire    ap_CS_fsm_state10;
reg    searcher_firstChilds_we0_local;
reg    searcher_firstChilds_ce0_local;
reg   [12:0] searcher_firstChilds_address0_local;
reg    searcher_numChildren_we0_local;
reg    searcher_numChildren_ce0_local;
reg   [12:0] searcher_numChildren_address0_local;
reg    searcher_visitCounts_we0_local;
reg    searcher_visitCounts_ce0_local;
reg   [12:0] searcher_visitCounts_address0_local;
reg    searcher_meanQ_we0_local;
reg    searcher_meanQ_ce0_local;
reg   [12:0] searcher_meanQ_address0_local;
reg    searcher_terminals_we0_local;
reg    searcher_terminals_ce0_local;
reg   [12:0] searcher_terminals_address0_local;
reg    searcher_triedMask_we0_local;
reg    searcher_triedMask_ce0_local;
reg   [12:0] searcher_triedMask_address0_local;
reg    searcher_logVisitCounts_we0_local;
reg    searcher_logVisitCounts_ce0_local;
reg   [12:0] searcher_logVisitCounts_address0_local;
reg   [11:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 12'd1;
#0 grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_ap_start_reg = 1'b0;
#0 grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_ap_start_reg = 1'b0;
#0 grp_search_fu_247_ap_start_reg = 1'b0;
end

dut_searcher_visitCounts_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 5100 ),
    .AddressWidth( 13 ))
searcher_visitCounts_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(searcher_visitCounts_address0),
    .ce0(searcher_visitCounts_ce0),
    .we0(searcher_visitCounts_we0),
    .d0(searcher_visitCounts_d0),
    .q0(searcher_visitCounts_q0)
);

dut_searcher_meanQ_RAM_AUTO_1R1W #(
    .DataWidth( 20 ),
    .AddressRange( 5100 ),
    .AddressWidth( 13 ))
searcher_meanQ_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(searcher_meanQ_address0),
    .ce0(searcher_meanQ_ce0),
    .we0(searcher_meanQ_we0),
    .d0(searcher_meanQ_d0),
    .q0(searcher_meanQ_q0)
);

dut_searcher_visitCounts_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 5100 ),
    .AddressWidth( 13 ))
searcher_parents_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(searcher_parents_address0),
    .ce0(searcher_parents_ce0),
    .we0(searcher_parents_we0),
    .d0(searcher_parents_d0),
    .q0(searcher_parents_q0)
);

dut_searcher_visitCounts_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 5100 ),
    .AddressWidth( 13 ))
searcher_firstChilds_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(searcher_firstChilds_address0),
    .ce0(searcher_firstChilds_ce0),
    .we0(searcher_firstChilds_we0),
    .d0(searcher_firstChilds_d0),
    .q0(searcher_firstChilds_q0)
);

dut_searcher_visitCounts_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 5100 ),
    .AddressWidth( 13 ))
searcher_numChildren_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(searcher_numChildren_address0),
    .ce0(searcher_numChildren_ce0),
    .we0(searcher_numChildren_we0),
    .d0(searcher_numChildren_d0),
    .q0(searcher_numChildren_q0)
);

dut_searcher_visitCounts_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 5100 ),
    .AddressWidth( 13 ))
searcher_nextSiblings_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_search_fu_247_this_nextSiblings_address0),
    .ce0(searcher_nextSiblings_ce0),
    .we0(searcher_nextSiblings_we0),
    .d0(grp_search_fu_247_this_nextSiblings_d0),
    .q0(searcher_nextSiblings_q0)
);

dut_searcher_visitCounts_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 5100 ),
    .AddressWidth( 13 ))
searcher_numLegalActions_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_search_fu_247_this_numLegalActions_address0),
    .ce0(searcher_numLegalActions_ce0),
    .we0(searcher_numLegalActions_we0),
    .d0(grp_search_fu_247_this_numLegalActions_d0),
    .q0(searcher_numLegalActions_q0)
);

dut_searcher_terminals_RAM_AUTO_1R1W #(
    .DataWidth( 1 ),
    .AddressRange( 5100 ),
    .AddressWidth( 13 ))
searcher_terminals_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(searcher_terminals_address0),
    .ce0(searcher_terminals_ce0),
    .we0(searcher_terminals_we0),
    .d0(searcher_terminals_d0),
    .q0(searcher_terminals_q0)
);

dut_searcher_childActions_RAM_AUTO_1R1W #(
    .DataWidth( 6 ),
    .AddressRange( 5100 ),
    .AddressWidth( 13 ))
searcher_childActions_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_search_fu_247_this_childActions_address0),
    .ce0(searcher_childActions_ce0),
    .we0(searcher_childActions_we0),
    .d0(grp_search_fu_247_this_childActions_d0),
    .q0(searcher_childActions_q0)
);

dut_searcher_triedMask_RAM_AUTO_1R1W #(
    .DataWidth( 49 ),
    .AddressRange( 5100 ),
    .AddressWidth( 13 ))
searcher_triedMask_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(searcher_triedMask_address0),
    .ce0(searcher_triedMask_ce0),
    .we0(searcher_triedMask_we0),
    .d0(searcher_triedMask_d0),
    .q0(searcher_triedMask_q0)
);

dut_searcher_terminals_RAM_AUTO_1R1W #(
    .DataWidth( 1 ),
    .AddressRange( 5100 ),
    .AddressWidth( 13 ))
searcher_isREDs_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_search_fu_247_this_isREDs_address0),
    .ce0(searcher_isREDs_ce0),
    .we0(searcher_isREDs_we0),
    .d0(grp_search_fu_247_this_isREDs_d0),
    .q0(searcher_isREDs_q0)
);

dut_searcher_visitCounts_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 5100 ),
    .AddressWidth( 13 ))
searcher_logVisitCounts_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(searcher_logVisitCounts_address0),
    .ce0(searcher_logVisitCounts_ce0),
    .we0(searcher_logVisitCounts_we0),
    .d0(searcher_logVisitCounts_d0),
    .q0(searcher_logVisitCounts_q0)
);

dut_dut_Pipeline_VITIS_LOOP_17_1 grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_ap_start),
    .ap_done(grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_ap_done),
    .ap_idle(grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_ap_idle),
    .ap_ready(grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_ap_ready),
    .strm_in_dout(strm_in_dout),
    .strm_in_empty_n(strm_in_empty_n),
    .strm_in_read(grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_strm_in_read),
    .player1_48_out(grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_player1_48_out),
    .player1_48_out_ap_vld(grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_player1_48_out_ap_vld)
);

dut_dut_Pipeline_VITIS_LOOP_27_3 grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_ap_start),
    .ap_done(grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_ap_done),
    .ap_idle(grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_ap_idle),
    .ap_ready(grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_ap_ready),
    .strm_in_dout(strm_in_dout),
    .strm_in_empty_n(strm_in_empty_n),
    .strm_in_read(grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_strm_in_read),
    .player2_out(grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_player2_out),
    .player2_out_ap_vld(grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_player2_out_ap_vld)
);

dut_search grp_search_fu_247(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_search_fu_247_ap_start),
    .ap_done(grp_search_fu_247_ap_done),
    .ap_idle(grp_search_fu_247_ap_idle),
    .ap_ready(grp_search_fu_247_ap_ready),
    .this_visitCounts_address0(grp_search_fu_247_this_visitCounts_address0),
    .this_visitCounts_ce0(grp_search_fu_247_this_visitCounts_ce0),
    .this_visitCounts_we0(grp_search_fu_247_this_visitCounts_we0),
    .this_visitCounts_d0(grp_search_fu_247_this_visitCounts_d0),
    .this_visitCounts_q0(searcher_visitCounts_q0),
    .this_meanQ_address0(grp_search_fu_247_this_meanQ_address0),
    .this_meanQ_ce0(grp_search_fu_247_this_meanQ_ce0),
    .this_meanQ_we0(grp_search_fu_247_this_meanQ_we0),
    .this_meanQ_d0(grp_search_fu_247_this_meanQ_d0),
    .this_meanQ_q0(searcher_meanQ_q0),
    .this_parents_address0(grp_search_fu_247_this_parents_address0),
    .this_parents_ce0(grp_search_fu_247_this_parents_ce0),
    .this_parents_we0(grp_search_fu_247_this_parents_we0),
    .this_parents_d0(grp_search_fu_247_this_parents_d0),
    .this_parents_q0(searcher_parents_q0),
    .this_firstChilds_address0(grp_search_fu_247_this_firstChilds_address0),
    .this_firstChilds_ce0(grp_search_fu_247_this_firstChilds_ce0),
    .this_firstChilds_we0(grp_search_fu_247_this_firstChilds_we0),
    .this_firstChilds_d0(grp_search_fu_247_this_firstChilds_d0),
    .this_firstChilds_q0(searcher_firstChilds_q0),
    .this_numChildren_address0(grp_search_fu_247_this_numChildren_address0),
    .this_numChildren_ce0(grp_search_fu_247_this_numChildren_ce0),
    .this_numChildren_we0(grp_search_fu_247_this_numChildren_we0),
    .this_numChildren_d0(grp_search_fu_247_this_numChildren_d0),
    .this_numChildren_q0(searcher_numChildren_q0),
    .this_nextSiblings_address0(grp_search_fu_247_this_nextSiblings_address0),
    .this_nextSiblings_ce0(grp_search_fu_247_this_nextSiblings_ce0),
    .this_nextSiblings_we0(grp_search_fu_247_this_nextSiblings_we0),
    .this_nextSiblings_d0(grp_search_fu_247_this_nextSiblings_d0),
    .this_nextSiblings_q0(searcher_nextSiblings_q0),
    .this_numLegalActions_address0(grp_search_fu_247_this_numLegalActions_address0),
    .this_numLegalActions_ce0(grp_search_fu_247_this_numLegalActions_ce0),
    .this_numLegalActions_we0(grp_search_fu_247_this_numLegalActions_we0),
    .this_numLegalActions_d0(grp_search_fu_247_this_numLegalActions_d0),
    .this_numLegalActions_q0(searcher_numLegalActions_q0),
    .this_terminals_address0(grp_search_fu_247_this_terminals_address0),
    .this_terminals_ce0(grp_search_fu_247_this_terminals_ce0),
    .this_terminals_we0(grp_search_fu_247_this_terminals_we0),
    .this_terminals_d0(grp_search_fu_247_this_terminals_d0),
    .this_terminals_q0(searcher_terminals_q0),
    .this_childActions_address0(grp_search_fu_247_this_childActions_address0),
    .this_childActions_ce0(grp_search_fu_247_this_childActions_ce0),
    .this_childActions_we0(grp_search_fu_247_this_childActions_we0),
    .this_childActions_d0(grp_search_fu_247_this_childActions_d0),
    .this_childActions_q0(searcher_childActions_q0),
    .this_triedMask_address0(grp_search_fu_247_this_triedMask_address0),
    .this_triedMask_ce0(grp_search_fu_247_this_triedMask_ce0),
    .this_triedMask_we0(grp_search_fu_247_this_triedMask_we0),
    .this_triedMask_d0(grp_search_fu_247_this_triedMask_d0),
    .this_triedMask_q0(searcher_triedMask_q0),
    .this_isREDs_address0(grp_search_fu_247_this_isREDs_address0),
    .this_isREDs_ce0(grp_search_fu_247_this_isREDs_ce0),
    .this_isREDs_we0(grp_search_fu_247_this_isREDs_we0),
    .this_isREDs_d0(grp_search_fu_247_this_isREDs_d0),
    .this_isREDs_q0(searcher_isREDs_q0),
    .this_logVisitCounts_address0(grp_search_fu_247_this_logVisitCounts_address0),
    .this_logVisitCounts_ce0(grp_search_fu_247_this_logVisitCounts_ce0),
    .this_logVisitCounts_we0(grp_search_fu_247_this_logVisitCounts_we0),
    .this_logVisitCounts_d0(grp_search_fu_247_this_logVisitCounts_d0),
    .this_logVisitCounts_q0(searcher_logVisitCounts_q0),
    .this_rng_read(grp_search_fu_247_this_rng_read),
    .boardState_isPlayer1Turn_s(is_player1_turn_reg_320),
    .boardState_lastMove_s(last_move_reg_371),
    .boardState_player1_s(grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_player1_48_out),
    .boardState_player2_s(grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_player2_out),
    .isRED(is_red_reg_315),
    .ap_return(grp_search_fu_247_ap_return)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_ap_start_reg <= 1'b1;
        end else if ((grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_ap_ready == 1'b1)) begin
            grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_ap_start_reg <= 1'b1;
        end else if ((grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_ap_ready == 1'b1)) begin
            grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_search_fu_247_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state11) | ((strm_in_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state8)))) begin
            grp_search_fu_247_ap_start_reg <= 1'b1;
        end else if ((grp_search_fu_247_ap_ready == 1'b1)) begin
            grp_search_fu_247_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        is_player1_turn_reg_320 <= grp_fu_277_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        is_red_reg_315 <= grp_fu_277_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        last_move_reg_371 <= last_move_fu_291_p2;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if (((strm_out_full_n == 1'b0) | (grp_search_fu_247_ap_done == 1'b0))) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((strm_in_empty_n == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((strm_in_empty_n == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if ((strm_in_empty_n == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if ((strm_in_empty_n == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_search_fu_247_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((strm_out_full_n == 1'b0) | (grp_search_fu_247_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state12))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((strm_out_full_n == 1'b0) | (grp_search_fu_247_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state12))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_search_fu_247_this_rng_read = 6'd43;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_search_fu_247_this_rng_read = 6'd42;
    end else begin
        grp_search_fu_247_this_rng_read = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state9))) begin
        searcher_childActions_ce0 = grp_search_fu_247_this_childActions_ce0;
    end else begin
        searcher_childActions_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state9))) begin
        searcher_childActions_we0 = grp_search_fu_247_this_childActions_we0;
    end else begin
        searcher_childActions_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state9))) begin
        searcher_firstChilds_address0 = grp_search_fu_247_this_firstChilds_address0;
    end else begin
        searcher_firstChilds_address0 = searcher_firstChilds_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        searcher_firstChilds_address0_local = this_firstChilds_addr_reg_330;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        searcher_firstChilds_address0_local = 64'd0;
    end else begin
        searcher_firstChilds_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state9))) begin
        searcher_firstChilds_ce0 = grp_search_fu_247_this_firstChilds_ce0;
    end else begin
        searcher_firstChilds_ce0 = searcher_firstChilds_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | ((strm_in_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state7)))) begin
        searcher_firstChilds_ce0_local = 1'b1;
    end else begin
        searcher_firstChilds_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state9))) begin
        searcher_firstChilds_d0 = grp_search_fu_247_this_firstChilds_d0;
    end else begin
        searcher_firstChilds_d0 = 32'd4294967295;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state9))) begin
        searcher_firstChilds_we0 = grp_search_fu_247_this_firstChilds_we0;
    end else begin
        searcher_firstChilds_we0 = (searcher_firstChilds_we0_out | 1'b0);
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | ((strm_in_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state7)))) begin
        searcher_firstChilds_we0_local = 1'b1;
    end else begin
        searcher_firstChilds_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state9))) begin
        searcher_isREDs_ce0 = grp_search_fu_247_this_isREDs_ce0;
    end else begin
        searcher_isREDs_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state9))) begin
        searcher_isREDs_we0 = grp_search_fu_247_this_isREDs_we0;
    end else begin
        searcher_isREDs_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state9))) begin
        searcher_logVisitCounts_address0 = grp_search_fu_247_this_logVisitCounts_address0;
    end else begin
        searcher_logVisitCounts_address0 = searcher_logVisitCounts_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        searcher_logVisitCounts_address0_local = this_logVisitCounts_addr_reg_360;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        searcher_logVisitCounts_address0_local = 64'd0;
    end else begin
        searcher_logVisitCounts_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state9))) begin
        searcher_logVisitCounts_ce0 = grp_search_fu_247_this_logVisitCounts_ce0;
    end else begin
        searcher_logVisitCounts_ce0 = searcher_logVisitCounts_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | ((strm_in_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state7)))) begin
        searcher_logVisitCounts_ce0_local = 1'b1;
    end else begin
        searcher_logVisitCounts_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state9))) begin
        searcher_logVisitCounts_d0 = grp_search_fu_247_this_logVisitCounts_d0;
    end else begin
        searcher_logVisitCounts_d0 = 32'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state9))) begin
        searcher_logVisitCounts_we0 = grp_search_fu_247_this_logVisitCounts_we0;
    end else begin
        searcher_logVisitCounts_we0 = (searcher_logVisitCounts_we0_out | 1'b0);
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | ((strm_in_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state7)))) begin
        searcher_logVisitCounts_we0_local = 1'b1;
    end else begin
        searcher_logVisitCounts_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state9))) begin
        searcher_meanQ_address0 = grp_search_fu_247_this_meanQ_address0;
    end else begin
        searcher_meanQ_address0 = searcher_meanQ_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        searcher_meanQ_address0_local = this_meanQ_addr_reg_345;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        searcher_meanQ_address0_local = 64'd0;
    end else begin
        searcher_meanQ_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state9))) begin
        searcher_meanQ_ce0 = grp_search_fu_247_this_meanQ_ce0;
    end else begin
        searcher_meanQ_ce0 = searcher_meanQ_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | ((strm_in_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state7)))) begin
        searcher_meanQ_ce0_local = 1'b1;
    end else begin
        searcher_meanQ_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state9))) begin
        searcher_meanQ_d0 = grp_search_fu_247_this_meanQ_d0;
    end else begin
        searcher_meanQ_d0 = 20'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state9))) begin
        searcher_meanQ_we0 = grp_search_fu_247_this_meanQ_we0;
    end else begin
        searcher_meanQ_we0 = (searcher_meanQ_we0_out | 1'b0);
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | ((strm_in_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state7)))) begin
        searcher_meanQ_we0_local = 1'b1;
    end else begin
        searcher_meanQ_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state9))) begin
        searcher_nextSiblings_ce0 = grp_search_fu_247_this_nextSiblings_ce0;
    end else begin
        searcher_nextSiblings_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state9))) begin
        searcher_nextSiblings_we0 = grp_search_fu_247_this_nextSiblings_we0;
    end else begin
        searcher_nextSiblings_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state9))) begin
        searcher_numChildren_address0 = grp_search_fu_247_this_numChildren_address0;
    end else begin
        searcher_numChildren_address0 = searcher_numChildren_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        searcher_numChildren_address0_local = this_numChildren_addr_reg_335;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        searcher_numChildren_address0_local = 64'd0;
    end else begin
        searcher_numChildren_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state9))) begin
        searcher_numChildren_ce0 = grp_search_fu_247_this_numChildren_ce0;
    end else begin
        searcher_numChildren_ce0 = searcher_numChildren_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | ((strm_in_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state7)))) begin
        searcher_numChildren_ce0_local = 1'b1;
    end else begin
        searcher_numChildren_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state9))) begin
        searcher_numChildren_d0 = grp_search_fu_247_this_numChildren_d0;
    end else begin
        searcher_numChildren_d0 = 32'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state9))) begin
        searcher_numChildren_we0 = grp_search_fu_247_this_numChildren_we0;
    end else begin
        searcher_numChildren_we0 = (searcher_numChildren_we0_out | 1'b0);
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | ((strm_in_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state7)))) begin
        searcher_numChildren_we0_local = 1'b1;
    end else begin
        searcher_numChildren_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state9))) begin
        searcher_numLegalActions_ce0 = grp_search_fu_247_this_numLegalActions_ce0;
    end else begin
        searcher_numLegalActions_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state9))) begin
        searcher_numLegalActions_we0 = grp_search_fu_247_this_numLegalActions_we0;
    end else begin
        searcher_numLegalActions_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state9))) begin
        searcher_parents_address0 = grp_search_fu_247_this_parents_address0;
    end else begin
        searcher_parents_address0 = searcher_parents_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        searcher_parents_address0_local = this_parents_addr_reg_325;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        searcher_parents_address0_local = 64'd0;
    end else begin
        searcher_parents_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state9))) begin
        searcher_parents_ce0 = grp_search_fu_247_this_parents_ce0;
    end else begin
        searcher_parents_ce0 = searcher_parents_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | ((strm_in_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state7)))) begin
        searcher_parents_ce0_local = 1'b1;
    end else begin
        searcher_parents_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state9))) begin
        searcher_parents_d0 = grp_search_fu_247_this_parents_d0;
    end else begin
        searcher_parents_d0 = 32'd4294967295;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state9))) begin
        searcher_parents_we0 = grp_search_fu_247_this_parents_we0;
    end else begin
        searcher_parents_we0 = (searcher_parents_we0_out | 1'b0);
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | ((strm_in_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state7)))) begin
        searcher_parents_we0_local = 1'b1;
    end else begin
        searcher_parents_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state9))) begin
        searcher_terminals_address0 = grp_search_fu_247_this_terminals_address0;
    end else begin
        searcher_terminals_address0 = searcher_terminals_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        searcher_terminals_address0_local = this_terminals_addr_reg_350;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        searcher_terminals_address0_local = 64'd0;
    end else begin
        searcher_terminals_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state9))) begin
        searcher_terminals_ce0 = grp_search_fu_247_this_terminals_ce0;
    end else begin
        searcher_terminals_ce0 = searcher_terminals_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | ((strm_in_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state7)))) begin
        searcher_terminals_ce0_local = 1'b1;
    end else begin
        searcher_terminals_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state9))) begin
        searcher_terminals_d0 = grp_search_fu_247_this_terminals_d0;
    end else begin
        searcher_terminals_d0 = 1'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state9))) begin
        searcher_terminals_we0 = grp_search_fu_247_this_terminals_we0;
    end else begin
        searcher_terminals_we0 = (searcher_terminals_we0_out | 1'b0);
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | ((strm_in_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state7)))) begin
        searcher_terminals_we0_local = 1'b1;
    end else begin
        searcher_terminals_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state9))) begin
        searcher_triedMask_address0 = grp_search_fu_247_this_triedMask_address0;
    end else begin
        searcher_triedMask_address0 = searcher_triedMask_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        searcher_triedMask_address0_local = this_triedMask_addr_reg_355;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        searcher_triedMask_address0_local = 64'd0;
    end else begin
        searcher_triedMask_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state9))) begin
        searcher_triedMask_ce0 = grp_search_fu_247_this_triedMask_ce0;
    end else begin
        searcher_triedMask_ce0 = searcher_triedMask_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | ((strm_in_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state7)))) begin
        searcher_triedMask_ce0_local = 1'b1;
    end else begin
        searcher_triedMask_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state9))) begin
        searcher_triedMask_d0 = grp_search_fu_247_this_triedMask_d0;
    end else begin
        searcher_triedMask_d0 = 49'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state9))) begin
        searcher_triedMask_we0 = grp_search_fu_247_this_triedMask_we0;
    end else begin
        searcher_triedMask_we0 = (searcher_triedMask_we0_out | 1'b0);
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | ((strm_in_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state7)))) begin
        searcher_triedMask_we0_local = 1'b1;
    end else begin
        searcher_triedMask_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state9))) begin
        searcher_visitCounts_address0 = grp_search_fu_247_this_visitCounts_address0;
    end else begin
        searcher_visitCounts_address0 = searcher_visitCounts_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        searcher_visitCounts_address0_local = this_visitCounts_addr_reg_340;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        searcher_visitCounts_address0_local = 64'd0;
    end else begin
        searcher_visitCounts_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state9))) begin
        searcher_visitCounts_ce0 = grp_search_fu_247_this_visitCounts_ce0;
    end else begin
        searcher_visitCounts_ce0 = searcher_visitCounts_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | ((strm_in_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state7)))) begin
        searcher_visitCounts_ce0_local = 1'b1;
    end else begin
        searcher_visitCounts_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state9))) begin
        searcher_visitCounts_d0 = grp_search_fu_247_this_visitCounts_d0;
    end else begin
        searcher_visitCounts_d0 = 32'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state9))) begin
        searcher_visitCounts_we0 = grp_search_fu_247_this_visitCounts_we0;
    end else begin
        searcher_visitCounts_we0 = (searcher_visitCounts_we0_out | 1'b0);
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | ((strm_in_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state7)))) begin
        searcher_visitCounts_we0_local = 1'b1;
    end else begin
        searcher_visitCounts_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        strm_in_blk_n = strm_in_empty_n;
    end else begin
        strm_in_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((strm_in_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state8)) | ((strm_in_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state7)) | ((strm_in_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state6)) | ((strm_in_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state5)))) begin
        strm_in_read = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        strm_in_read = grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_strm_in_read;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        strm_in_read = grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_strm_in_read;
    end else begin
        strm_in_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        strm_out_blk_n = strm_out_full_n;
    end else begin
        strm_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((strm_out_full_n == 1'b0) | (grp_search_fu_247_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state12))) begin
        strm_out_write = 1'b1;
    end else begin
        strm_out_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((strm_in_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((strm_in_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((strm_in_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((strm_in_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((grp_search_fu_247_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if ((~((strm_out_full_n == 1'b0) | (grp_search_fu_247_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_ap_start = grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_ap_start_reg;

assign grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_ap_start = grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_ap_start_reg;

assign grp_fu_277_p2 = ((strm_in_dout != 32'd0) ? 1'b1 : 1'b0);

assign grp_search_fu_247_ap_start = grp_search_fu_247_ap_start_reg;

assign last_move_fu_291_p2 = ($signed(strm_in_dout) + $signed(32'd4294967295));

assign searcher_firstChilds_we0_out = searcher_firstChilds_we0_local;

assign searcher_logVisitCounts_we0_out = searcher_logVisitCounts_we0_local;

assign searcher_meanQ_we0_out = searcher_meanQ_we0_local;

assign searcher_numChildren_we0_out = searcher_numChildren_we0_local;

assign searcher_parents_we0_out = searcher_parents_we0_local;

assign searcher_terminals_we0_out = searcher_terminals_we0_local;

assign searcher_triedMask_we0_out = searcher_triedMask_we0_local;

assign searcher_visitCounts_we0_out = searcher_visitCounts_we0_local;

assign strm_out_din = grp_search_fu_247_ap_return;

assign this_firstChilds_addr_reg_330 = 64'd0;

assign this_logVisitCounts_addr_reg_360 = 64'd0;

assign this_meanQ_addr_reg_345 = 64'd0;

assign this_numChildren_addr_reg_335 = 64'd0;

assign this_parents_addr_reg_325 = 64'd0;

assign this_terminals_addr_reg_350 = 64'd0;

assign this_triedMask_addr_reg_355 = 64'd0;

assign this_visitCounts_addr_reg_340 = 64'd0;

endmodule //dut
