

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "47", "81"],
		"CDFG" : "dut",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "strm_in", "Type" : "Fifo", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "strm_in_blk_n", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "13", "SubInstance" : "grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233", "Port" : "strm_in", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "47", "SubInstance" : "grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240", "Port" : "strm_in", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "strm_out", "Type" : "Fifo", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "strm_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "log_apfixed_reduce_log_inverse_lut_table_array", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "81", "SubInstance" : "grp_search_fu_247", "Port" : "log_apfixed_reduce_log_inverse_lut_table_array", "Inst_start_state" : "11", "Inst_end_state" : "12"}]},
			{"Name" : "log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "81", "SubInstance" : "grp_search_fu_247", "Port" : "log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array", "Inst_start_state" : "11", "Inst_end_state" : "12"}]},
			{"Name" : "log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "81", "SubInstance" : "grp_search_fu_247", "Port" : "log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array", "Inst_start_state" : "11", "Inst_end_state" : "12"}]}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.searcher_visitCounts_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.searcher_meanQ_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.searcher_parents_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.searcher_firstChilds_U", "Parent" : "0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.searcher_numChildren_U", "Parent" : "0"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.searcher_nextSiblings_U", "Parent" : "0"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.searcher_numLegalActions_U", "Parent" : "0"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.searcher_terminals_U", "Parent" : "0"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.searcher_childActions_U", "Parent" : "0"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.searcher_triedMask_U", "Parent" : "0"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.searcher_isREDs_U", "Parent" : "0"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.searcher_logVisitCounts_U", "Parent" : "0"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233", "Parent" : "0", "Child" : ["14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46"],
		"CDFG" : "dut_Pipeline_VITIS_LOOP_17_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "10", "EstimateLatencyMax" : "10",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "strm_in", "Type" : "Fifo", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "strm_in_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "player1_48_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_17_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "4", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "14", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233.bitset_49ns_49ns_6ns_1ns_49_1_1_U1", "Parent" : "13"},
	{"ID" : "15", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233.bitset_49ns_49ns_6ns_1ns_49_1_1_U2", "Parent" : "13"},
	{"ID" : "16", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233.bitset_49ns_49ns_6ns_1ns_49_1_1_U3", "Parent" : "13"},
	{"ID" : "17", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233.bitset_49ns_49ns_6ns_1ns_49_1_1_U4", "Parent" : "13"},
	{"ID" : "18", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233.bitset_49ns_49ns_6ns_1ns_49_1_1_U5", "Parent" : "13"},
	{"ID" : "19", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233.bitset_49ns_49ns_6ns_1ns_49_1_1_U6", "Parent" : "13"},
	{"ID" : "20", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233.bitset_49ns_49ns_6ns_1ns_49_1_1_U7", "Parent" : "13"},
	{"ID" : "21", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233.bitset_49ns_49ns_6ns_1ns_49_1_1_U8", "Parent" : "13"},
	{"ID" : "22", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233.bitset_49ns_49ns_6ns_1ns_49_1_1_U9", "Parent" : "13"},
	{"ID" : "23", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233.bitset_49ns_49ns_6ns_1ns_49_1_1_U10", "Parent" : "13"},
	{"ID" : "24", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233.bitset_49ns_49ns_6ns_1ns_49_1_1_U11", "Parent" : "13"},
	{"ID" : "25", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233.bitset_49ns_49ns_6ns_1ns_49_1_1_U12", "Parent" : "13"},
	{"ID" : "26", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233.bitset_49ns_49ns_6ns_1ns_49_1_1_U13", "Parent" : "13"},
	{"ID" : "27", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233.bitset_49ns_49ns_6ns_1ns_49_1_1_U14", "Parent" : "13"},
	{"ID" : "28", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233.bitset_49ns_49ns_6ns_1ns_49_1_1_U15", "Parent" : "13"},
	{"ID" : "29", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233.bitset_49ns_49ns_6ns_1ns_49_1_1_U16", "Parent" : "13"},
	{"ID" : "30", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233.bitset_49ns_49ns_6ns_1ns_49_1_1_U17", "Parent" : "13"},
	{"ID" : "31", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233.bitset_49ns_49ns_6ns_1ns_49_1_1_U18", "Parent" : "13"},
	{"ID" : "32", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233.bitset_49ns_49ns_6ns_1ns_49_1_1_U19", "Parent" : "13"},
	{"ID" : "33", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233.bitset_49ns_49ns_6ns_1ns_49_1_1_U20", "Parent" : "13"},
	{"ID" : "34", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233.bitset_49ns_49ns_6ns_1ns_49_1_1_U21", "Parent" : "13"},
	{"ID" : "35", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233.bitset_49ns_49ns_6ns_1ns_49_1_1_U22", "Parent" : "13"},
	{"ID" : "36", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233.bitset_49ns_49ns_6ns_1ns_49_1_1_U23", "Parent" : "13"},
	{"ID" : "37", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233.bitset_49ns_49ns_6ns_1ns_49_1_1_U24", "Parent" : "13"},
	{"ID" : "38", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233.bitset_49ns_49ns_6ns_1ns_49_1_1_U25", "Parent" : "13"},
	{"ID" : "39", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233.bitset_49ns_49ns_6ns_1ns_49_1_1_U26", "Parent" : "13"},
	{"ID" : "40", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233.bitset_49ns_49ns_6ns_1ns_49_1_1_U27", "Parent" : "13"},
	{"ID" : "41", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233.bitset_49ns_49ns_6ns_1ns_49_1_1_U28", "Parent" : "13"},
	{"ID" : "42", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233.bitset_49ns_49ns_6ns_1ns_49_1_1_U29", "Parent" : "13"},
	{"ID" : "43", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233.bitset_49ns_49ns_6ns_1ns_49_1_1_U30", "Parent" : "13"},
	{"ID" : "44", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233.bitset_49ns_49ns_6ns_1ns_49_1_1_U31", "Parent" : "13"},
	{"ID" : "45", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233.bitset_49ns_49ns_6ns_1ns_49_1_1_U32", "Parent" : "13"},
	{"ID" : "46", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233.flow_control_loop_pipe_sequential_init_U", "Parent" : "13"},
	{"ID" : "47", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240", "Parent" : "0", "Child" : ["48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80"],
		"CDFG" : "dut_Pipeline_VITIS_LOOP_27_3",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "10", "EstimateLatencyMax" : "10",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "strm_in", "Type" : "Fifo", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "strm_in_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "player2_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_27_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "4", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "48", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240.bitset_49ns_49ns_6ns_1ns_49_1_1_U36", "Parent" : "47"},
	{"ID" : "49", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240.bitset_49ns_49ns_6ns_1ns_49_1_1_U37", "Parent" : "47"},
	{"ID" : "50", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240.bitset_49ns_49ns_6ns_1ns_49_1_1_U38", "Parent" : "47"},
	{"ID" : "51", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240.bitset_49ns_49ns_6ns_1ns_49_1_1_U39", "Parent" : "47"},
	{"ID" : "52", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240.bitset_49ns_49ns_6ns_1ns_49_1_1_U40", "Parent" : "47"},
	{"ID" : "53", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240.bitset_49ns_49ns_6ns_1ns_49_1_1_U41", "Parent" : "47"},
	{"ID" : "54", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240.bitset_49ns_49ns_6ns_1ns_49_1_1_U42", "Parent" : "47"},
	{"ID" : "55", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240.bitset_49ns_49ns_6ns_1ns_49_1_1_U43", "Parent" : "47"},
	{"ID" : "56", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240.bitset_49ns_49ns_6ns_1ns_49_1_1_U44", "Parent" : "47"},
	{"ID" : "57", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240.bitset_49ns_49ns_6ns_1ns_49_1_1_U45", "Parent" : "47"},
	{"ID" : "58", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240.bitset_49ns_49ns_6ns_1ns_49_1_1_U46", "Parent" : "47"},
	{"ID" : "59", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240.bitset_49ns_49ns_6ns_1ns_49_1_1_U47", "Parent" : "47"},
	{"ID" : "60", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240.bitset_49ns_49ns_6ns_1ns_49_1_1_U48", "Parent" : "47"},
	{"ID" : "61", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240.bitset_49ns_49ns_6ns_1ns_49_1_1_U49", "Parent" : "47"},
	{"ID" : "62", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240.bitset_49ns_49ns_6ns_1ns_49_1_1_U50", "Parent" : "47"},
	{"ID" : "63", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240.bitset_49ns_49ns_6ns_1ns_49_1_1_U51", "Parent" : "47"},
	{"ID" : "64", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240.bitset_49ns_49ns_6ns_1ns_49_1_1_U52", "Parent" : "47"},
	{"ID" : "65", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240.bitset_49ns_49ns_6ns_1ns_49_1_1_U53", "Parent" : "47"},
	{"ID" : "66", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240.bitset_49ns_49ns_6ns_1ns_49_1_1_U54", "Parent" : "47"},
	{"ID" : "67", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240.bitset_49ns_49ns_6ns_1ns_49_1_1_U55", "Parent" : "47"},
	{"ID" : "68", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240.bitset_49ns_49ns_6ns_1ns_49_1_1_U56", "Parent" : "47"},
	{"ID" : "69", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240.bitset_49ns_49ns_6ns_1ns_49_1_1_U57", "Parent" : "47"},
	{"ID" : "70", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240.bitset_49ns_49ns_6ns_1ns_49_1_1_U58", "Parent" : "47"},
	{"ID" : "71", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240.bitset_49ns_49ns_6ns_1ns_49_1_1_U59", "Parent" : "47"},
	{"ID" : "72", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240.bitset_49ns_49ns_6ns_1ns_49_1_1_U60", "Parent" : "47"},
	{"ID" : "73", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240.bitset_49ns_49ns_6ns_1ns_49_1_1_U61", "Parent" : "47"},
	{"ID" : "74", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240.bitset_49ns_49ns_6ns_1ns_49_1_1_U62", "Parent" : "47"},
	{"ID" : "75", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240.bitset_49ns_49ns_6ns_1ns_49_1_1_U63", "Parent" : "47"},
	{"ID" : "76", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240.bitset_49ns_49ns_6ns_1ns_49_1_1_U64", "Parent" : "47"},
	{"ID" : "77", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240.bitset_49ns_49ns_6ns_1ns_49_1_1_U65", "Parent" : "47"},
	{"ID" : "78", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240.bitset_49ns_49ns_6ns_1ns_49_1_1_U66", "Parent" : "47"},
	{"ID" : "79", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240.bitset_49ns_49ns_6ns_1ns_49_1_1_U67", "Parent" : "47"},
	{"ID" : "80", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240.flow_control_loop_pipe_sequential_init_U", "Parent" : "47"},
	{"ID" : "81", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247", "Parent" : "0", "Child" : ["82", "85", "129"],
		"CDFG" : "search",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "this_visitCounts", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "85", "SubInstance" : "grp_forward_fu_214", "Port" : "this_visitCounts", "Inst_start_state" : "4", "Inst_end_state" : "5"},
					{"ID" : "129", "SubInstance" : "grp_search_Pipeline_VITIS_LOOP_27_1_fu_255", "Port" : "this_visitCounts", "Inst_start_state" : "6", "Inst_end_state" : "7"}]},
			{"Name" : "this_meanQ", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "85", "SubInstance" : "grp_forward_fu_214", "Port" : "this_meanQ", "Inst_start_state" : "4", "Inst_end_state" : "5"}]},
			{"Name" : "this_parents", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "85", "SubInstance" : "grp_forward_fu_214", "Port" : "this_parents", "Inst_start_state" : "4", "Inst_end_state" : "5"}]},
			{"Name" : "this_firstChilds", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "85", "SubInstance" : "grp_forward_fu_214", "Port" : "this_firstChilds", "Inst_start_state" : "4", "Inst_end_state" : "5"}]},
			{"Name" : "this_numChildren", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "85", "SubInstance" : "grp_forward_fu_214", "Port" : "this_numChildren", "Inst_start_state" : "4", "Inst_end_state" : "5"}]},
			{"Name" : "this_nextSiblings", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "85", "SubInstance" : "grp_forward_fu_214", "Port" : "this_nextSiblings", "Inst_start_state" : "4", "Inst_end_state" : "5"},
					{"ID" : "129", "SubInstance" : "grp_search_Pipeline_VITIS_LOOP_27_1_fu_255", "Port" : "this_nextSiblings", "Inst_start_state" : "6", "Inst_end_state" : "7"}]},
			{"Name" : "this_numLegalActions", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "85", "SubInstance" : "grp_forward_fu_214", "Port" : "this_numLegalActions", "Inst_start_state" : "4", "Inst_end_state" : "5"}]},
			{"Name" : "this_terminals", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "85", "SubInstance" : "grp_forward_fu_214", "Port" : "this_terminals", "Inst_start_state" : "4", "Inst_end_state" : "5"}]},
			{"Name" : "this_childActions", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "85", "SubInstance" : "grp_forward_fu_214", "Port" : "this_childActions", "Inst_start_state" : "4", "Inst_end_state" : "5"}]},
			{"Name" : "this_triedMask", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "85", "SubInstance" : "grp_forward_fu_214", "Port" : "this_triedMask", "Inst_start_state" : "4", "Inst_end_state" : "5"}]},
			{"Name" : "this_isREDs", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "85", "SubInstance" : "grp_forward_fu_214", "Port" : "this_isREDs", "Inst_start_state" : "4", "Inst_end_state" : "5"}]},
			{"Name" : "this_logVisitCounts", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "85", "SubInstance" : "grp_forward_fu_214", "Port" : "this_logVisitCounts", "Inst_start_state" : "4", "Inst_end_state" : "5"}]},
			{"Name" : "this_rng_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "boardState_isPlayer1Turn_s", "Type" : "None", "Direction" : "I"},
			{"Name" : "boardState_lastMove_s", "Type" : "None", "Direction" : "I"},
			{"Name" : "boardState_player1_s", "Type" : "None", "Direction" : "I"},
			{"Name" : "boardState_player2_s", "Type" : "None", "Direction" : "I"},
			{"Name" : "isRED", "Type" : "None", "Direction" : "I"},
			{"Name" : "log_apfixed_reduce_log_inverse_lut_table_array", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "85", "SubInstance" : "grp_forward_fu_214", "Port" : "log_apfixed_reduce_log_inverse_lut_table_array", "Inst_start_state" : "4", "Inst_end_state" : "5"}]},
			{"Name" : "log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "85", "SubInstance" : "grp_forward_fu_214", "Port" : "log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array", "Inst_start_state" : "4", "Inst_end_state" : "5"}]},
			{"Name" : "log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "85", "SubInstance" : "grp_forward_fu_214", "Port" : "log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array", "Inst_start_state" : "4", "Inst_end_state" : "5"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_46_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "9", "FirstState" : "ap_ST_fsm_state4", "LastState" : ["ap_ST_fsm_state5"], "QuitState" : ["ap_ST_fsm_state4"], "PreState" : ["ap_ST_fsm_state3"], "PostState" : ["ap_ST_fsm_state6"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "82", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_search_Pipeline_VITIS_LOOP_42_1_fu_208", "Parent" : "81", "Child" : ["83", "84"],
		"CDFG" : "search_Pipeline_VITIS_LOOP_42_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "51", "EstimateLatencyMax" : "51",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gameState_legalActionMap", "Type" : "None", "Direction" : "I"},
			{"Name" : "numLegalActions_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_42_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "83", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_search_Pipeline_VITIS_LOOP_42_1_fu_208.bitselect_1ns_49ns_6ns_1_1_1_U70", "Parent" : "82"},
	{"ID" : "84", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_search_Pipeline_VITIS_LOOP_42_1_fu_208.flow_control_loop_pipe_sequential_init_U", "Parent" : "82"},
	{"ID" : "85", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214", "Parent" : "81", "Child" : ["86", "91", "94", "96", "98", "111", "113", "115"],
		"CDFG" : "forward",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "this_visitCounts", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "86", "SubInstance" : "grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714", "Port" : "this_visitCounts", "Inst_start_state" : "5", "Inst_end_state" : "6"},
					{"ID" : "115", "SubInstance" : "grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784", "Port" : "this_visitCounts", "Inst_start_state" : "23", "Inst_end_state" : "28"}]},
			{"Name" : "this_meanQ", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "86", "SubInstance" : "grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714", "Port" : "this_meanQ", "Inst_start_state" : "5", "Inst_end_state" : "6"},
					{"ID" : "115", "SubInstance" : "grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784", "Port" : "this_meanQ", "Inst_start_state" : "23", "Inst_end_state" : "28"}]},
			{"Name" : "this_parents", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "115", "SubInstance" : "grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784", "Port" : "this_parents", "Inst_start_state" : "23", "Inst_end_state" : "28"}]},
			{"Name" : "this_firstChilds", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "this_numChildren", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "this_nextSiblings", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "86", "SubInstance" : "grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714", "Port" : "this_nextSiblings", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "this_numLegalActions", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "this_terminals", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "this_childActions", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "this_triedMask", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "this_isREDs", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "115", "SubInstance" : "grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784", "Port" : "this_isREDs", "Inst_start_state" : "23", "Inst_end_state" : "28"}]},
			{"Name" : "this_logVisitCounts", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "115", "SubInstance" : "grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784", "Port" : "this_logVisitCounts", "Inst_start_state" : "23", "Inst_end_state" : "28"}]},
			{"Name" : "this_nextFree_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "this_rng_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "gameState_legalActionMap", "Type" : "None", "Direction" : "I"},
			{"Name" : "gameState_hexGame_isPlayer1Turn_s", "Type" : "None", "Direction" : "I"},
			{"Name" : "gameState_hexGame_lastMove_s", "Type" : "None", "Direction" : "I"},
			{"Name" : "gameState_hexGame_player1_s", "Type" : "None", "Direction" : "I"},
			{"Name" : "gameState_hexGame_player2_s", "Type" : "None", "Direction" : "I"},
			{"Name" : "log_apfixed_reduce_log_inverse_lut_table_array", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "115", "SubInstance" : "grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784", "Port" : "log_apfixed_reduce_log_inverse_lut_table_array", "Inst_start_state" : "23", "Inst_end_state" : "28"}]},
			{"Name" : "log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "115", "SubInstance" : "grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784", "Port" : "log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array", "Inst_start_state" : "23", "Inst_end_state" : "28"}]},
			{"Name" : "log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "115", "SubInstance" : "grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784", "Port" : "log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array", "Inst_start_state" : "23", "Inst_end_state" : "28"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_127_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "28", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state8"], "QuitState" : ["ap_ST_fsm_state3", "ap_ST_fsm_state4"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state9", "ap_ST_fsm_state13", "ap_ST_fsm_state16"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "86", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714", "Parent" : "85", "Child" : ["87", "88", "89", "90"],
		"CDFG" : "forward_Pipeline_VITIS_LOOP_140_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "bestChildNode_7", "Type" : "None", "Direction" : "I"},
			{"Name" : "this_meanQ", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "this_visitCounts", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "logVisitCount", "Type" : "None", "Direction" : "I"},
			{"Name" : "this_nextSiblings", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bestChildNode_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_140_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter48", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter48", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "87", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714.grp_sqrt_fixed_32_16_s_fu_118", "Parent" : "86",
		"CDFG" : "sqrt_fixed_32_16_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "0", "ap_start" : "0", "ap_ready" : "0", "ap_done" : "0", "ap_continue" : "0", "ap_idle" : "0", "real_start" : "0",
		"Pipeline" : "Aligned", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "6", "EstimateLatencyMin" : "6", "EstimateLatencyMax" : "6",
		"Combinational" : "0",
		"Datapath" : "1",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "x", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "88", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714.sdiv_32ns_32ns_32_36_1_U75", "Parent" : "86"},
	{"ID" : "89", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714.mac_muladd_24ns_16ns_36s_41_4_1_U76", "Parent" : "86"},
	{"ID" : "90", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_forward_Pipeline_VITIS_LOOP_140_2_fu_714.flow_control_loop_pipe_sequential_init_U", "Parent" : "86"},
	{"ID" : "91", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_forward_Pipeline_VITIS_LOOP_73_1_fu_729", "Parent" : "85", "Child" : ["92", "93"],
		"CDFG" : "forward_Pipeline_VITIS_LOOP_73_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "2", "EstimateLatencyMax" : "51",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "untried", "Type" : "None", "Direction" : "I"},
			{"Name" : "action_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_73_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state1", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state1_blk", "QuitState" : "ap_ST_fsm_state1", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state1_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "92", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_forward_Pipeline_VITIS_LOOP_73_1_fu_729.bitselect_1ns_49ns_6ns_1_1_1_U85", "Parent" : "91"},
	{"ID" : "93", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_forward_Pipeline_VITIS_LOOP_73_1_fu_729.flow_control_loop_pipe_sequential_init_U", "Parent" : "91"},
	{"ID" : "94", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_forward_Pipeline_VITIS_LOOP_114_14_fu_735", "Parent" : "85", "Child" : ["95"],
		"CDFG" : "forward_Pipeline_VITIS_LOOP_114_14",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "fill_10", "Type" : "None", "Direction" : "I"},
			{"Name" : "gameState_hexGame_player2_7", "Type" : "None", "Direction" : "I"},
			{"Name" : "prev_8_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out1", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_114_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "95", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_forward_Pipeline_VITIS_LOOP_114_14_fu_735.flow_control_loop_pipe_sequential_init_U", "Parent" : "94"},
	{"ID" : "96", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_forward_Pipeline_VITIS_LOOP_114_1_fu_744", "Parent" : "85", "Child" : ["97"],
		"CDFG" : "forward_Pipeline_VITIS_LOOP_114_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "fill_9", "Type" : "None", "Direction" : "I"},
			{"Name" : "gameState_hexGame_player1_7", "Type" : "None", "Direction" : "I"},
			{"Name" : "prev_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_114_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state1", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state1_blk", "QuitState" : "ap_ST_fsm_state1", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state1_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "97", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_forward_Pipeline_VITIS_LOOP_114_1_fu_744.flow_control_loop_pipe_sequential_init_U", "Parent" : "96"},
	{"ID" : "98", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_rollout_fu_751", "Parent" : "85", "Child" : ["99", "101", "103", "105", "107", "110"],
		"CDFG" : "rollout",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "this_rng_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "gameState_legalActionMap", "Type" : "None", "Direction" : "I"},
			{"Name" : "gameState_hexGame_isPlayer1Turn_s", "Type" : "None", "Direction" : "I"},
			{"Name" : "gameState_hexGame_lastMove_s", "Type" : "None", "Direction" : "I"},
			{"Name" : "gameState_hexGame_player1_s", "Type" : "None", "Direction" : "I"},
			{"Name" : "gameState_hexGame_player2_s", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_200_2", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "78", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state78"], "QuitState" : ["ap_ST_fsm_state4"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state6", "ap_ST_fsm_state8"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "99", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_rollout_fu_751.grp_rollout_Pipeline_VITIS_LOOP_114_1_fu_300", "Parent" : "98", "Child" : ["100"],
		"CDFG" : "rollout_Pipeline_VITIS_LOOP_114_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "fill_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "gameState_hexGame_player1_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "prev_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_114_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state1", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state1_blk", "QuitState" : "ap_ST_fsm_state1", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state1_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "100", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_rollout_fu_751.grp_rollout_Pipeline_VITIS_LOOP_114_1_fu_300.flow_control_loop_pipe_sequential_init_U", "Parent" : "99"},
	{"ID" : "101", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_rollout_fu_751.grp_rollout_Pipeline_VITIS_LOOP_114_11_fu_307", "Parent" : "98", "Child" : ["102"],
		"CDFG" : "rollout_Pipeline_VITIS_LOOP_114_11",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "fill_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "gameState_hexGame_player2_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "prev_3_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out1", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_114_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "102", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_rollout_fu_751.grp_rollout_Pipeline_VITIS_LOOP_114_11_fu_307.flow_control_loop_pipe_sequential_init_U", "Parent" : "101"},
	{"ID" : "103", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_rollout_fu_751.grp_rollout_Pipeline_VITIS_LOOP_114_12_fu_316", "Parent" : "98", "Child" : ["104"],
		"CDFG" : "rollout_Pipeline_VITIS_LOOP_114_12",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "connected", "Type" : "None", "Direction" : "I"},
			{"Name" : "gameState_hexGame_player1_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "prev_4_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_114_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state1", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state1_blk", "QuitState" : "ap_ST_fsm_state1", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state1_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "104", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_rollout_fu_751.grp_rollout_Pipeline_VITIS_LOOP_114_12_fu_316.flow_control_loop_pipe_sequential_init_U", "Parent" : "103"},
	{"ID" : "105", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_rollout_fu_751.grp_rollout_Pipeline_VITIS_LOOP_114_13_fu_323", "Parent" : "98", "Child" : ["106"],
		"CDFG" : "rollout_Pipeline_VITIS_LOOP_114_13",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "connected_6", "Type" : "None", "Direction" : "I"},
			{"Name" : "gameState_hexGame_player2_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "prev_5_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out1", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_114_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "106", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_rollout_fu_751.grp_rollout_Pipeline_VITIS_LOOP_114_13_fu_323.flow_control_loop_pipe_sequential_init_U", "Parent" : "105"},
	{"ID" : "107", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_rollout_fu_751.grp_rollout_Pipeline_VITIS_LOOP_230_3_fu_332", "Parent" : "98", "Child" : ["108", "109"],
		"CDFG" : "rollout_Pipeline_VITIS_LOOP_230_3",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "2", "EstimateLatencyMax" : "50",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gameState_legalActionMap_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"},
			{"Name" : "action_2_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_230_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "108", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_rollout_fu_751.grp_rollout_Pipeline_VITIS_LOOP_230_3_fu_332.bitselect_1ns_49ns_6ns_1_1_1_U112", "Parent" : "107"},
	{"ID" : "109", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_rollout_fu_751.grp_rollout_Pipeline_VITIS_LOOP_230_3_fu_332.flow_control_loop_pipe_sequential_init_U", "Parent" : "107"},
	{"ID" : "110", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_rollout_fu_751.urem_64ns_64ns_32_68_seq_1_U116", "Parent" : "98"},
	{"ID" : "111", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_forward_Pipeline_VITIS_LOOP_114_15_fu_766", "Parent" : "85", "Child" : ["112"],
		"CDFG" : "forward_Pipeline_VITIS_LOOP_114_15",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "connected", "Type" : "None", "Direction" : "I"},
			{"Name" : "gameState_hexGame_player1_8", "Type" : "None", "Direction" : "I"},
			{"Name" : "prev_9_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_114_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state1", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state1_blk", "QuitState" : "ap_ST_fsm_state1", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state1_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "112", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_forward_Pipeline_VITIS_LOOP_114_15_fu_766.flow_control_loop_pipe_sequential_init_U", "Parent" : "111"},
	{"ID" : "113", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_forward_Pipeline_VITIS_LOOP_114_16_fu_774", "Parent" : "85", "Child" : ["114"],
		"CDFG" : "forward_Pipeline_VITIS_LOOP_114_16",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "connected_12", "Type" : "None", "Direction" : "I"},
			{"Name" : "gameState_hexGame_player2_8", "Type" : "None", "Direction" : "I"},
			{"Name" : "prev_10_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out1", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_114_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "114", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_forward_Pipeline_VITIS_LOOP_114_16_fu_774.flow_control_loop_pipe_sequential_init_U", "Parent" : "113"},
	{"ID" : "115", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784", "Parent" : "85", "Child" : ["116", "124", "125", "126", "127", "128"],
		"CDFG" : "forward_Pipeline_VITIS_LOOP_259_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "node_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "reward_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "this_visitCounts", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "zext_ln125", "Type" : "None", "Direction" : "I"},
			{"Name" : "this_meanQ", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "visitCount_cast3", "Type" : "None", "Direction" : "I"},
			{"Name" : "this_logVisitCounts", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "this_parents", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "this_isREDs", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "conv7_i_i159_i", "Type" : "None", "Direction" : "I"},
			{"Name" : "log_apfixed_reduce_log_inverse_lut_table_array", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "116", "SubInstance" : "grp_log_32_16_s_fu_182", "Port" : "log_apfixed_reduce_log_inverse_lut_table_array", "Inst_start_state" : "2", "Inst_end_state" : "7"}]},
			{"Name" : "log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "116", "SubInstance" : "grp_log_32_16_s_fu_182", "Port" : "log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array", "Inst_start_state" : "2", "Inst_end_state" : "7"}]},
			{"Name" : "log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "116", "SubInstance" : "grp_log_32_16_s_fu_182", "Port" : "log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array", "Inst_start_state" : "2", "Inst_end_state" : "7"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_259_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "30", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage22", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage22_subdone", "QuitState" : "ap_ST_fsm_pp0_stage22", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage22_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "116", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784.grp_log_32_16_s_fu_182", "Parent" : "115", "Child" : ["117", "118", "119", "120", "121", "122", "123"],
		"CDFG" : "log_32_16_s",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "0", "ap_start" : "0", "ap_ready" : "0", "ap_done" : "0", "ap_continue" : "0", "ap_idle" : "0", "real_start" : "0",
		"Pipeline" : "Aligned", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "4", "EstimateLatencyMin" : "4", "EstimateLatencyMax" : "4",
		"Combinational" : "0",
		"Datapath" : "1",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "x", "Type" : "None", "Direction" : "I"},
			{"Name" : "log_apfixed_reduce_log_inverse_lut_table_array", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array", "Type" : "Memory", "Direction" : "I"}]},
	{"ID" : "117", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784.grp_log_32_16_s_fu_182.log_apfixed_reduce_log_inverse_lut_table_array_U", "Parent" : "116"},
	{"ID" : "118", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784.grp_log_32_16_s_fu_182.log_apfixed_reduce_log0_lut_table_ap_fixed_0_5_64_array_U", "Parent" : "116"},
	{"ID" : "119", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784.grp_log_32_16_s_fu_182.log_apfixed_reduce_log_lut_table_ap_fixed_4_4_16_array_U", "Parent" : "116"},
	{"ID" : "120", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784.grp_log_32_16_s_fu_182.mul_36ns_6ns_42_1_1_U132", "Parent" : "116"},
	{"ID" : "121", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784.grp_log_32_16_s_fu_182.mul_6s_23ns_27_1_1_U133", "Parent" : "116"},
	{"ID" : "122", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784.grp_log_32_16_s_fu_182.mul_9ns_9ns_18_1_1_U134", "Parent" : "116"},
	{"ID" : "123", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784.grp_log_32_16_s_fu_182.mac_mulsub_24ns_4ns_29ns_29_4_1_U135", "Parent" : "116"},
	{"ID" : "124", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784.sdiv_20ns_4ns_20_24_1_U144", "Parent" : "115"},
	{"ID" : "125", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784.mul_20s_3ns_20_1_1_U145", "Parent" : "115"},
	{"ID" : "126", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784.sdiv_24s_32ns_20_28_1_U146", "Parent" : "115"},
	{"ID" : "127", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784.mac_mulsub_20s_3ns_20s_23_4_1_U147", "Parent" : "115"},
	{"ID" : "128", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_forward_fu_214.grp_forward_Pipeline_VITIS_LOOP_259_1_fu_784.flow_control_loop_pipe_sequential_init_U", "Parent" : "115"},
	{"ID" : "129", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_search_Pipeline_VITIS_LOOP_27_1_fu_255", "Parent" : "81", "Child" : ["130"],
		"CDFG" : "search_Pipeline_VITIS_LOOP_27_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "bestChildNode_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "this_visitCounts", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "this_nextSiblings", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bestChildNode_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_27_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "130", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_search_fu_247.grp_search_Pipeline_VITIS_LOOP_27_1_fu_255.flow_control_loop_pipe_sequential_init_U", "Parent" : "129"}]}
