// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module dut_rollout_Pipeline_VITIS_LOOP_114_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        fill_4,
        gameState_hexGame_player1_2,
        prev_out,
        prev_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [48:0] fill_4;
input  [48:0] gameState_hexGame_player1_2;
output  [48:0] prev_out;
output   prev_out_ap_vld;

reg ap_idle;
reg prev_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln125_fu_500_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [48:0] prev_reg_121;
wire   [48:0] or_ln123_11_fu_494_p2;
reg   [48:0] ap_phi_mux_prev_phi_fu_124_p4;
wire    ap_loop_init;
wire   [5:0] tmp_96_fu_142_p4;
wire   [5:0] tmp_97_fu_152_p4;
wire   [5:0] tmp_98_fu_162_p4;
wire   [5:0] tmp_99_fu_172_p4;
wire   [5:0] tmp_100_fu_182_p4;
wire   [40:0] tmp_109_fu_286_p4;
wire   [40:0] tmp_108_fu_262_p11;
wire   [5:0] tmp_s_fu_132_p4;
wire   [0:0] tmp_fu_302_p3;
wire   [40:0] or_ln123_8_fu_296_p2;
wire   [40:0] trunc_ln123_fu_320_p1;
wire   [47:0] shl_ln123_1_fu_324_p3;
wire   [47:0] or_ln123_6_fu_310_p4;
wire   [0:0] tmp_110_fu_338_p3;
wire   [47:0] or_ln123_7_fu_332_p2;
wire   [4:0] tmp_106_fu_242_p4;
wire   [5:0] tmp_101_fu_192_p4;
wire   [5:0] tmp_102_fu_202_p4;
wire   [5:0] tmp_103_fu_212_p4;
wire   [5:0] tmp_104_fu_222_p4;
wire   [5:0] tmp_105_fu_232_p4;
wire   [40:0] tmp_111_fu_380_p13;
wire   [40:0] and_ln123_2_fu_354_p12;
wire   [5:0] tmp_107_fu_252_p4;
wire   [0:0] tmp_112_fu_414_p3;
wire   [40:0] or_ln123_fu_408_p2;
wire   [5:0] trunc_ln123_4_fu_432_p1;
wire   [47:0] and_ln123_3_fu_436_p15;
wire   [47:0] tmp9_fu_422_p4;
wire   [47:0] or_ln123_9_fu_468_p2;
wire   [48:0] tmp11_fu_474_p3;
wire   [48:0] tmp7_fu_346_p3;
wire   [48:0] or_ln123_10_fu_482_p2;
wire   [48:0] and_ln123_fu_488_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

dut_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln125_fu_500_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        prev_reg_121 <= or_ln123_11_fu_494_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln125_fu_500_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_phi_mux_prev_phi_fu_124_p4 = fill_4;
    end else begin
        ap_phi_mux_prev_phi_fu_124_p4 = prev_reg_121;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln125_fu_500_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        prev_out_ap_vld = 1'b1;
    end else begin
        prev_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign and_ln123_2_fu_354_p12 = {{{{{{{{{{{tmp_s_fu_132_p4}, {1'd0}}, {tmp_96_fu_142_p4}}, {1'd0}}, {tmp_97_fu_152_p4}}, {1'd0}}, {tmp_98_fu_162_p4}}, {1'd0}}, {tmp_99_fu_172_p4}}, {1'd0}}, {tmp_100_fu_182_p4}};

assign and_ln123_3_fu_436_p15 = {{{{{{{{{{{{{{tmp_106_fu_242_p4}, {1'd0}}, {tmp_101_fu_192_p4}}, {1'd0}}, {tmp_102_fu_202_p4}}, {1'd0}}, {tmp_103_fu_212_p4}}, {1'd0}}, {tmp_104_fu_222_p4}}, {1'd0}}, {tmp_105_fu_232_p4}}, {1'd0}}, {trunc_ln123_4_fu_432_p1}}, {1'd0}};

assign and_ln123_fu_488_p2 = (or_ln123_10_fu_482_p2 & gameState_hexGame_player1_2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln125_fu_500_p2 = ((or_ln123_11_fu_494_p2 == ap_phi_mux_prev_phi_fu_124_p4) ? 1'b1 : 1'b0);

assign or_ln123_10_fu_482_p2 = (tmp7_fu_346_p3 | tmp11_fu_474_p3);

assign or_ln123_11_fu_494_p2 = (ap_phi_mux_prev_phi_fu_124_p4 | and_ln123_fu_488_p2);

assign or_ln123_6_fu_310_p4 = {{{tmp_s_fu_132_p4}, {tmp_fu_302_p3}}, {or_ln123_8_fu_296_p2}};

assign or_ln123_7_fu_332_p2 = (shl_ln123_1_fu_324_p3 | or_ln123_6_fu_310_p4);

assign or_ln123_8_fu_296_p2 = (tmp_109_fu_286_p4 | tmp_108_fu_262_p11);

assign or_ln123_9_fu_468_p2 = (tmp9_fu_422_p4 | and_ln123_3_fu_436_p15);

assign or_ln123_fu_408_p2 = (tmp_111_fu_380_p13 | and_ln123_2_fu_354_p12);

assign prev_out = ap_phi_mux_prev_phi_fu_124_p4;

assign shl_ln123_1_fu_324_p3 = {{trunc_ln123_fu_320_p1}, {7'd0}};

assign tmp11_fu_474_p3 = {{tmp_112_fu_414_p3}, {or_ln123_9_fu_468_p2}};

assign tmp7_fu_346_p3 = {{tmp_110_fu_338_p3}, {or_ln123_7_fu_332_p2}};

assign tmp9_fu_422_p4 = {{{tmp_107_fu_252_p4}, {tmp_112_fu_414_p3}}, {or_ln123_fu_408_p2}};

assign tmp_100_fu_182_p4 = {{ap_phi_mux_prev_phi_fu_124_p4[6:1]}};

assign tmp_101_fu_192_p4 = {{ap_phi_mux_prev_phi_fu_124_p4[40:35]}};

assign tmp_102_fu_202_p4 = {{ap_phi_mux_prev_phi_fu_124_p4[33:28]}};

assign tmp_103_fu_212_p4 = {{ap_phi_mux_prev_phi_fu_124_p4[26:21]}};

assign tmp_104_fu_222_p4 = {{ap_phi_mux_prev_phi_fu_124_p4[19:14]}};

assign tmp_105_fu_232_p4 = {{ap_phi_mux_prev_phi_fu_124_p4[12:7]}};

assign tmp_106_fu_242_p4 = {{ap_phi_mux_prev_phi_fu_124_p4[46:42]}};

assign tmp_107_fu_252_p4 = {{ap_phi_mux_prev_phi_fu_124_p4[48:43]}};

assign tmp_108_fu_262_p11 = {{{{{{{{{{tmp_96_fu_142_p4}, {1'd0}}, {tmp_97_fu_152_p4}}, {1'd0}}, {tmp_98_fu_162_p4}}, {1'd0}}, {tmp_99_fu_172_p4}}, {1'd0}}, {tmp_100_fu_182_p4}}, {7'd0}};

assign tmp_109_fu_286_p4 = {{ap_phi_mux_prev_phi_fu_124_p4[47:7]}};

assign tmp_110_fu_338_p3 = ap_phi_mux_prev_phi_fu_124_p4[32'd41];

assign tmp_111_fu_380_p13 = {{{{{{{{{{{{tmp_106_fu_242_p4}, {1'd0}}, {tmp_101_fu_192_p4}}, {1'd0}}, {tmp_102_fu_202_p4}}, {1'd0}}, {tmp_103_fu_212_p4}}, {1'd0}}, {tmp_104_fu_222_p4}}, {1'd0}}, {tmp_105_fu_232_p4}}, {1'd0}};

assign tmp_112_fu_414_p3 = ap_phi_mux_prev_phi_fu_124_p4[32'd47];

assign tmp_96_fu_142_p4 = {{ap_phi_mux_prev_phi_fu_124_p4[34:29]}};

assign tmp_97_fu_152_p4 = {{ap_phi_mux_prev_phi_fu_124_p4[27:22]}};

assign tmp_98_fu_162_p4 = {{ap_phi_mux_prev_phi_fu_124_p4[20:15]}};

assign tmp_99_fu_172_p4 = {{ap_phi_mux_prev_phi_fu_124_p4[13:8]}};

assign tmp_fu_302_p3 = ap_phi_mux_prev_phi_fu_124_p4[32'd48];

assign tmp_s_fu_132_p4 = {{ap_phi_mux_prev_phi_fu_124_p4[41:36]}};

assign trunc_ln123_4_fu_432_p1 = ap_phi_mux_prev_phi_fu_124_p4[5:0];

assign trunc_ln123_fu_320_p1 = ap_phi_mux_prev_phi_fu_124_p4[40:0];

endmodule //dut_rollout_Pipeline_VITIS_LOOP_114_1
