-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dut is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    strm_in_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    strm_in_empty_n : IN STD_LOGIC;
    strm_in_read : OUT STD_LOGIC;
    strm_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    strm_out_full_n : IN STD_LOGIC;
    strm_out_write : OUT STD_LOGIC );
end;


architecture behav of dut is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "dut_dut,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.167437,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=128,HLS_SYN_DSP=0,HLS_SYN_FF=14889,HLS_SYN_LUT=30730,HLS_VERSION=2025_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (11 downto 0) := "000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (11 downto 0) := "000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (11 downto 0) := "000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (11 downto 0) := "000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (11 downto 0) := "000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (11 downto 0) := "000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (11 downto 0) := "000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (11 downto 0) := "000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (11 downto 0) := "001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (11 downto 0) := "010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (11 downto 0) := "100000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv20_0 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv49_0 : STD_LOGIC_VECTOR (48 downto 0) := "0000000000000000000000000000000000000000000000000";
    constant ap_const_lv6_2A : STD_LOGIC_VECTOR (5 downto 0) := "101010";
    constant ap_const_lv6_2B : STD_LOGIC_VECTOR (5 downto 0) := "101011";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal strm_in_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal strm_out_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal grp_fu_277_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal is_red_reg_315 : STD_LOGIC_VECTOR (0 downto 0);
    signal is_player1_turn_reg_320 : STD_LOGIC_VECTOR (0 downto 0);
    signal this_parents_addr_reg_325 : STD_LOGIC_VECTOR (12 downto 0);
    signal this_firstChilds_addr_reg_330 : STD_LOGIC_VECTOR (12 downto 0);
    signal this_numChildren_addr_reg_335 : STD_LOGIC_VECTOR (12 downto 0);
    signal this_visitCounts_addr_reg_340 : STD_LOGIC_VECTOR (12 downto 0);
    signal this_meanQ_addr_reg_345 : STD_LOGIC_VECTOR (12 downto 0);
    signal this_terminals_addr_reg_350 : STD_LOGIC_VECTOR (12 downto 0);
    signal this_triedMask_addr_reg_355 : STD_LOGIC_VECTOR (12 downto 0);
    signal this_logVisitCounts_addr_reg_360 : STD_LOGIC_VECTOR (12 downto 0);
    signal last_move_fu_291_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal last_move_reg_371 : STD_LOGIC_VECTOR (31 downto 0);
    signal searcher_visitCounts_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal searcher_visitCounts_ce0 : STD_LOGIC;
    signal searcher_visitCounts_we0 : STD_LOGIC;
    signal searcher_visitCounts_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal searcher_visitCounts_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal searcher_meanQ_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal searcher_meanQ_ce0 : STD_LOGIC;
    signal searcher_meanQ_we0 : STD_LOGIC;
    signal searcher_meanQ_d0 : STD_LOGIC_VECTOR (19 downto 0);
    signal searcher_meanQ_q0 : STD_LOGIC_VECTOR (19 downto 0);
    signal searcher_parents_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal searcher_parents_ce0 : STD_LOGIC;
    signal searcher_parents_we0 : STD_LOGIC;
    signal searcher_parents_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal searcher_parents_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal searcher_firstChilds_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal searcher_firstChilds_ce0 : STD_LOGIC;
    signal searcher_firstChilds_we0 : STD_LOGIC;
    signal searcher_firstChilds_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal searcher_firstChilds_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal searcher_numChildren_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal searcher_numChildren_ce0 : STD_LOGIC;
    signal searcher_numChildren_we0 : STD_LOGIC;
    signal searcher_numChildren_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal searcher_numChildren_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal searcher_nextSiblings_ce0 : STD_LOGIC;
    signal searcher_nextSiblings_we0 : STD_LOGIC;
    signal searcher_nextSiblings_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal searcher_numLegalActions_ce0 : STD_LOGIC;
    signal searcher_numLegalActions_we0 : STD_LOGIC;
    signal searcher_numLegalActions_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal searcher_terminals_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal searcher_terminals_ce0 : STD_LOGIC;
    signal searcher_terminals_we0 : STD_LOGIC;
    signal searcher_terminals_d0 : STD_LOGIC_VECTOR (0 downto 0);
    signal searcher_terminals_q0 : STD_LOGIC_VECTOR (0 downto 0);
    signal searcher_childActions_ce0 : STD_LOGIC;
    signal searcher_childActions_we0 : STD_LOGIC;
    signal searcher_childActions_q0 : STD_LOGIC_VECTOR (5 downto 0);
    signal searcher_triedMask_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal searcher_triedMask_ce0 : STD_LOGIC;
    signal searcher_triedMask_we0 : STD_LOGIC;
    signal searcher_triedMask_d0 : STD_LOGIC_VECTOR (48 downto 0);
    signal searcher_triedMask_q0 : STD_LOGIC_VECTOR (48 downto 0);
    signal searcher_isREDs_ce0 : STD_LOGIC;
    signal searcher_isREDs_we0 : STD_LOGIC;
    signal searcher_isREDs_q0 : STD_LOGIC_VECTOR (0 downto 0);
    signal searcher_logVisitCounts_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal searcher_logVisitCounts_ce0 : STD_LOGIC;
    signal searcher_logVisitCounts_we0 : STD_LOGIC;
    signal searcher_logVisitCounts_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal searcher_logVisitCounts_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_ap_start : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_ap_done : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_ap_idle : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_ap_ready : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_strm_in_read : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_player1_48_out : STD_LOGIC_VECTOR (48 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_player1_48_out_ap_vld : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_ap_start : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_ap_done : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_ap_idle : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_ap_ready : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_strm_in_read : STD_LOGIC;
    signal grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_player2_out : STD_LOGIC_VECTOR (48 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_player2_out_ap_vld : STD_LOGIC;
    signal grp_search_fu_247_ap_start : STD_LOGIC;
    signal grp_search_fu_247_ap_done : STD_LOGIC;
    signal grp_search_fu_247_ap_idle : STD_LOGIC;
    signal grp_search_fu_247_ap_ready : STD_LOGIC;
    signal grp_search_fu_247_this_visitCounts_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_search_fu_247_this_visitCounts_ce0 : STD_LOGIC;
    signal grp_search_fu_247_this_visitCounts_we0 : STD_LOGIC;
    signal grp_search_fu_247_this_visitCounts_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_search_fu_247_this_meanQ_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_search_fu_247_this_meanQ_ce0 : STD_LOGIC;
    signal grp_search_fu_247_this_meanQ_we0 : STD_LOGIC;
    signal grp_search_fu_247_this_meanQ_d0 : STD_LOGIC_VECTOR (19 downto 0);
    signal grp_search_fu_247_this_parents_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_search_fu_247_this_parents_ce0 : STD_LOGIC;
    signal grp_search_fu_247_this_parents_we0 : STD_LOGIC;
    signal grp_search_fu_247_this_parents_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_search_fu_247_this_firstChilds_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_search_fu_247_this_firstChilds_ce0 : STD_LOGIC;
    signal grp_search_fu_247_this_firstChilds_we0 : STD_LOGIC;
    signal grp_search_fu_247_this_firstChilds_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_search_fu_247_this_numChildren_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_search_fu_247_this_numChildren_ce0 : STD_LOGIC;
    signal grp_search_fu_247_this_numChildren_we0 : STD_LOGIC;
    signal grp_search_fu_247_this_numChildren_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_search_fu_247_this_nextSiblings_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_search_fu_247_this_nextSiblings_ce0 : STD_LOGIC;
    signal grp_search_fu_247_this_nextSiblings_we0 : STD_LOGIC;
    signal grp_search_fu_247_this_nextSiblings_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_search_fu_247_this_numLegalActions_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_search_fu_247_this_numLegalActions_ce0 : STD_LOGIC;
    signal grp_search_fu_247_this_numLegalActions_we0 : STD_LOGIC;
    signal grp_search_fu_247_this_numLegalActions_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_search_fu_247_this_terminals_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_search_fu_247_this_terminals_ce0 : STD_LOGIC;
    signal grp_search_fu_247_this_terminals_we0 : STD_LOGIC;
    signal grp_search_fu_247_this_terminals_d0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_search_fu_247_this_childActions_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_search_fu_247_this_childActions_ce0 : STD_LOGIC;
    signal grp_search_fu_247_this_childActions_we0 : STD_LOGIC;
    signal grp_search_fu_247_this_childActions_d0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_search_fu_247_this_triedMask_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_search_fu_247_this_triedMask_ce0 : STD_LOGIC;
    signal grp_search_fu_247_this_triedMask_we0 : STD_LOGIC;
    signal grp_search_fu_247_this_triedMask_d0 : STD_LOGIC_VECTOR (48 downto 0);
    signal grp_search_fu_247_this_isREDs_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_search_fu_247_this_isREDs_ce0 : STD_LOGIC;
    signal grp_search_fu_247_this_isREDs_we0 : STD_LOGIC;
    signal grp_search_fu_247_this_isREDs_d0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_search_fu_247_this_logVisitCounts_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_search_fu_247_this_logVisitCounts_ce0 : STD_LOGIC;
    signal grp_search_fu_247_this_logVisitCounts_we0 : STD_LOGIC;
    signal grp_search_fu_247_this_logVisitCounts_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_search_fu_247_this_rng_read : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_search_fu_247_ap_return : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_search_fu_247_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal searcher_visitCounts_we0_out : STD_LOGIC;
    signal searcher_meanQ_we0_out : STD_LOGIC;
    signal searcher_parents_we0_out : STD_LOGIC;
    signal searcher_firstChilds_we0_out : STD_LOGIC;
    signal searcher_numChildren_we0_out : STD_LOGIC;
    signal searcher_terminals_we0_out : STD_LOGIC;
    signal searcher_triedMask_we0_out : STD_LOGIC;
    signal searcher_logVisitCounts_we0_out : STD_LOGIC;
    signal searcher_parents_we0_local : STD_LOGIC;
    signal searcher_parents_ce0_local : STD_LOGIC;
    signal searcher_parents_address0_local : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal searcher_firstChilds_we0_local : STD_LOGIC;
    signal searcher_firstChilds_ce0_local : STD_LOGIC;
    signal searcher_firstChilds_address0_local : STD_LOGIC_VECTOR (12 downto 0);
    signal searcher_numChildren_we0_local : STD_LOGIC;
    signal searcher_numChildren_ce0_local : STD_LOGIC;
    signal searcher_numChildren_address0_local : STD_LOGIC_VECTOR (12 downto 0);
    signal searcher_visitCounts_we0_local : STD_LOGIC;
    signal searcher_visitCounts_ce0_local : STD_LOGIC;
    signal searcher_visitCounts_address0_local : STD_LOGIC_VECTOR (12 downto 0);
    signal searcher_meanQ_we0_local : STD_LOGIC;
    signal searcher_meanQ_ce0_local : STD_LOGIC;
    signal searcher_meanQ_address0_local : STD_LOGIC_VECTOR (12 downto 0);
    signal searcher_terminals_we0_local : STD_LOGIC;
    signal searcher_terminals_ce0_local : STD_LOGIC;
    signal searcher_terminals_address0_local : STD_LOGIC_VECTOR (12 downto 0);
    signal searcher_triedMask_we0_local : STD_LOGIC;
    signal searcher_triedMask_ce0_local : STD_LOGIC;
    signal searcher_triedMask_address0_local : STD_LOGIC_VECTOR (12 downto 0);
    signal searcher_logVisitCounts_we0_local : STD_LOGIC;
    signal searcher_logVisitCounts_ce0_local : STD_LOGIC;
    signal searcher_logVisitCounts_address0_local : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component dut_dut_Pipeline_VITIS_LOOP_17_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        strm_in_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        strm_in_empty_n : IN STD_LOGIC;
        strm_in_read : OUT STD_LOGIC;
        player1_48_out : OUT STD_LOGIC_VECTOR (48 downto 0);
        player1_48_out_ap_vld : OUT STD_LOGIC );
    end component;


    component dut_dut_Pipeline_VITIS_LOOP_27_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        strm_in_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        strm_in_empty_n : IN STD_LOGIC;
        strm_in_read : OUT STD_LOGIC;
        player2_out : OUT STD_LOGIC_VECTOR (48 downto 0);
        player2_out_ap_vld : OUT STD_LOGIC );
    end component;


    component dut_search IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        this_visitCounts_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        this_visitCounts_ce0 : OUT STD_LOGIC;
        this_visitCounts_we0 : OUT STD_LOGIC;
        this_visitCounts_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        this_visitCounts_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        this_meanQ_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        this_meanQ_ce0 : OUT STD_LOGIC;
        this_meanQ_we0 : OUT STD_LOGIC;
        this_meanQ_d0 : OUT STD_LOGIC_VECTOR (19 downto 0);
        this_meanQ_q0 : IN STD_LOGIC_VECTOR (19 downto 0);
        this_parents_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        this_parents_ce0 : OUT STD_LOGIC;
        this_parents_we0 : OUT STD_LOGIC;
        this_parents_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        this_parents_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        this_firstChilds_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        this_firstChilds_ce0 : OUT STD_LOGIC;
        this_firstChilds_we0 : OUT STD_LOGIC;
        this_firstChilds_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        this_firstChilds_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        this_numChildren_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        this_numChildren_ce0 : OUT STD_LOGIC;
        this_numChildren_we0 : OUT STD_LOGIC;
        this_numChildren_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        this_numChildren_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        this_nextSiblings_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        this_nextSiblings_ce0 : OUT STD_LOGIC;
        this_nextSiblings_we0 : OUT STD_LOGIC;
        this_nextSiblings_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        this_nextSiblings_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        this_numLegalActions_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        this_numLegalActions_ce0 : OUT STD_LOGIC;
        this_numLegalActions_we0 : OUT STD_LOGIC;
        this_numLegalActions_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        this_numLegalActions_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        this_terminals_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        this_terminals_ce0 : OUT STD_LOGIC;
        this_terminals_we0 : OUT STD_LOGIC;
        this_terminals_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        this_terminals_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
        this_childActions_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        this_childActions_ce0 : OUT STD_LOGIC;
        this_childActions_we0 : OUT STD_LOGIC;
        this_childActions_d0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        this_childActions_q0 : IN STD_LOGIC_VECTOR (5 downto 0);
        this_triedMask_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        this_triedMask_ce0 : OUT STD_LOGIC;
        this_triedMask_we0 : OUT STD_LOGIC;
        this_triedMask_d0 : OUT STD_LOGIC_VECTOR (48 downto 0);
        this_triedMask_q0 : IN STD_LOGIC_VECTOR (48 downto 0);
        this_isREDs_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        this_isREDs_ce0 : OUT STD_LOGIC;
        this_isREDs_we0 : OUT STD_LOGIC;
        this_isREDs_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        this_isREDs_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
        this_logVisitCounts_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        this_logVisitCounts_ce0 : OUT STD_LOGIC;
        this_logVisitCounts_we0 : OUT STD_LOGIC;
        this_logVisitCounts_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        this_logVisitCounts_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        this_rng_read : IN STD_LOGIC_VECTOR (5 downto 0);
        boardState_isPlayer1Turn_s : IN STD_LOGIC_VECTOR (0 downto 0);
        boardState_lastMove_s : IN STD_LOGIC_VECTOR (31 downto 0);
        boardState_player1_s : IN STD_LOGIC_VECTOR (48 downto 0);
        boardState_player2_s : IN STD_LOGIC_VECTOR (48 downto 0);
        isRED : IN STD_LOGIC_VECTOR (0 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (5 downto 0) );
    end component;


    component dut_searcher_visitCounts_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component dut_searcher_meanQ_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (19 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (19 downto 0) );
    end component;


    component dut_searcher_terminals_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (0 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component dut_searcher_childActions_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (5 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (5 downto 0) );
    end component;


    component dut_searcher_triedMask_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (48 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (48 downto 0) );
    end component;



begin
    searcher_visitCounts_U : component dut_searcher_visitCounts_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 5100,
        AddressWidth => 13)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => searcher_visitCounts_address0,
        ce0 => searcher_visitCounts_ce0,
        we0 => searcher_visitCounts_we0,
        d0 => searcher_visitCounts_d0,
        q0 => searcher_visitCounts_q0);

    searcher_meanQ_U : component dut_searcher_meanQ_RAM_AUTO_1R1W
    generic map (
        DataWidth => 20,
        AddressRange => 5100,
        AddressWidth => 13)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => searcher_meanQ_address0,
        ce0 => searcher_meanQ_ce0,
        we0 => searcher_meanQ_we0,
        d0 => searcher_meanQ_d0,
        q0 => searcher_meanQ_q0);

    searcher_parents_U : component dut_searcher_visitCounts_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 5100,
        AddressWidth => 13)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => searcher_parents_address0,
        ce0 => searcher_parents_ce0,
        we0 => searcher_parents_we0,
        d0 => searcher_parents_d0,
        q0 => searcher_parents_q0);

    searcher_firstChilds_U : component dut_searcher_visitCounts_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 5100,
        AddressWidth => 13)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => searcher_firstChilds_address0,
        ce0 => searcher_firstChilds_ce0,
        we0 => searcher_firstChilds_we0,
        d0 => searcher_firstChilds_d0,
        q0 => searcher_firstChilds_q0);

    searcher_numChildren_U : component dut_searcher_visitCounts_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 5100,
        AddressWidth => 13)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => searcher_numChildren_address0,
        ce0 => searcher_numChildren_ce0,
        we0 => searcher_numChildren_we0,
        d0 => searcher_numChildren_d0,
        q0 => searcher_numChildren_q0);

    searcher_nextSiblings_U : component dut_searcher_visitCounts_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 5100,
        AddressWidth => 13)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => grp_search_fu_247_this_nextSiblings_address0,
        ce0 => searcher_nextSiblings_ce0,
        we0 => searcher_nextSiblings_we0,
        d0 => grp_search_fu_247_this_nextSiblings_d0,
        q0 => searcher_nextSiblings_q0);

    searcher_numLegalActions_U : component dut_searcher_visitCounts_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 5100,
        AddressWidth => 13)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => grp_search_fu_247_this_numLegalActions_address0,
        ce0 => searcher_numLegalActions_ce0,
        we0 => searcher_numLegalActions_we0,
        d0 => grp_search_fu_247_this_numLegalActions_d0,
        q0 => searcher_numLegalActions_q0);

    searcher_terminals_U : component dut_searcher_terminals_RAM_AUTO_1R1W
    generic map (
        DataWidth => 1,
        AddressRange => 5100,
        AddressWidth => 13)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => searcher_terminals_address0,
        ce0 => searcher_terminals_ce0,
        we0 => searcher_terminals_we0,
        d0 => searcher_terminals_d0,
        q0 => searcher_terminals_q0);

    searcher_childActions_U : component dut_searcher_childActions_RAM_AUTO_1R1W
    generic map (
        DataWidth => 6,
        AddressRange => 5100,
        AddressWidth => 13)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => grp_search_fu_247_this_childActions_address0,
        ce0 => searcher_childActions_ce0,
        we0 => searcher_childActions_we0,
        d0 => grp_search_fu_247_this_childActions_d0,
        q0 => searcher_childActions_q0);

    searcher_triedMask_U : component dut_searcher_triedMask_RAM_AUTO_1R1W
    generic map (
        DataWidth => 49,
        AddressRange => 5100,
        AddressWidth => 13)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => searcher_triedMask_address0,
        ce0 => searcher_triedMask_ce0,
        we0 => searcher_triedMask_we0,
        d0 => searcher_triedMask_d0,
        q0 => searcher_triedMask_q0);

    searcher_isREDs_U : component dut_searcher_terminals_RAM_AUTO_1R1W
    generic map (
        DataWidth => 1,
        AddressRange => 5100,
        AddressWidth => 13)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => grp_search_fu_247_this_isREDs_address0,
        ce0 => searcher_isREDs_ce0,
        we0 => searcher_isREDs_we0,
        d0 => grp_search_fu_247_this_isREDs_d0,
        q0 => searcher_isREDs_q0);

    searcher_logVisitCounts_U : component dut_searcher_visitCounts_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 5100,
        AddressWidth => 13)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => searcher_logVisitCounts_address0,
        ce0 => searcher_logVisitCounts_ce0,
        we0 => searcher_logVisitCounts_we0,
        d0 => searcher_logVisitCounts_d0,
        q0 => searcher_logVisitCounts_q0);

    grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233 : component dut_dut_Pipeline_VITIS_LOOP_17_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_ap_start,
        ap_done => grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_ap_done,
        ap_idle => grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_ap_idle,
        ap_ready => grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_ap_ready,
        strm_in_dout => strm_in_dout,
        strm_in_empty_n => strm_in_empty_n,
        strm_in_read => grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_strm_in_read,
        player1_48_out => grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_player1_48_out,
        player1_48_out_ap_vld => grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_player1_48_out_ap_vld);

    grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240 : component dut_dut_Pipeline_VITIS_LOOP_27_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_ap_start,
        ap_done => grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_ap_done,
        ap_idle => grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_ap_idle,
        ap_ready => grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_ap_ready,
        strm_in_dout => strm_in_dout,
        strm_in_empty_n => strm_in_empty_n,
        strm_in_read => grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_strm_in_read,
        player2_out => grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_player2_out,
        player2_out_ap_vld => grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_player2_out_ap_vld);

    grp_search_fu_247 : component dut_search
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_search_fu_247_ap_start,
        ap_done => grp_search_fu_247_ap_done,
        ap_idle => grp_search_fu_247_ap_idle,
        ap_ready => grp_search_fu_247_ap_ready,
        this_visitCounts_address0 => grp_search_fu_247_this_visitCounts_address0,
        this_visitCounts_ce0 => grp_search_fu_247_this_visitCounts_ce0,
        this_visitCounts_we0 => grp_search_fu_247_this_visitCounts_we0,
        this_visitCounts_d0 => grp_search_fu_247_this_visitCounts_d0,
        this_visitCounts_q0 => searcher_visitCounts_q0,
        this_meanQ_address0 => grp_search_fu_247_this_meanQ_address0,
        this_meanQ_ce0 => grp_search_fu_247_this_meanQ_ce0,
        this_meanQ_we0 => grp_search_fu_247_this_meanQ_we0,
        this_meanQ_d0 => grp_search_fu_247_this_meanQ_d0,
        this_meanQ_q0 => searcher_meanQ_q0,
        this_parents_address0 => grp_search_fu_247_this_parents_address0,
        this_parents_ce0 => grp_search_fu_247_this_parents_ce0,
        this_parents_we0 => grp_search_fu_247_this_parents_we0,
        this_parents_d0 => grp_search_fu_247_this_parents_d0,
        this_parents_q0 => searcher_parents_q0,
        this_firstChilds_address0 => grp_search_fu_247_this_firstChilds_address0,
        this_firstChilds_ce0 => grp_search_fu_247_this_firstChilds_ce0,
        this_firstChilds_we0 => grp_search_fu_247_this_firstChilds_we0,
        this_firstChilds_d0 => grp_search_fu_247_this_firstChilds_d0,
        this_firstChilds_q0 => searcher_firstChilds_q0,
        this_numChildren_address0 => grp_search_fu_247_this_numChildren_address0,
        this_numChildren_ce0 => grp_search_fu_247_this_numChildren_ce0,
        this_numChildren_we0 => grp_search_fu_247_this_numChildren_we0,
        this_numChildren_d0 => grp_search_fu_247_this_numChildren_d0,
        this_numChildren_q0 => searcher_numChildren_q0,
        this_nextSiblings_address0 => grp_search_fu_247_this_nextSiblings_address0,
        this_nextSiblings_ce0 => grp_search_fu_247_this_nextSiblings_ce0,
        this_nextSiblings_we0 => grp_search_fu_247_this_nextSiblings_we0,
        this_nextSiblings_d0 => grp_search_fu_247_this_nextSiblings_d0,
        this_nextSiblings_q0 => searcher_nextSiblings_q0,
        this_numLegalActions_address0 => grp_search_fu_247_this_numLegalActions_address0,
        this_numLegalActions_ce0 => grp_search_fu_247_this_numLegalActions_ce0,
        this_numLegalActions_we0 => grp_search_fu_247_this_numLegalActions_we0,
        this_numLegalActions_d0 => grp_search_fu_247_this_numLegalActions_d0,
        this_numLegalActions_q0 => searcher_numLegalActions_q0,
        this_terminals_address0 => grp_search_fu_247_this_terminals_address0,
        this_terminals_ce0 => grp_search_fu_247_this_terminals_ce0,
        this_terminals_we0 => grp_search_fu_247_this_terminals_we0,
        this_terminals_d0 => grp_search_fu_247_this_terminals_d0,
        this_terminals_q0 => searcher_terminals_q0,
        this_childActions_address0 => grp_search_fu_247_this_childActions_address0,
        this_childActions_ce0 => grp_search_fu_247_this_childActions_ce0,
        this_childActions_we0 => grp_search_fu_247_this_childActions_we0,
        this_childActions_d0 => grp_search_fu_247_this_childActions_d0,
        this_childActions_q0 => searcher_childActions_q0,
        this_triedMask_address0 => grp_search_fu_247_this_triedMask_address0,
        this_triedMask_ce0 => grp_search_fu_247_this_triedMask_ce0,
        this_triedMask_we0 => grp_search_fu_247_this_triedMask_we0,
        this_triedMask_d0 => grp_search_fu_247_this_triedMask_d0,
        this_triedMask_q0 => searcher_triedMask_q0,
        this_isREDs_address0 => grp_search_fu_247_this_isREDs_address0,
        this_isREDs_ce0 => grp_search_fu_247_this_isREDs_ce0,
        this_isREDs_we0 => grp_search_fu_247_this_isREDs_we0,
        this_isREDs_d0 => grp_search_fu_247_this_isREDs_d0,
        this_isREDs_q0 => searcher_isREDs_q0,
        this_logVisitCounts_address0 => grp_search_fu_247_this_logVisitCounts_address0,
        this_logVisitCounts_ce0 => grp_search_fu_247_this_logVisitCounts_ce0,
        this_logVisitCounts_we0 => grp_search_fu_247_this_logVisitCounts_we0,
        this_logVisitCounts_d0 => grp_search_fu_247_this_logVisitCounts_d0,
        this_logVisitCounts_q0 => searcher_logVisitCounts_q0,
        this_rng_read => grp_search_fu_247_this_rng_read,
        boardState_isPlayer1Turn_s => is_player1_turn_reg_320,
        boardState_lastMove_s => last_move_reg_371,
        boardState_player1_s => grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_player1_48_out,
        boardState_player2_s => grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_player2_out,
        isRED => is_red_reg_315,
        ap_return => grp_search_fu_247_ap_return);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_ap_ready = ap_const_logic_1)) then 
                    grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_ap_ready = ap_const_logic_1)) then 
                    grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_search_fu_247_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_search_fu_247_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state11) or ((strm_in_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8)))) then 
                    grp_search_fu_247_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_search_fu_247_ap_ready = ap_const_logic_1)) then 
                    grp_search_fu_247_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                is_player1_turn_reg_320 <= grp_fu_277_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                is_red_reg_315 <= grp_fu_277_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                last_move_reg_371 <= last_move_fu_291_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, strm_in_empty_n, strm_out_full_n, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8, ap_CS_fsm_state12, grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_ap_done, grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_ap_done, grp_search_fu_247_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state9)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((strm_in_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                if (((strm_in_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                if (((strm_in_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                if (((strm_in_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                if (((grp_search_fu_247_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                if ((not(((strm_out_full_n = ap_const_logic_0) or (grp_search_fu_247_ap_done = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state12))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state12;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;

    ap_ST_fsm_state12_blk_assign_proc : process(strm_out_full_n, grp_search_fu_247_ap_done)
    begin
        if (((strm_out_full_n = ap_const_logic_0) or (grp_search_fu_247_ap_done = ap_const_logic_0))) then 
            ap_ST_fsm_state12_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state12_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_ap_done)
    begin
        if ((grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_ap_done)
    begin
        if ((grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state5_blk_assign_proc : process(strm_in_empty_n)
    begin
        if ((strm_in_empty_n = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state6_blk_assign_proc : process(strm_in_empty_n)
    begin
        if ((strm_in_empty_n = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state7_blk_assign_proc : process(strm_in_empty_n)
    begin
        if ((strm_in_empty_n = ap_const_logic_0)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state8_blk_assign_proc : process(strm_in_empty_n)
    begin
        if ((strm_in_empty_n = ap_const_logic_0)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state9_blk_assign_proc : process(grp_search_fu_247_ap_done)
    begin
        if ((grp_search_fu_247_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(strm_out_full_n, ap_CS_fsm_state12, grp_search_fu_247_ap_done)
    begin
        if ((not(((strm_out_full_n = ap_const_logic_0) or (grp_search_fu_247_ap_done = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(strm_out_full_n, ap_CS_fsm_state12, grp_search_fu_247_ap_done)
    begin
        if ((not(((strm_out_full_n = ap_const_logic_0) or (grp_search_fu_247_ap_done = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_ap_start <= grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_ap_start_reg;
    grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_ap_start <= grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_ap_start_reg;
    grp_fu_277_p2 <= "0" when (strm_in_dout = ap_const_lv32_0) else "1";
    grp_search_fu_247_ap_start <= grp_search_fu_247_ap_start_reg;

    grp_search_fu_247_this_rng_read_assign_proc : process(ap_CS_fsm_state12, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grp_search_fu_247_this_rng_read <= ap_const_lv6_2B;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            grp_search_fu_247_this_rng_read <= ap_const_lv6_2A;
        else 
            grp_search_fu_247_this_rng_read <= "XXXXXX";
        end if; 
    end process;

    last_move_fu_291_p2 <= std_logic_vector(unsigned(strm_in_dout) + unsigned(ap_const_lv32_FFFFFFFF));

    searcher_childActions_ce0_assign_proc : process(ap_CS_fsm_state12, grp_search_fu_247_this_childActions_ce0, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            searcher_childActions_ce0 <= grp_search_fu_247_this_childActions_ce0;
        else 
            searcher_childActions_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    searcher_childActions_we0_assign_proc : process(ap_CS_fsm_state12, grp_search_fu_247_this_childActions_we0, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            searcher_childActions_we0 <= grp_search_fu_247_this_childActions_we0;
        else 
            searcher_childActions_we0 <= ap_const_logic_0;
        end if; 
    end process;


    searcher_firstChilds_address0_assign_proc : process(ap_CS_fsm_state12, grp_search_fu_247_this_firstChilds_address0, ap_CS_fsm_state9, searcher_firstChilds_address0_local)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            searcher_firstChilds_address0 <= grp_search_fu_247_this_firstChilds_address0;
        else 
            searcher_firstChilds_address0 <= searcher_firstChilds_address0_local;
        end if; 
    end process;


    searcher_firstChilds_address0_local_assign_proc : process(ap_CS_fsm_state7, this_firstChilds_addr_reg_330, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            searcher_firstChilds_address0_local <= this_firstChilds_addr_reg_330;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            searcher_firstChilds_address0_local <= ap_const_lv64_0(13 - 1 downto 0);
        else 
            searcher_firstChilds_address0_local <= "XXXXXXXXXXXXX";
        end if; 
    end process;


    searcher_firstChilds_ce0_assign_proc : process(ap_CS_fsm_state12, grp_search_fu_247_this_firstChilds_ce0, ap_CS_fsm_state9, searcher_firstChilds_ce0_local)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            searcher_firstChilds_ce0 <= grp_search_fu_247_this_firstChilds_ce0;
        else 
            searcher_firstChilds_ce0 <= searcher_firstChilds_ce0_local;
        end if; 
    end process;


    searcher_firstChilds_ce0_local_assign_proc : process(strm_in_empty_n, ap_CS_fsm_state7, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or ((strm_in_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7)))) then 
            searcher_firstChilds_ce0_local <= ap_const_logic_1;
        else 
            searcher_firstChilds_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    searcher_firstChilds_d0_assign_proc : process(ap_CS_fsm_state12, grp_search_fu_247_this_firstChilds_d0, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            searcher_firstChilds_d0 <= grp_search_fu_247_this_firstChilds_d0;
        else 
            searcher_firstChilds_d0 <= ap_const_lv32_FFFFFFFF;
        end if; 
    end process;


    searcher_firstChilds_we0_assign_proc : process(ap_CS_fsm_state12, grp_search_fu_247_this_firstChilds_we0, ap_CS_fsm_state9, searcher_firstChilds_we0_out)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            searcher_firstChilds_we0 <= grp_search_fu_247_this_firstChilds_we0;
        else 
            searcher_firstChilds_we0 <= (searcher_firstChilds_we0_out or ap_const_logic_0);
        end if; 
    end process;


    searcher_firstChilds_we0_local_assign_proc : process(strm_in_empty_n, ap_CS_fsm_state7, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or ((strm_in_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7)))) then 
            searcher_firstChilds_we0_local <= ap_const_logic_1;
        else 
            searcher_firstChilds_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    searcher_firstChilds_we0_out <= searcher_firstChilds_we0_local;

    searcher_isREDs_ce0_assign_proc : process(ap_CS_fsm_state12, grp_search_fu_247_this_isREDs_ce0, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            searcher_isREDs_ce0 <= grp_search_fu_247_this_isREDs_ce0;
        else 
            searcher_isREDs_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    searcher_isREDs_we0_assign_proc : process(ap_CS_fsm_state12, grp_search_fu_247_this_isREDs_we0, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            searcher_isREDs_we0 <= grp_search_fu_247_this_isREDs_we0;
        else 
            searcher_isREDs_we0 <= ap_const_logic_0;
        end if; 
    end process;


    searcher_logVisitCounts_address0_assign_proc : process(ap_CS_fsm_state12, grp_search_fu_247_this_logVisitCounts_address0, ap_CS_fsm_state9, searcher_logVisitCounts_address0_local)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            searcher_logVisitCounts_address0 <= grp_search_fu_247_this_logVisitCounts_address0;
        else 
            searcher_logVisitCounts_address0 <= searcher_logVisitCounts_address0_local;
        end if; 
    end process;


    searcher_logVisitCounts_address0_local_assign_proc : process(ap_CS_fsm_state7, this_logVisitCounts_addr_reg_360, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            searcher_logVisitCounts_address0_local <= this_logVisitCounts_addr_reg_360;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            searcher_logVisitCounts_address0_local <= ap_const_lv64_0(13 - 1 downto 0);
        else 
            searcher_logVisitCounts_address0_local <= "XXXXXXXXXXXXX";
        end if; 
    end process;


    searcher_logVisitCounts_ce0_assign_proc : process(ap_CS_fsm_state12, grp_search_fu_247_this_logVisitCounts_ce0, ap_CS_fsm_state9, searcher_logVisitCounts_ce0_local)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            searcher_logVisitCounts_ce0 <= grp_search_fu_247_this_logVisitCounts_ce0;
        else 
            searcher_logVisitCounts_ce0 <= searcher_logVisitCounts_ce0_local;
        end if; 
    end process;


    searcher_logVisitCounts_ce0_local_assign_proc : process(strm_in_empty_n, ap_CS_fsm_state7, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or ((strm_in_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7)))) then 
            searcher_logVisitCounts_ce0_local <= ap_const_logic_1;
        else 
            searcher_logVisitCounts_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    searcher_logVisitCounts_d0_assign_proc : process(ap_CS_fsm_state12, grp_search_fu_247_this_logVisitCounts_d0, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            searcher_logVisitCounts_d0 <= grp_search_fu_247_this_logVisitCounts_d0;
        else 
            searcher_logVisitCounts_d0 <= ap_const_lv32_0;
        end if; 
    end process;


    searcher_logVisitCounts_we0_assign_proc : process(ap_CS_fsm_state12, grp_search_fu_247_this_logVisitCounts_we0, ap_CS_fsm_state9, searcher_logVisitCounts_we0_out)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            searcher_logVisitCounts_we0 <= grp_search_fu_247_this_logVisitCounts_we0;
        else 
            searcher_logVisitCounts_we0 <= (searcher_logVisitCounts_we0_out or ap_const_logic_0);
        end if; 
    end process;


    searcher_logVisitCounts_we0_local_assign_proc : process(strm_in_empty_n, ap_CS_fsm_state7, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or ((strm_in_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7)))) then 
            searcher_logVisitCounts_we0_local <= ap_const_logic_1;
        else 
            searcher_logVisitCounts_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    searcher_logVisitCounts_we0_out <= searcher_logVisitCounts_we0_local;

    searcher_meanQ_address0_assign_proc : process(ap_CS_fsm_state12, grp_search_fu_247_this_meanQ_address0, ap_CS_fsm_state9, searcher_meanQ_address0_local)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            searcher_meanQ_address0 <= grp_search_fu_247_this_meanQ_address0;
        else 
            searcher_meanQ_address0 <= searcher_meanQ_address0_local;
        end if; 
    end process;


    searcher_meanQ_address0_local_assign_proc : process(ap_CS_fsm_state7, this_meanQ_addr_reg_345, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            searcher_meanQ_address0_local <= this_meanQ_addr_reg_345;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            searcher_meanQ_address0_local <= ap_const_lv64_0(13 - 1 downto 0);
        else 
            searcher_meanQ_address0_local <= "XXXXXXXXXXXXX";
        end if; 
    end process;


    searcher_meanQ_ce0_assign_proc : process(ap_CS_fsm_state12, grp_search_fu_247_this_meanQ_ce0, ap_CS_fsm_state9, searcher_meanQ_ce0_local)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            searcher_meanQ_ce0 <= grp_search_fu_247_this_meanQ_ce0;
        else 
            searcher_meanQ_ce0 <= searcher_meanQ_ce0_local;
        end if; 
    end process;


    searcher_meanQ_ce0_local_assign_proc : process(strm_in_empty_n, ap_CS_fsm_state7, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or ((strm_in_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7)))) then 
            searcher_meanQ_ce0_local <= ap_const_logic_1;
        else 
            searcher_meanQ_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    searcher_meanQ_d0_assign_proc : process(ap_CS_fsm_state12, grp_search_fu_247_this_meanQ_d0, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            searcher_meanQ_d0 <= grp_search_fu_247_this_meanQ_d0;
        else 
            searcher_meanQ_d0 <= ap_const_lv20_0;
        end if; 
    end process;


    searcher_meanQ_we0_assign_proc : process(ap_CS_fsm_state12, grp_search_fu_247_this_meanQ_we0, ap_CS_fsm_state9, searcher_meanQ_we0_out)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            searcher_meanQ_we0 <= grp_search_fu_247_this_meanQ_we0;
        else 
            searcher_meanQ_we0 <= (searcher_meanQ_we0_out or ap_const_logic_0);
        end if; 
    end process;


    searcher_meanQ_we0_local_assign_proc : process(strm_in_empty_n, ap_CS_fsm_state7, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or ((strm_in_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7)))) then 
            searcher_meanQ_we0_local <= ap_const_logic_1;
        else 
            searcher_meanQ_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    searcher_meanQ_we0_out <= searcher_meanQ_we0_local;

    searcher_nextSiblings_ce0_assign_proc : process(ap_CS_fsm_state12, grp_search_fu_247_this_nextSiblings_ce0, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            searcher_nextSiblings_ce0 <= grp_search_fu_247_this_nextSiblings_ce0;
        else 
            searcher_nextSiblings_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    searcher_nextSiblings_we0_assign_proc : process(ap_CS_fsm_state12, grp_search_fu_247_this_nextSiblings_we0, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            searcher_nextSiblings_we0 <= grp_search_fu_247_this_nextSiblings_we0;
        else 
            searcher_nextSiblings_we0 <= ap_const_logic_0;
        end if; 
    end process;


    searcher_numChildren_address0_assign_proc : process(ap_CS_fsm_state12, grp_search_fu_247_this_numChildren_address0, ap_CS_fsm_state9, searcher_numChildren_address0_local)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            searcher_numChildren_address0 <= grp_search_fu_247_this_numChildren_address0;
        else 
            searcher_numChildren_address0 <= searcher_numChildren_address0_local;
        end if; 
    end process;


    searcher_numChildren_address0_local_assign_proc : process(ap_CS_fsm_state7, this_numChildren_addr_reg_335, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            searcher_numChildren_address0_local <= this_numChildren_addr_reg_335;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            searcher_numChildren_address0_local <= ap_const_lv64_0(13 - 1 downto 0);
        else 
            searcher_numChildren_address0_local <= "XXXXXXXXXXXXX";
        end if; 
    end process;


    searcher_numChildren_ce0_assign_proc : process(ap_CS_fsm_state12, grp_search_fu_247_this_numChildren_ce0, ap_CS_fsm_state9, searcher_numChildren_ce0_local)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            searcher_numChildren_ce0 <= grp_search_fu_247_this_numChildren_ce0;
        else 
            searcher_numChildren_ce0 <= searcher_numChildren_ce0_local;
        end if; 
    end process;


    searcher_numChildren_ce0_local_assign_proc : process(strm_in_empty_n, ap_CS_fsm_state7, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or ((strm_in_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7)))) then 
            searcher_numChildren_ce0_local <= ap_const_logic_1;
        else 
            searcher_numChildren_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    searcher_numChildren_d0_assign_proc : process(ap_CS_fsm_state12, grp_search_fu_247_this_numChildren_d0, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            searcher_numChildren_d0 <= grp_search_fu_247_this_numChildren_d0;
        else 
            searcher_numChildren_d0 <= ap_const_lv32_0;
        end if; 
    end process;


    searcher_numChildren_we0_assign_proc : process(ap_CS_fsm_state12, grp_search_fu_247_this_numChildren_we0, ap_CS_fsm_state9, searcher_numChildren_we0_out)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            searcher_numChildren_we0 <= grp_search_fu_247_this_numChildren_we0;
        else 
            searcher_numChildren_we0 <= (searcher_numChildren_we0_out or ap_const_logic_0);
        end if; 
    end process;


    searcher_numChildren_we0_local_assign_proc : process(strm_in_empty_n, ap_CS_fsm_state7, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or ((strm_in_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7)))) then 
            searcher_numChildren_we0_local <= ap_const_logic_1;
        else 
            searcher_numChildren_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    searcher_numChildren_we0_out <= searcher_numChildren_we0_local;

    searcher_numLegalActions_ce0_assign_proc : process(ap_CS_fsm_state12, grp_search_fu_247_this_numLegalActions_ce0, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            searcher_numLegalActions_ce0 <= grp_search_fu_247_this_numLegalActions_ce0;
        else 
            searcher_numLegalActions_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    searcher_numLegalActions_we0_assign_proc : process(ap_CS_fsm_state12, grp_search_fu_247_this_numLegalActions_we0, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            searcher_numLegalActions_we0 <= grp_search_fu_247_this_numLegalActions_we0;
        else 
            searcher_numLegalActions_we0 <= ap_const_logic_0;
        end if; 
    end process;


    searcher_parents_address0_assign_proc : process(ap_CS_fsm_state12, grp_search_fu_247_this_parents_address0, ap_CS_fsm_state9, searcher_parents_address0_local)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            searcher_parents_address0 <= grp_search_fu_247_this_parents_address0;
        else 
            searcher_parents_address0 <= searcher_parents_address0_local;
        end if; 
    end process;


    searcher_parents_address0_local_assign_proc : process(ap_CS_fsm_state7, this_parents_addr_reg_325, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            searcher_parents_address0_local <= this_parents_addr_reg_325;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            searcher_parents_address0_local <= ap_const_lv64_0(13 - 1 downto 0);
        else 
            searcher_parents_address0_local <= "XXXXXXXXXXXXX";
        end if; 
    end process;


    searcher_parents_ce0_assign_proc : process(ap_CS_fsm_state12, grp_search_fu_247_this_parents_ce0, ap_CS_fsm_state9, searcher_parents_ce0_local)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            searcher_parents_ce0 <= grp_search_fu_247_this_parents_ce0;
        else 
            searcher_parents_ce0 <= searcher_parents_ce0_local;
        end if; 
    end process;


    searcher_parents_ce0_local_assign_proc : process(strm_in_empty_n, ap_CS_fsm_state7, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or ((strm_in_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7)))) then 
            searcher_parents_ce0_local <= ap_const_logic_1;
        else 
            searcher_parents_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    searcher_parents_d0_assign_proc : process(ap_CS_fsm_state12, grp_search_fu_247_this_parents_d0, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            searcher_parents_d0 <= grp_search_fu_247_this_parents_d0;
        else 
            searcher_parents_d0 <= ap_const_lv32_FFFFFFFF;
        end if; 
    end process;


    searcher_parents_we0_assign_proc : process(ap_CS_fsm_state12, grp_search_fu_247_this_parents_we0, ap_CS_fsm_state9, searcher_parents_we0_out)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            searcher_parents_we0 <= grp_search_fu_247_this_parents_we0;
        else 
            searcher_parents_we0 <= (searcher_parents_we0_out or ap_const_logic_0);
        end if; 
    end process;


    searcher_parents_we0_local_assign_proc : process(strm_in_empty_n, ap_CS_fsm_state7, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or ((strm_in_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7)))) then 
            searcher_parents_we0_local <= ap_const_logic_1;
        else 
            searcher_parents_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    searcher_parents_we0_out <= searcher_parents_we0_local;

    searcher_terminals_address0_assign_proc : process(ap_CS_fsm_state12, grp_search_fu_247_this_terminals_address0, ap_CS_fsm_state9, searcher_terminals_address0_local)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            searcher_terminals_address0 <= grp_search_fu_247_this_terminals_address0;
        else 
            searcher_terminals_address0 <= searcher_terminals_address0_local;
        end if; 
    end process;


    searcher_terminals_address0_local_assign_proc : process(ap_CS_fsm_state7, this_terminals_addr_reg_350, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            searcher_terminals_address0_local <= this_terminals_addr_reg_350;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            searcher_terminals_address0_local <= ap_const_lv64_0(13 - 1 downto 0);
        else 
            searcher_terminals_address0_local <= "XXXXXXXXXXXXX";
        end if; 
    end process;


    searcher_terminals_ce0_assign_proc : process(ap_CS_fsm_state12, grp_search_fu_247_this_terminals_ce0, ap_CS_fsm_state9, searcher_terminals_ce0_local)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            searcher_terminals_ce0 <= grp_search_fu_247_this_terminals_ce0;
        else 
            searcher_terminals_ce0 <= searcher_terminals_ce0_local;
        end if; 
    end process;


    searcher_terminals_ce0_local_assign_proc : process(strm_in_empty_n, ap_CS_fsm_state7, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or ((strm_in_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7)))) then 
            searcher_terminals_ce0_local <= ap_const_logic_1;
        else 
            searcher_terminals_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    searcher_terminals_d0_assign_proc : process(ap_CS_fsm_state12, grp_search_fu_247_this_terminals_d0, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            searcher_terminals_d0 <= grp_search_fu_247_this_terminals_d0;
        else 
            searcher_terminals_d0 <= ap_const_lv1_0;
        end if; 
    end process;


    searcher_terminals_we0_assign_proc : process(ap_CS_fsm_state12, grp_search_fu_247_this_terminals_we0, ap_CS_fsm_state9, searcher_terminals_we0_out)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            searcher_terminals_we0 <= grp_search_fu_247_this_terminals_we0;
        else 
            searcher_terminals_we0 <= (searcher_terminals_we0_out or ap_const_logic_0);
        end if; 
    end process;


    searcher_terminals_we0_local_assign_proc : process(strm_in_empty_n, ap_CS_fsm_state7, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or ((strm_in_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7)))) then 
            searcher_terminals_we0_local <= ap_const_logic_1;
        else 
            searcher_terminals_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    searcher_terminals_we0_out <= searcher_terminals_we0_local;

    searcher_triedMask_address0_assign_proc : process(ap_CS_fsm_state12, grp_search_fu_247_this_triedMask_address0, ap_CS_fsm_state9, searcher_triedMask_address0_local)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            searcher_triedMask_address0 <= grp_search_fu_247_this_triedMask_address0;
        else 
            searcher_triedMask_address0 <= searcher_triedMask_address0_local;
        end if; 
    end process;


    searcher_triedMask_address0_local_assign_proc : process(ap_CS_fsm_state7, this_triedMask_addr_reg_355, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            searcher_triedMask_address0_local <= this_triedMask_addr_reg_355;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            searcher_triedMask_address0_local <= ap_const_lv64_0(13 - 1 downto 0);
        else 
            searcher_triedMask_address0_local <= "XXXXXXXXXXXXX";
        end if; 
    end process;


    searcher_triedMask_ce0_assign_proc : process(ap_CS_fsm_state12, grp_search_fu_247_this_triedMask_ce0, ap_CS_fsm_state9, searcher_triedMask_ce0_local)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            searcher_triedMask_ce0 <= grp_search_fu_247_this_triedMask_ce0;
        else 
            searcher_triedMask_ce0 <= searcher_triedMask_ce0_local;
        end if; 
    end process;


    searcher_triedMask_ce0_local_assign_proc : process(strm_in_empty_n, ap_CS_fsm_state7, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or ((strm_in_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7)))) then 
            searcher_triedMask_ce0_local <= ap_const_logic_1;
        else 
            searcher_triedMask_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    searcher_triedMask_d0_assign_proc : process(ap_CS_fsm_state12, grp_search_fu_247_this_triedMask_d0, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            searcher_triedMask_d0 <= grp_search_fu_247_this_triedMask_d0;
        else 
            searcher_triedMask_d0 <= ap_const_lv49_0;
        end if; 
    end process;


    searcher_triedMask_we0_assign_proc : process(ap_CS_fsm_state12, grp_search_fu_247_this_triedMask_we0, ap_CS_fsm_state9, searcher_triedMask_we0_out)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            searcher_triedMask_we0 <= grp_search_fu_247_this_triedMask_we0;
        else 
            searcher_triedMask_we0 <= (searcher_triedMask_we0_out or ap_const_logic_0);
        end if; 
    end process;


    searcher_triedMask_we0_local_assign_proc : process(strm_in_empty_n, ap_CS_fsm_state7, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or ((strm_in_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7)))) then 
            searcher_triedMask_we0_local <= ap_const_logic_1;
        else 
            searcher_triedMask_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    searcher_triedMask_we0_out <= searcher_triedMask_we0_local;

    searcher_visitCounts_address0_assign_proc : process(ap_CS_fsm_state12, grp_search_fu_247_this_visitCounts_address0, ap_CS_fsm_state9, searcher_visitCounts_address0_local)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            searcher_visitCounts_address0 <= grp_search_fu_247_this_visitCounts_address0;
        else 
            searcher_visitCounts_address0 <= searcher_visitCounts_address0_local;
        end if; 
    end process;


    searcher_visitCounts_address0_local_assign_proc : process(ap_CS_fsm_state7, this_visitCounts_addr_reg_340, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            searcher_visitCounts_address0_local <= this_visitCounts_addr_reg_340;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            searcher_visitCounts_address0_local <= ap_const_lv64_0(13 - 1 downto 0);
        else 
            searcher_visitCounts_address0_local <= "XXXXXXXXXXXXX";
        end if; 
    end process;


    searcher_visitCounts_ce0_assign_proc : process(ap_CS_fsm_state12, grp_search_fu_247_this_visitCounts_ce0, ap_CS_fsm_state9, searcher_visitCounts_ce0_local)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            searcher_visitCounts_ce0 <= grp_search_fu_247_this_visitCounts_ce0;
        else 
            searcher_visitCounts_ce0 <= searcher_visitCounts_ce0_local;
        end if; 
    end process;


    searcher_visitCounts_ce0_local_assign_proc : process(strm_in_empty_n, ap_CS_fsm_state7, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or ((strm_in_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7)))) then 
            searcher_visitCounts_ce0_local <= ap_const_logic_1;
        else 
            searcher_visitCounts_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    searcher_visitCounts_d0_assign_proc : process(ap_CS_fsm_state12, grp_search_fu_247_this_visitCounts_d0, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            searcher_visitCounts_d0 <= grp_search_fu_247_this_visitCounts_d0;
        else 
            searcher_visitCounts_d0 <= ap_const_lv32_0;
        end if; 
    end process;


    searcher_visitCounts_we0_assign_proc : process(ap_CS_fsm_state12, grp_search_fu_247_this_visitCounts_we0, ap_CS_fsm_state9, searcher_visitCounts_we0_out)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            searcher_visitCounts_we0 <= grp_search_fu_247_this_visitCounts_we0;
        else 
            searcher_visitCounts_we0 <= (searcher_visitCounts_we0_out or ap_const_logic_0);
        end if; 
    end process;


    searcher_visitCounts_we0_local_assign_proc : process(strm_in_empty_n, ap_CS_fsm_state7, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or ((strm_in_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7)))) then 
            searcher_visitCounts_we0_local <= ap_const_logic_1;
        else 
            searcher_visitCounts_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    searcher_visitCounts_we0_out <= searcher_visitCounts_we0_local;

    strm_in_blk_n_assign_proc : process(strm_in_empty_n, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            strm_in_blk_n <= strm_in_empty_n;
        else 
            strm_in_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    strm_in_read_assign_proc : process(strm_in_empty_n, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8, grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_strm_in_read, grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_strm_in_read, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((((strm_in_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8)) or ((strm_in_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7)) or ((strm_in_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((strm_in_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5)))) then 
            strm_in_read <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            strm_in_read <= grp_dut_Pipeline_VITIS_LOOP_27_3_fu_240_strm_in_read;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            strm_in_read <= grp_dut_Pipeline_VITIS_LOOP_17_1_fu_233_strm_in_read;
        else 
            strm_in_read <= ap_const_logic_0;
        end if; 
    end process;


    strm_out_blk_n_assign_proc : process(strm_out_full_n, ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            strm_out_blk_n <= strm_out_full_n;
        else 
            strm_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    strm_out_din <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_search_fu_247_ap_return),32));

    strm_out_write_assign_proc : process(strm_out_full_n, ap_CS_fsm_state12, grp_search_fu_247_ap_done)
    begin
        if ((not(((strm_out_full_n = ap_const_logic_0) or (grp_search_fu_247_ap_done = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            strm_out_write <= ap_const_logic_1;
        else 
            strm_out_write <= ap_const_logic_0;
        end if; 
    end process;

    this_firstChilds_addr_reg_330 <= ap_const_lv64_0(13 - 1 downto 0);
    this_logVisitCounts_addr_reg_360 <= ap_const_lv64_0(13 - 1 downto 0);
    this_meanQ_addr_reg_345 <= ap_const_lv64_0(13 - 1 downto 0);
    this_numChildren_addr_reg_335 <= ap_const_lv64_0(13 - 1 downto 0);
    this_parents_addr_reg_325 <= ap_const_lv64_0(13 - 1 downto 0);
    this_terminals_addr_reg_350 <= ap_const_lv64_0(13 - 1 downto 0);
    this_triedMask_addr_reg_355 <= ap_const_lv64_0(13 - 1 downto 0);
    this_visitCounts_addr_reg_340 <= ap_const_lv64_0(13 - 1 downto 0);
end behav;
