-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dut_search is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    this_visitCounts_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    this_visitCounts_ce0 : OUT STD_LOGIC;
    this_visitCounts_we0 : OUT STD_LOGIC;
    this_visitCounts_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    this_visitCounts_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    this_meanQ_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    this_meanQ_ce0 : OUT STD_LOGIC;
    this_meanQ_we0 : OUT STD_LOGIC;
    this_meanQ_d0 : OUT STD_LOGIC_VECTOR (19 downto 0);
    this_meanQ_q0 : IN STD_LOGIC_VECTOR (19 downto 0);
    this_parents_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    this_parents_ce0 : OUT STD_LOGIC;
    this_parents_we0 : OUT STD_LOGIC;
    this_parents_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    this_parents_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    this_firstChilds_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    this_firstChilds_ce0 : OUT STD_LOGIC;
    this_firstChilds_we0 : OUT STD_LOGIC;
    this_firstChilds_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    this_firstChilds_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    this_numChildren_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    this_numChildren_ce0 : OUT STD_LOGIC;
    this_numChildren_we0 : OUT STD_LOGIC;
    this_numChildren_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    this_numChildren_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    this_nextSiblings_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    this_nextSiblings_ce0 : OUT STD_LOGIC;
    this_nextSiblings_we0 : OUT STD_LOGIC;
    this_nextSiblings_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    this_nextSiblings_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    this_numLegalActions_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    this_numLegalActions_ce0 : OUT STD_LOGIC;
    this_numLegalActions_we0 : OUT STD_LOGIC;
    this_numLegalActions_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    this_numLegalActions_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    this_terminals_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    this_terminals_ce0 : OUT STD_LOGIC;
    this_terminals_we0 : OUT STD_LOGIC;
    this_terminals_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    this_terminals_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    this_childActions_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    this_childActions_ce0 : OUT STD_LOGIC;
    this_childActions_we0 : OUT STD_LOGIC;
    this_childActions_d0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    this_childActions_q0 : IN STD_LOGIC_VECTOR (5 downto 0);
    this_triedMask_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    this_triedMask_ce0 : OUT STD_LOGIC;
    this_triedMask_we0 : OUT STD_LOGIC;
    this_triedMask_d0 : OUT STD_LOGIC_VECTOR (48 downto 0);
    this_triedMask_q0 : IN STD_LOGIC_VECTOR (48 downto 0);
    this_isREDs_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    this_isREDs_ce0 : OUT STD_LOGIC;
    this_isREDs_we0 : OUT STD_LOGIC;
    this_isREDs_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    this_isREDs_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    this_logVisitCounts_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    this_logVisitCounts_ce0 : OUT STD_LOGIC;
    this_logVisitCounts_we0 : OUT STD_LOGIC;
    this_logVisitCounts_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    this_logVisitCounts_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    this_rng_read : IN STD_LOGIC_VECTOR (5 downto 0);
    boardState_isPlayer1Turn_s : IN STD_LOGIC_VECTOR (0 downto 0);
    boardState_lastMove_s : IN STD_LOGIC_VECTOR (31 downto 0);
    boardState_player1_s : IN STD_LOGIC_VECTOR (48 downto 0);
    boardState_player2_s : IN STD_LOGIC_VECTOR (48 downto 0);
    isRED : IN STD_LOGIC_VECTOR (0 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (5 downto 0) );
end;


architecture behav of dut_search is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (8 downto 0) := "000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (8 downto 0) := "000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (8 downto 0) := "000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (8 downto 0) := "000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (8 downto 0) := "001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (8 downto 0) := "010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv49_1FFFFFFFFFFFF : STD_LOGIC_VECTOR (48 downto 0) := "1111111111111111111111111111111111111111111111111";
    constant ap_const_lv13_1388 : STD_LOGIC_VECTOR (12 downto 0) := "1001110001000";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal gameState_legalActionMap_fu_276_p2 : STD_LOGIC_VECTOR (48 downto 0);
    signal gameState_legalActionMap_reg_399 : STD_LOGIC_VECTOR (48 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal this_firstChilds_addr_reg_415 : STD_LOGIC_VECTOR (12 downto 0);
    signal bestChildNode_reg_429 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal grp_search_Pipeline_VITIS_LOOP_42_1_fu_208_ap_start : STD_LOGIC;
    signal grp_search_Pipeline_VITIS_LOOP_42_1_fu_208_ap_done : STD_LOGIC;
    signal grp_search_Pipeline_VITIS_LOOP_42_1_fu_208_ap_idle : STD_LOGIC;
    signal grp_search_Pipeline_VITIS_LOOP_42_1_fu_208_ap_ready : STD_LOGIC;
    signal grp_search_Pipeline_VITIS_LOOP_42_1_fu_208_numLegalActions_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_search_Pipeline_VITIS_LOOP_42_1_fu_208_numLegalActions_out_ap_vld : STD_LOGIC;
    signal grp_forward_fu_214_ap_start : STD_LOGIC;
    signal grp_forward_fu_214_ap_done : STD_LOGIC;
    signal grp_forward_fu_214_ap_idle : STD_LOGIC;
    signal grp_forward_fu_214_ap_ready : STD_LOGIC;
    signal grp_forward_fu_214_this_visitCounts_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_forward_fu_214_this_visitCounts_ce0 : STD_LOGIC;
    signal grp_forward_fu_214_this_visitCounts_we0 : STD_LOGIC;
    signal grp_forward_fu_214_this_visitCounts_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_forward_fu_214_this_meanQ_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_forward_fu_214_this_meanQ_ce0 : STD_LOGIC;
    signal grp_forward_fu_214_this_meanQ_we0 : STD_LOGIC;
    signal grp_forward_fu_214_this_meanQ_d0 : STD_LOGIC_VECTOR (19 downto 0);
    signal grp_forward_fu_214_this_parents_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_forward_fu_214_this_parents_ce0 : STD_LOGIC;
    signal grp_forward_fu_214_this_parents_we0 : STD_LOGIC;
    signal grp_forward_fu_214_this_parents_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_forward_fu_214_this_firstChilds_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_forward_fu_214_this_firstChilds_ce0 : STD_LOGIC;
    signal grp_forward_fu_214_this_firstChilds_we0 : STD_LOGIC;
    signal grp_forward_fu_214_this_firstChilds_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_forward_fu_214_this_numChildren_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_forward_fu_214_this_numChildren_ce0 : STD_LOGIC;
    signal grp_forward_fu_214_this_numChildren_we0 : STD_LOGIC;
    signal grp_forward_fu_214_this_numChildren_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_forward_fu_214_this_nextSiblings_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_forward_fu_214_this_nextSiblings_ce0 : STD_LOGIC;
    signal grp_forward_fu_214_this_nextSiblings_we0 : STD_LOGIC;
    signal grp_forward_fu_214_this_nextSiblings_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_forward_fu_214_this_numLegalActions_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_forward_fu_214_this_numLegalActions_ce0 : STD_LOGIC;
    signal grp_forward_fu_214_this_numLegalActions_we0 : STD_LOGIC;
    signal grp_forward_fu_214_this_numLegalActions_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_forward_fu_214_this_terminals_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_forward_fu_214_this_terminals_ce0 : STD_LOGIC;
    signal grp_forward_fu_214_this_terminals_we0 : STD_LOGIC;
    signal grp_forward_fu_214_this_terminals_d0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_forward_fu_214_this_childActions_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_forward_fu_214_this_childActions_ce0 : STD_LOGIC;
    signal grp_forward_fu_214_this_childActions_we0 : STD_LOGIC;
    signal grp_forward_fu_214_this_childActions_d0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_forward_fu_214_this_triedMask_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_forward_fu_214_this_triedMask_ce0 : STD_LOGIC;
    signal grp_forward_fu_214_this_triedMask_we0 : STD_LOGIC;
    signal grp_forward_fu_214_this_triedMask_d0 : STD_LOGIC_VECTOR (48 downto 0);
    signal grp_forward_fu_214_this_isREDs_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_forward_fu_214_this_isREDs_ce0 : STD_LOGIC;
    signal grp_forward_fu_214_this_isREDs_we0 : STD_LOGIC;
    signal grp_forward_fu_214_this_isREDs_d0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_forward_fu_214_this_logVisitCounts_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_forward_fu_214_this_logVisitCounts_ce0 : STD_LOGIC;
    signal grp_forward_fu_214_this_logVisitCounts_we0 : STD_LOGIC;
    signal grp_forward_fu_214_this_logVisitCounts_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_forward_fu_214_ap_return_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_forward_fu_214_ap_return_1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_search_Pipeline_VITIS_LOOP_27_1_fu_255_ap_start : STD_LOGIC;
    signal grp_search_Pipeline_VITIS_LOOP_27_1_fu_255_ap_done : STD_LOGIC;
    signal grp_search_Pipeline_VITIS_LOOP_27_1_fu_255_ap_idle : STD_LOGIC;
    signal grp_search_Pipeline_VITIS_LOOP_27_1_fu_255_ap_ready : STD_LOGIC;
    signal grp_search_Pipeline_VITIS_LOOP_27_1_fu_255_this_visitCounts_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_search_Pipeline_VITIS_LOOP_27_1_fu_255_this_visitCounts_ce0 : STD_LOGIC;
    signal grp_search_Pipeline_VITIS_LOOP_27_1_fu_255_this_nextSiblings_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_search_Pipeline_VITIS_LOOP_27_1_fu_255_this_nextSiblings_ce0 : STD_LOGIC;
    signal grp_search_Pipeline_VITIS_LOOP_27_1_fu_255_bestChildNode_out : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_search_Pipeline_VITIS_LOOP_27_1_fu_255_bestChildNode_out_ap_vld : STD_LOGIC;
    signal grp_search_Pipeline_VITIS_LOOP_42_1_fu_208_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_forward_fu_214_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln46_fu_305_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal this_parents_we0_out : STD_LOGIC;
    signal this_firstChilds_we0_out : STD_LOGIC;
    signal this_numLegalActions_we0_out : STD_LOGIC;
    signal this_isREDs_we0_out : STD_LOGIC;
    signal grp_search_Pipeline_VITIS_LOOP_27_1_fu_255_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal bestChildNode_loc_fu_92 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln36_fu_351_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_2_fu_80 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    signal i_3_fu_311_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal this_rng_0_fu_84 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal zext_ln64_fu_266_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal this_nextFree_0_fu_88 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal this_parents_we0_local : STD_LOGIC;
    signal this_parents_ce0_local : STD_LOGIC;
    signal this_firstChilds_we0_local : STD_LOGIC;
    signal this_firstChilds_ce0_local : STD_LOGIC;
    signal this_firstChilds_address0_local : STD_LOGIC_VECTOR (12 downto 0);
    signal this_isREDs_we0_local : STD_LOGIC;
    signal this_isREDs_ce0_local : STD_LOGIC;
    signal this_numLegalActions_we0_local : STD_LOGIC;
    signal this_numLegalActions_ce0_local : STD_LOGIC;
    signal this_childActions_ce0_local : STD_LOGIC;
    signal or_ln23_fu_270_p2 : STD_LOGIC_VECTOR (48 downto 0);
    signal ap_return_preg : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component dut_search_Pipeline_VITIS_LOOP_42_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        gameState_legalActionMap : IN STD_LOGIC_VECTOR (48 downto 0);
        numLegalActions_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        numLegalActions_out_ap_vld : OUT STD_LOGIC );
    end component;


    component dut_forward IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        this_visitCounts_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        this_visitCounts_ce0 : OUT STD_LOGIC;
        this_visitCounts_we0 : OUT STD_LOGIC;
        this_visitCounts_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        this_visitCounts_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        this_meanQ_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        this_meanQ_ce0 : OUT STD_LOGIC;
        this_meanQ_we0 : OUT STD_LOGIC;
        this_meanQ_d0 : OUT STD_LOGIC_VECTOR (19 downto 0);
        this_meanQ_q0 : IN STD_LOGIC_VECTOR (19 downto 0);
        this_parents_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        this_parents_ce0 : OUT STD_LOGIC;
        this_parents_we0 : OUT STD_LOGIC;
        this_parents_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        this_parents_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        this_firstChilds_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        this_firstChilds_ce0 : OUT STD_LOGIC;
        this_firstChilds_we0 : OUT STD_LOGIC;
        this_firstChilds_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        this_firstChilds_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        this_numChildren_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        this_numChildren_ce0 : OUT STD_LOGIC;
        this_numChildren_we0 : OUT STD_LOGIC;
        this_numChildren_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        this_numChildren_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        this_nextSiblings_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        this_nextSiblings_ce0 : OUT STD_LOGIC;
        this_nextSiblings_we0 : OUT STD_LOGIC;
        this_nextSiblings_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        this_nextSiblings_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        this_numLegalActions_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        this_numLegalActions_ce0 : OUT STD_LOGIC;
        this_numLegalActions_we0 : OUT STD_LOGIC;
        this_numLegalActions_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        this_numLegalActions_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        this_terminals_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        this_terminals_ce0 : OUT STD_LOGIC;
        this_terminals_we0 : OUT STD_LOGIC;
        this_terminals_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        this_terminals_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
        this_childActions_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        this_childActions_ce0 : OUT STD_LOGIC;
        this_childActions_we0 : OUT STD_LOGIC;
        this_childActions_d0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        this_childActions_q0 : IN STD_LOGIC_VECTOR (5 downto 0);
        this_triedMask_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        this_triedMask_ce0 : OUT STD_LOGIC;
        this_triedMask_we0 : OUT STD_LOGIC;
        this_triedMask_d0 : OUT STD_LOGIC_VECTOR (48 downto 0);
        this_triedMask_q0 : IN STD_LOGIC_VECTOR (48 downto 0);
        this_isREDs_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        this_isREDs_ce0 : OUT STD_LOGIC;
        this_isREDs_we0 : OUT STD_LOGIC;
        this_isREDs_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        this_isREDs_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
        this_logVisitCounts_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        this_logVisitCounts_ce0 : OUT STD_LOGIC;
        this_logVisitCounts_we0 : OUT STD_LOGIC;
        this_logVisitCounts_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        this_logVisitCounts_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        this_nextFree_read : IN STD_LOGIC_VECTOR (31 downto 0);
        this_rng_read : IN STD_LOGIC_VECTOR (63 downto 0);
        gameState_legalActionMap : IN STD_LOGIC_VECTOR (48 downto 0);
        gameState_hexGame_isPlayer1Turn_s : IN STD_LOGIC_VECTOR (0 downto 0);
        gameState_hexGame_lastMove_s : IN STD_LOGIC_VECTOR (31 downto 0);
        gameState_hexGame_player1_s : IN STD_LOGIC_VECTOR (48 downto 0);
        gameState_hexGame_player2_s : IN STD_LOGIC_VECTOR (48 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component dut_search_Pipeline_VITIS_LOOP_27_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        bestChildNode_3 : IN STD_LOGIC_VECTOR (31 downto 0);
        this_visitCounts_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        this_visitCounts_ce0 : OUT STD_LOGIC;
        this_visitCounts_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        this_nextSiblings_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        this_nextSiblings_ce0 : OUT STD_LOGIC;
        this_nextSiblings_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        bestChildNode_out : OUT STD_LOGIC_VECTOR (12 downto 0);
        bestChildNode_out_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_search_Pipeline_VITIS_LOOP_42_1_fu_208 : component dut_search_Pipeline_VITIS_LOOP_42_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_search_Pipeline_VITIS_LOOP_42_1_fu_208_ap_start,
        ap_done => grp_search_Pipeline_VITIS_LOOP_42_1_fu_208_ap_done,
        ap_idle => grp_search_Pipeline_VITIS_LOOP_42_1_fu_208_ap_idle,
        ap_ready => grp_search_Pipeline_VITIS_LOOP_42_1_fu_208_ap_ready,
        gameState_legalActionMap => gameState_legalActionMap_reg_399,
        numLegalActions_out => grp_search_Pipeline_VITIS_LOOP_42_1_fu_208_numLegalActions_out,
        numLegalActions_out_ap_vld => grp_search_Pipeline_VITIS_LOOP_42_1_fu_208_numLegalActions_out_ap_vld);

    grp_forward_fu_214 : component dut_forward
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_forward_fu_214_ap_start,
        ap_done => grp_forward_fu_214_ap_done,
        ap_idle => grp_forward_fu_214_ap_idle,
        ap_ready => grp_forward_fu_214_ap_ready,
        this_visitCounts_address0 => grp_forward_fu_214_this_visitCounts_address0,
        this_visitCounts_ce0 => grp_forward_fu_214_this_visitCounts_ce0,
        this_visitCounts_we0 => grp_forward_fu_214_this_visitCounts_we0,
        this_visitCounts_d0 => grp_forward_fu_214_this_visitCounts_d0,
        this_visitCounts_q0 => this_visitCounts_q0,
        this_meanQ_address0 => grp_forward_fu_214_this_meanQ_address0,
        this_meanQ_ce0 => grp_forward_fu_214_this_meanQ_ce0,
        this_meanQ_we0 => grp_forward_fu_214_this_meanQ_we0,
        this_meanQ_d0 => grp_forward_fu_214_this_meanQ_d0,
        this_meanQ_q0 => this_meanQ_q0,
        this_parents_address0 => grp_forward_fu_214_this_parents_address0,
        this_parents_ce0 => grp_forward_fu_214_this_parents_ce0,
        this_parents_we0 => grp_forward_fu_214_this_parents_we0,
        this_parents_d0 => grp_forward_fu_214_this_parents_d0,
        this_parents_q0 => this_parents_q0,
        this_firstChilds_address0 => grp_forward_fu_214_this_firstChilds_address0,
        this_firstChilds_ce0 => grp_forward_fu_214_this_firstChilds_ce0,
        this_firstChilds_we0 => grp_forward_fu_214_this_firstChilds_we0,
        this_firstChilds_d0 => grp_forward_fu_214_this_firstChilds_d0,
        this_firstChilds_q0 => this_firstChilds_q0,
        this_numChildren_address0 => grp_forward_fu_214_this_numChildren_address0,
        this_numChildren_ce0 => grp_forward_fu_214_this_numChildren_ce0,
        this_numChildren_we0 => grp_forward_fu_214_this_numChildren_we0,
        this_numChildren_d0 => grp_forward_fu_214_this_numChildren_d0,
        this_numChildren_q0 => this_numChildren_q0,
        this_nextSiblings_address0 => grp_forward_fu_214_this_nextSiblings_address0,
        this_nextSiblings_ce0 => grp_forward_fu_214_this_nextSiblings_ce0,
        this_nextSiblings_we0 => grp_forward_fu_214_this_nextSiblings_we0,
        this_nextSiblings_d0 => grp_forward_fu_214_this_nextSiblings_d0,
        this_nextSiblings_q0 => this_nextSiblings_q0,
        this_numLegalActions_address0 => grp_forward_fu_214_this_numLegalActions_address0,
        this_numLegalActions_ce0 => grp_forward_fu_214_this_numLegalActions_ce0,
        this_numLegalActions_we0 => grp_forward_fu_214_this_numLegalActions_we0,
        this_numLegalActions_d0 => grp_forward_fu_214_this_numLegalActions_d0,
        this_numLegalActions_q0 => this_numLegalActions_q0,
        this_terminals_address0 => grp_forward_fu_214_this_terminals_address0,
        this_terminals_ce0 => grp_forward_fu_214_this_terminals_ce0,
        this_terminals_we0 => grp_forward_fu_214_this_terminals_we0,
        this_terminals_d0 => grp_forward_fu_214_this_terminals_d0,
        this_terminals_q0 => this_terminals_q0,
        this_childActions_address0 => grp_forward_fu_214_this_childActions_address0,
        this_childActions_ce0 => grp_forward_fu_214_this_childActions_ce0,
        this_childActions_we0 => grp_forward_fu_214_this_childActions_we0,
        this_childActions_d0 => grp_forward_fu_214_this_childActions_d0,
        this_childActions_q0 => this_childActions_q0,
        this_triedMask_address0 => grp_forward_fu_214_this_triedMask_address0,
        this_triedMask_ce0 => grp_forward_fu_214_this_triedMask_ce0,
        this_triedMask_we0 => grp_forward_fu_214_this_triedMask_we0,
        this_triedMask_d0 => grp_forward_fu_214_this_triedMask_d0,
        this_triedMask_q0 => this_triedMask_q0,
        this_isREDs_address0 => grp_forward_fu_214_this_isREDs_address0,
        this_isREDs_ce0 => grp_forward_fu_214_this_isREDs_ce0,
        this_isREDs_we0 => grp_forward_fu_214_this_isREDs_we0,
        this_isREDs_d0 => grp_forward_fu_214_this_isREDs_d0,
        this_isREDs_q0 => this_isREDs_q0,
        this_logVisitCounts_address0 => grp_forward_fu_214_this_logVisitCounts_address0,
        this_logVisitCounts_ce0 => grp_forward_fu_214_this_logVisitCounts_ce0,
        this_logVisitCounts_we0 => grp_forward_fu_214_this_logVisitCounts_we0,
        this_logVisitCounts_d0 => grp_forward_fu_214_this_logVisitCounts_d0,
        this_logVisitCounts_q0 => this_logVisitCounts_q0,
        this_nextFree_read => this_nextFree_0_fu_88,
        this_rng_read => this_rng_0_fu_84,
        gameState_legalActionMap => gameState_legalActionMap_reg_399,
        gameState_hexGame_isPlayer1Turn_s => boardState_isPlayer1Turn_s,
        gameState_hexGame_lastMove_s => boardState_lastMove_s,
        gameState_hexGame_player1_s => boardState_player1_s,
        gameState_hexGame_player2_s => boardState_player2_s,
        ap_return_0 => grp_forward_fu_214_ap_return_0,
        ap_return_1 => grp_forward_fu_214_ap_return_1);

    grp_search_Pipeline_VITIS_LOOP_27_1_fu_255 : component dut_search_Pipeline_VITIS_LOOP_27_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_search_Pipeline_VITIS_LOOP_27_1_fu_255_ap_start,
        ap_done => grp_search_Pipeline_VITIS_LOOP_27_1_fu_255_ap_done,
        ap_idle => grp_search_Pipeline_VITIS_LOOP_27_1_fu_255_ap_idle,
        ap_ready => grp_search_Pipeline_VITIS_LOOP_27_1_fu_255_ap_ready,
        bestChildNode_3 => bestChildNode_reg_429,
        this_visitCounts_address0 => grp_search_Pipeline_VITIS_LOOP_27_1_fu_255_this_visitCounts_address0,
        this_visitCounts_ce0 => grp_search_Pipeline_VITIS_LOOP_27_1_fu_255_this_visitCounts_ce0,
        this_visitCounts_q0 => this_visitCounts_q0,
        this_nextSiblings_address0 => grp_search_Pipeline_VITIS_LOOP_27_1_fu_255_this_nextSiblings_address0,
        this_nextSiblings_ce0 => grp_search_Pipeline_VITIS_LOOP_27_1_fu_255_this_nextSiblings_ce0,
        this_nextSiblings_q0 => this_nextSiblings_q0,
        bestChildNode_out => grp_search_Pipeline_VITIS_LOOP_27_1_fu_255_bestChildNode_out,
        bestChildNode_out_ap_vld => grp_search_Pipeline_VITIS_LOOP_27_1_fu_255_bestChildNode_out_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_return_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_preg <= ap_const_lv6_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                    ap_return_preg <= this_childActions_q0;
                end if; 
            end if;
        end if;
    end process;


    grp_forward_fu_214_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_forward_fu_214_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln46_fu_305_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                    grp_forward_fu_214_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_forward_fu_214_ap_ready = ap_const_logic_1)) then 
                    grp_forward_fu_214_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_search_Pipeline_VITIS_LOOP_27_1_fu_255_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_search_Pipeline_VITIS_LOOP_27_1_fu_255_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    grp_search_Pipeline_VITIS_LOOP_27_1_fu_255_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_search_Pipeline_VITIS_LOOP_27_1_fu_255_ap_ready = ap_const_logic_1)) then 
                    grp_search_Pipeline_VITIS_LOOP_27_1_fu_255_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_search_Pipeline_VITIS_LOOP_42_1_fu_208_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_search_Pipeline_VITIS_LOOP_42_1_fu_208_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_search_Pipeline_VITIS_LOOP_42_1_fu_208_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_search_Pipeline_VITIS_LOOP_42_1_fu_208_ap_ready = ap_const_logic_1)) then 
                    grp_search_Pipeline_VITIS_LOOP_42_1_fu_208_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_2_fu_80_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_2_fu_80 <= ap_const_lv13_0;
            elsif (((icmp_ln46_fu_305_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                i_2_fu_80 <= i_3_fu_311_p2;
            end if; 
        end if;
    end process;

    this_nextFree_0_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                this_nextFree_0_fu_88 <= ap_const_lv32_1;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_forward_fu_214_ap_done = ap_const_logic_1))) then 
                this_nextFree_0_fu_88 <= grp_forward_fu_214_ap_return_0;
            end if; 
        end if;
    end process;

    this_rng_0_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                this_rng_0_fu_84 <= zext_ln64_fu_266_p1;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_forward_fu_214_ap_done = ap_const_logic_1))) then 
                this_rng_0_fu_84 <= grp_forward_fu_214_ap_return_1;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_search_Pipeline_VITIS_LOOP_27_1_fu_255_bestChildNode_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                bestChildNode_loc_fu_92 <= grp_search_Pipeline_VITIS_LOOP_27_1_fu_255_bestChildNode_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                bestChildNode_reg_429 <= this_firstChilds_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                gameState_legalActionMap_reg_399 <= gameState_legalActionMap_fu_276_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_search_Pipeline_VITIS_LOOP_42_1_fu_208_ap_done, grp_forward_fu_214_ap_done, grp_search_Pipeline_VITIS_LOOP_27_1_fu_255_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state4, icmp_ln46_fu_305_p2, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_search_Pipeline_VITIS_LOOP_42_1_fu_208_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((icmp_ln46_fu_305_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_forward_fu_214_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((grp_search_Pipeline_VITIS_LOOP_27_1_fu_255_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_search_Pipeline_VITIS_LOOP_42_1_fu_208_ap_done)
    begin
        if ((grp_search_Pipeline_VITIS_LOOP_42_1_fu_208_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_forward_fu_214_ap_done)
    begin
        if ((grp_forward_fu_214_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_ST_fsm_state7_blk_assign_proc : process(grp_search_Pipeline_VITIS_LOOP_27_1_fu_255_ap_done)
    begin
        if ((grp_search_Pipeline_VITIS_LOOP_27_1_fu_255_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_assign_proc : process(this_childActions_q0, ap_return_preg, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            ap_return <= this_childActions_q0;
        else 
            ap_return <= ap_return_preg;
        end if; 
    end process;

    gameState_legalActionMap_fu_276_p2 <= (or_ln23_fu_270_p2 xor ap_const_lv49_1FFFFFFFFFFFF);
    grp_forward_fu_214_ap_start <= grp_forward_fu_214_ap_start_reg;
    grp_search_Pipeline_VITIS_LOOP_27_1_fu_255_ap_start <= grp_search_Pipeline_VITIS_LOOP_27_1_fu_255_ap_start_reg;
    grp_search_Pipeline_VITIS_LOOP_42_1_fu_208_ap_start <= grp_search_Pipeline_VITIS_LOOP_42_1_fu_208_ap_start_reg;
    i_3_fu_311_p2 <= std_logic_vector(unsigned(i_2_fu_80) + unsigned(ap_const_lv13_1));
    icmp_ln46_fu_305_p2 <= "1" when (i_2_fu_80 = ap_const_lv13_1388) else "0";
    or_ln23_fu_270_p2 <= (boardState_player2_s or boardState_player1_s);

    this_childActions_address0_assign_proc : process(grp_forward_fu_214_this_childActions_address0, ap_CS_fsm_state5, zext_ln36_fu_351_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            this_childActions_address0 <= grp_forward_fu_214_this_childActions_address0;
        else 
            this_childActions_address0 <= zext_ln36_fu_351_p1(13 - 1 downto 0);
        end if; 
    end process;


    this_childActions_ce0_assign_proc : process(grp_forward_fu_214_this_childActions_ce0, ap_CS_fsm_state5, this_childActions_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            this_childActions_ce0 <= grp_forward_fu_214_this_childActions_ce0;
        else 
            this_childActions_ce0 <= this_childActions_ce0_local;
        end if; 
    end process;


    this_childActions_ce0_local_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            this_childActions_ce0_local <= ap_const_logic_1;
        else 
            this_childActions_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    this_childActions_d0 <= grp_forward_fu_214_this_childActions_d0;

    this_childActions_we0_assign_proc : process(grp_forward_fu_214_this_childActions_we0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            this_childActions_we0 <= grp_forward_fu_214_this_childActions_we0;
        else 
            this_childActions_we0 <= ap_const_logic_0;
        end if; 
    end process;

    this_firstChilds_addr_reg_415 <= ap_const_lv64_0(13 - 1 downto 0);

    this_firstChilds_address0_assign_proc : process(grp_forward_fu_214_this_firstChilds_address0, ap_CS_fsm_state5, this_firstChilds_address0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            this_firstChilds_address0 <= grp_forward_fu_214_this_firstChilds_address0;
        else 
            this_firstChilds_address0 <= this_firstChilds_address0_local;
        end if; 
    end process;


    this_firstChilds_address0_local_assign_proc : process(ap_CS_fsm_state3, this_firstChilds_addr_reg_415, ap_CS_fsm_state4, icmp_ln46_fu_305_p2)
    begin
        if (((icmp_ln46_fu_305_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            this_firstChilds_address0_local <= this_firstChilds_addr_reg_415;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            this_firstChilds_address0_local <= ap_const_lv64_0(13 - 1 downto 0);
        else 
            this_firstChilds_address0_local <= "XXXXXXXXXXXXX";
        end if; 
    end process;


    this_firstChilds_ce0_assign_proc : process(grp_forward_fu_214_this_firstChilds_ce0, ap_CS_fsm_state5, this_firstChilds_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            this_firstChilds_ce0 <= grp_forward_fu_214_this_firstChilds_ce0;
        else 
            this_firstChilds_ce0 <= this_firstChilds_ce0_local;
        end if; 
    end process;


    this_firstChilds_ce0_local_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state4, icmp_ln46_fu_305_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or ((icmp_ln46_fu_305_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4)))) then 
            this_firstChilds_ce0_local <= ap_const_logic_1;
        else 
            this_firstChilds_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    this_firstChilds_d0_assign_proc : process(grp_forward_fu_214_this_firstChilds_d0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            this_firstChilds_d0 <= grp_forward_fu_214_this_firstChilds_d0;
        else 
            this_firstChilds_d0 <= ap_const_lv32_FFFFFFFF;
        end if; 
    end process;


    this_firstChilds_we0_assign_proc : process(grp_forward_fu_214_this_firstChilds_we0, ap_CS_fsm_state5, this_firstChilds_we0_out)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            this_firstChilds_we0 <= grp_forward_fu_214_this_firstChilds_we0;
        else 
            this_firstChilds_we0 <= (this_firstChilds_we0_out or ap_const_logic_0);
        end if; 
    end process;


    this_firstChilds_we0_local_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            this_firstChilds_we0_local <= ap_const_logic_1;
        else 
            this_firstChilds_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    this_firstChilds_we0_out <= this_firstChilds_we0_local;

    this_isREDs_address0_assign_proc : process(grp_forward_fu_214_this_isREDs_address0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            this_isREDs_address0 <= grp_forward_fu_214_this_isREDs_address0;
        else 
            this_isREDs_address0 <= ap_const_lv64_0(13 - 1 downto 0);
        end if; 
    end process;


    this_isREDs_ce0_assign_proc : process(grp_forward_fu_214_this_isREDs_ce0, ap_CS_fsm_state5, this_isREDs_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            this_isREDs_ce0 <= grp_forward_fu_214_this_isREDs_ce0;
        else 
            this_isREDs_ce0 <= this_isREDs_ce0_local;
        end if; 
    end process;


    this_isREDs_ce0_local_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            this_isREDs_ce0_local <= ap_const_logic_1;
        else 
            this_isREDs_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    this_isREDs_d0_assign_proc : process(isRED, grp_forward_fu_214_this_isREDs_d0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            this_isREDs_d0 <= grp_forward_fu_214_this_isREDs_d0;
        else 
            this_isREDs_d0 <= isRED;
        end if; 
    end process;


    this_isREDs_we0_assign_proc : process(grp_forward_fu_214_this_isREDs_we0, ap_CS_fsm_state5, this_isREDs_we0_out)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            this_isREDs_we0 <= grp_forward_fu_214_this_isREDs_we0;
        else 
            this_isREDs_we0 <= (this_isREDs_we0_out or ap_const_logic_0);
        end if; 
    end process;


    this_isREDs_we0_local_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            this_isREDs_we0_local <= ap_const_logic_1;
        else 
            this_isREDs_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    this_isREDs_we0_out <= this_isREDs_we0_local;
    this_logVisitCounts_address0 <= grp_forward_fu_214_this_logVisitCounts_address0;
    this_logVisitCounts_ce0 <= grp_forward_fu_214_this_logVisitCounts_ce0;
    this_logVisitCounts_d0 <= grp_forward_fu_214_this_logVisitCounts_d0;
    this_logVisitCounts_we0 <= grp_forward_fu_214_this_logVisitCounts_we0;
    this_meanQ_address0 <= grp_forward_fu_214_this_meanQ_address0;
    this_meanQ_ce0 <= grp_forward_fu_214_this_meanQ_ce0;
    this_meanQ_d0 <= grp_forward_fu_214_this_meanQ_d0;
    this_meanQ_we0 <= grp_forward_fu_214_this_meanQ_we0;

    this_nextSiblings_address0_assign_proc : process(grp_forward_fu_214_this_nextSiblings_address0, grp_search_Pipeline_VITIS_LOOP_27_1_fu_255_this_nextSiblings_address0, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            this_nextSiblings_address0 <= grp_search_Pipeline_VITIS_LOOP_27_1_fu_255_this_nextSiblings_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            this_nextSiblings_address0 <= grp_forward_fu_214_this_nextSiblings_address0;
        else 
            this_nextSiblings_address0 <= "XXXXXXXXXXXXX";
        end if; 
    end process;


    this_nextSiblings_ce0_assign_proc : process(grp_forward_fu_214_this_nextSiblings_ce0, grp_search_Pipeline_VITIS_LOOP_27_1_fu_255_this_nextSiblings_ce0, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            this_nextSiblings_ce0 <= grp_search_Pipeline_VITIS_LOOP_27_1_fu_255_this_nextSiblings_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            this_nextSiblings_ce0 <= grp_forward_fu_214_this_nextSiblings_ce0;
        else 
            this_nextSiblings_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    this_nextSiblings_d0 <= grp_forward_fu_214_this_nextSiblings_d0;

    this_nextSiblings_we0_assign_proc : process(grp_forward_fu_214_this_nextSiblings_we0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            this_nextSiblings_we0 <= grp_forward_fu_214_this_nextSiblings_we0;
        else 
            this_nextSiblings_we0 <= ap_const_logic_0;
        end if; 
    end process;

    this_numChildren_address0 <= grp_forward_fu_214_this_numChildren_address0;
    this_numChildren_ce0 <= grp_forward_fu_214_this_numChildren_ce0;
    this_numChildren_d0 <= grp_forward_fu_214_this_numChildren_d0;
    this_numChildren_we0 <= grp_forward_fu_214_this_numChildren_we0;

    this_numLegalActions_address0_assign_proc : process(grp_forward_fu_214_this_numLegalActions_address0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            this_numLegalActions_address0 <= grp_forward_fu_214_this_numLegalActions_address0;
        else 
            this_numLegalActions_address0 <= ap_const_lv64_0(13 - 1 downto 0);
        end if; 
    end process;


    this_numLegalActions_ce0_assign_proc : process(grp_forward_fu_214_this_numLegalActions_ce0, ap_CS_fsm_state5, this_numLegalActions_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            this_numLegalActions_ce0 <= grp_forward_fu_214_this_numLegalActions_ce0;
        else 
            this_numLegalActions_ce0 <= this_numLegalActions_ce0_local;
        end if; 
    end process;


    this_numLegalActions_ce0_local_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            this_numLegalActions_ce0_local <= ap_const_logic_1;
        else 
            this_numLegalActions_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    this_numLegalActions_d0_assign_proc : process(grp_search_Pipeline_VITIS_LOOP_42_1_fu_208_numLegalActions_out, grp_forward_fu_214_this_numLegalActions_d0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            this_numLegalActions_d0 <= grp_forward_fu_214_this_numLegalActions_d0;
        else 
            this_numLegalActions_d0 <= grp_search_Pipeline_VITIS_LOOP_42_1_fu_208_numLegalActions_out;
        end if; 
    end process;


    this_numLegalActions_we0_assign_proc : process(grp_forward_fu_214_this_numLegalActions_we0, ap_CS_fsm_state5, this_numLegalActions_we0_out)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            this_numLegalActions_we0 <= grp_forward_fu_214_this_numLegalActions_we0;
        else 
            this_numLegalActions_we0 <= (this_numLegalActions_we0_out or ap_const_logic_0);
        end if; 
    end process;


    this_numLegalActions_we0_local_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            this_numLegalActions_we0_local <= ap_const_logic_1;
        else 
            this_numLegalActions_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    this_numLegalActions_we0_out <= this_numLegalActions_we0_local;

    this_parents_address0_assign_proc : process(grp_forward_fu_214_this_parents_address0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            this_parents_address0 <= grp_forward_fu_214_this_parents_address0;
        else 
            this_parents_address0 <= ap_const_lv64_0(13 - 1 downto 0);
        end if; 
    end process;


    this_parents_ce0_assign_proc : process(grp_forward_fu_214_this_parents_ce0, ap_CS_fsm_state5, this_parents_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            this_parents_ce0 <= grp_forward_fu_214_this_parents_ce0;
        else 
            this_parents_ce0 <= this_parents_ce0_local;
        end if; 
    end process;


    this_parents_ce0_local_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            this_parents_ce0_local <= ap_const_logic_1;
        else 
            this_parents_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    this_parents_d0_assign_proc : process(grp_forward_fu_214_this_parents_d0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            this_parents_d0 <= grp_forward_fu_214_this_parents_d0;
        else 
            this_parents_d0 <= ap_const_lv32_FFFFFFFF;
        end if; 
    end process;


    this_parents_we0_assign_proc : process(grp_forward_fu_214_this_parents_we0, ap_CS_fsm_state5, this_parents_we0_out)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            this_parents_we0 <= grp_forward_fu_214_this_parents_we0;
        else 
            this_parents_we0 <= (this_parents_we0_out or ap_const_logic_0);
        end if; 
    end process;


    this_parents_we0_local_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            this_parents_we0_local <= ap_const_logic_1;
        else 
            this_parents_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    this_parents_we0_out <= this_parents_we0_local;
    this_terminals_address0 <= grp_forward_fu_214_this_terminals_address0;
    this_terminals_ce0 <= grp_forward_fu_214_this_terminals_ce0;
    this_terminals_d0 <= grp_forward_fu_214_this_terminals_d0;
    this_terminals_we0 <= grp_forward_fu_214_this_terminals_we0;
    this_triedMask_address0 <= grp_forward_fu_214_this_triedMask_address0;
    this_triedMask_ce0 <= grp_forward_fu_214_this_triedMask_ce0;
    this_triedMask_d0 <= grp_forward_fu_214_this_triedMask_d0;
    this_triedMask_we0 <= grp_forward_fu_214_this_triedMask_we0;

    this_visitCounts_address0_assign_proc : process(grp_forward_fu_214_this_visitCounts_address0, grp_search_Pipeline_VITIS_LOOP_27_1_fu_255_this_visitCounts_address0, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            this_visitCounts_address0 <= grp_search_Pipeline_VITIS_LOOP_27_1_fu_255_this_visitCounts_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            this_visitCounts_address0 <= grp_forward_fu_214_this_visitCounts_address0;
        else 
            this_visitCounts_address0 <= "XXXXXXXXXXXXX";
        end if; 
    end process;


    this_visitCounts_ce0_assign_proc : process(grp_forward_fu_214_this_visitCounts_ce0, grp_search_Pipeline_VITIS_LOOP_27_1_fu_255_this_visitCounts_ce0, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            this_visitCounts_ce0 <= grp_search_Pipeline_VITIS_LOOP_27_1_fu_255_this_visitCounts_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            this_visitCounts_ce0 <= grp_forward_fu_214_this_visitCounts_ce0;
        else 
            this_visitCounts_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    this_visitCounts_d0 <= grp_forward_fu_214_this_visitCounts_d0;

    this_visitCounts_we0_assign_proc : process(grp_forward_fu_214_this_visitCounts_we0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            this_visitCounts_we0 <= grp_forward_fu_214_this_visitCounts_we0;
        else 
            this_visitCounts_we0 <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln36_fu_351_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(bestChildNode_loc_fu_92),64));
    zext_ln64_fu_266_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(this_rng_read),64));
end behav;
