-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dut_rollout_Pipeline_VITIS_LOOP_114_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    fill_4 : IN STD_LOGIC_VECTOR (48 downto 0);
    gameState_hexGame_player1_2 : IN STD_LOGIC_VECTOR (48 downto 0);
    prev_out : OUT STD_LOGIC_VECTOR (48 downto 0);
    prev_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of dut_rollout_Pipeline_VITIS_LOOP_114_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_24 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100100";
    constant ap_const_lv32_29 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101001";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv32_22 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100010";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_23 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100011";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv32_21 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100001";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_2A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101010";
    constant ap_const_lv32_2E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101110";
    constant ap_const_lv32_2B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101011";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln125_fu_500_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal prev_reg_121 : STD_LOGIC_VECTOR (48 downto 0);
    signal or_ln123_11_fu_494_p2 : STD_LOGIC_VECTOR (48 downto 0);
    signal ap_phi_mux_prev_phi_fu_124_p4 : STD_LOGIC_VECTOR (48 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal tmp_96_fu_142_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_97_fu_152_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_98_fu_162_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_99_fu_172_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_100_fu_182_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_109_fu_286_p4 : STD_LOGIC_VECTOR (40 downto 0);
    signal tmp_108_fu_262_p11 : STD_LOGIC_VECTOR (40 downto 0);
    signal tmp_s_fu_132_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_302_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln123_8_fu_296_p2 : STD_LOGIC_VECTOR (40 downto 0);
    signal trunc_ln123_fu_320_p1 : STD_LOGIC_VECTOR (40 downto 0);
    signal shl_ln123_1_fu_324_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal or_ln123_6_fu_310_p4 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_110_fu_338_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln123_7_fu_332_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_106_fu_242_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_101_fu_192_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_102_fu_202_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_103_fu_212_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_104_fu_222_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_105_fu_232_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_111_fu_380_p13 : STD_LOGIC_VECTOR (40 downto 0);
    signal and_ln123_2_fu_354_p12 : STD_LOGIC_VECTOR (40 downto 0);
    signal tmp_107_fu_252_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_112_fu_414_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln123_fu_408_p2 : STD_LOGIC_VECTOR (40 downto 0);
    signal trunc_ln123_4_fu_432_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal and_ln123_3_fu_436_p15 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp9_fu_422_p4 : STD_LOGIC_VECTOR (47 downto 0);
    signal or_ln123_9_fu_468_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp11_fu_474_p3 : STD_LOGIC_VECTOR (48 downto 0);
    signal tmp7_fu_346_p3 : STD_LOGIC_VECTOR (48 downto 0);
    signal or_ln123_10_fu_482_p2 : STD_LOGIC_VECTOR (48 downto 0);
    signal and_ln123_fu_488_p2 : STD_LOGIC_VECTOR (48 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component dut_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component dut_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln125_fu_500_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                prev_reg_121 <= or_ln123_11_fu_494_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    and_ln123_2_fu_354_p12 <= ((((((((((tmp_s_fu_132_p4 & ap_const_lv1_0) & tmp_96_fu_142_p4) & ap_const_lv1_0) & tmp_97_fu_152_p4) & ap_const_lv1_0) & tmp_98_fu_162_p4) & ap_const_lv1_0) & tmp_99_fu_172_p4) & ap_const_lv1_0) & tmp_100_fu_182_p4);
    and_ln123_3_fu_436_p15 <= (((((((((((((tmp_106_fu_242_p4 & ap_const_lv1_0) & tmp_101_fu_192_p4) & ap_const_lv1_0) & tmp_102_fu_202_p4) & ap_const_lv1_0) & tmp_103_fu_212_p4) & ap_const_lv1_0) & tmp_104_fu_222_p4) & ap_const_lv1_0) & tmp_105_fu_232_p4) & ap_const_lv1_0) & trunc_ln123_4_fu_432_p1) & ap_const_lv1_0);
    and_ln123_fu_488_p2 <= (or_ln123_10_fu_482_p2 and gameState_hexGame_player1_2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1_pp0_stage0_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start_int = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln125_fu_500_p2)
    begin
        if (((icmp_ln125_fu_500_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_phi_mux_prev_phi_fu_124_p4_assign_proc : process(ap_CS_fsm_state1, fill_4, prev_reg_121, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_phi_mux_prev_phi_fu_124_p4 <= fill_4;
        else 
            ap_phi_mux_prev_phi_fu_124_p4 <= prev_reg_121;
        end if; 
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln125_fu_500_p2 <= "1" when (or_ln123_11_fu_494_p2 = ap_phi_mux_prev_phi_fu_124_p4) else "0";
    or_ln123_10_fu_482_p2 <= (tmp7_fu_346_p3 or tmp11_fu_474_p3);
    or_ln123_11_fu_494_p2 <= (ap_phi_mux_prev_phi_fu_124_p4 or and_ln123_fu_488_p2);
    or_ln123_6_fu_310_p4 <= ((tmp_s_fu_132_p4 & tmp_fu_302_p3) & or_ln123_8_fu_296_p2);
    or_ln123_7_fu_332_p2 <= (shl_ln123_1_fu_324_p3 or or_ln123_6_fu_310_p4);
    or_ln123_8_fu_296_p2 <= (tmp_109_fu_286_p4 or tmp_108_fu_262_p11);
    or_ln123_9_fu_468_p2 <= (tmp9_fu_422_p4 or and_ln123_3_fu_436_p15);
    or_ln123_fu_408_p2 <= (tmp_111_fu_380_p13 or and_ln123_2_fu_354_p12);
    prev_out <= ap_phi_mux_prev_phi_fu_124_p4;

    prev_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln125_fu_500_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln125_fu_500_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            prev_out_ap_vld <= ap_const_logic_1;
        else 
            prev_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    shl_ln123_1_fu_324_p3 <= (trunc_ln123_fu_320_p1 & ap_const_lv7_0);
    tmp11_fu_474_p3 <= (tmp_112_fu_414_p3 & or_ln123_9_fu_468_p2);
    tmp7_fu_346_p3 <= (tmp_110_fu_338_p3 & or_ln123_7_fu_332_p2);
    tmp9_fu_422_p4 <= ((tmp_107_fu_252_p4 & tmp_112_fu_414_p3) & or_ln123_fu_408_p2);
    tmp_100_fu_182_p4 <= ap_phi_mux_prev_phi_fu_124_p4(6 downto 1);
    tmp_101_fu_192_p4 <= ap_phi_mux_prev_phi_fu_124_p4(40 downto 35);
    tmp_102_fu_202_p4 <= ap_phi_mux_prev_phi_fu_124_p4(33 downto 28);
    tmp_103_fu_212_p4 <= ap_phi_mux_prev_phi_fu_124_p4(26 downto 21);
    tmp_104_fu_222_p4 <= ap_phi_mux_prev_phi_fu_124_p4(19 downto 14);
    tmp_105_fu_232_p4 <= ap_phi_mux_prev_phi_fu_124_p4(12 downto 7);
    tmp_106_fu_242_p4 <= ap_phi_mux_prev_phi_fu_124_p4(46 downto 42);
    tmp_107_fu_252_p4 <= ap_phi_mux_prev_phi_fu_124_p4(48 downto 43);
    tmp_108_fu_262_p11 <= (((((((((tmp_96_fu_142_p4 & ap_const_lv1_0) & tmp_97_fu_152_p4) & ap_const_lv1_0) & tmp_98_fu_162_p4) & ap_const_lv1_0) & tmp_99_fu_172_p4) & ap_const_lv1_0) & tmp_100_fu_182_p4) & ap_const_lv7_0);
    tmp_109_fu_286_p4 <= ap_phi_mux_prev_phi_fu_124_p4(47 downto 7);
    tmp_110_fu_338_p3 <= ap_phi_mux_prev_phi_fu_124_p4(41 downto 41);
    tmp_111_fu_380_p13 <= (((((((((((tmp_106_fu_242_p4 & ap_const_lv1_0) & tmp_101_fu_192_p4) & ap_const_lv1_0) & tmp_102_fu_202_p4) & ap_const_lv1_0) & tmp_103_fu_212_p4) & ap_const_lv1_0) & tmp_104_fu_222_p4) & ap_const_lv1_0) & tmp_105_fu_232_p4) & ap_const_lv1_0);
    tmp_112_fu_414_p3 <= ap_phi_mux_prev_phi_fu_124_p4(47 downto 47);
    tmp_96_fu_142_p4 <= ap_phi_mux_prev_phi_fu_124_p4(34 downto 29);
    tmp_97_fu_152_p4 <= ap_phi_mux_prev_phi_fu_124_p4(27 downto 22);
    tmp_98_fu_162_p4 <= ap_phi_mux_prev_phi_fu_124_p4(20 downto 15);
    tmp_99_fu_172_p4 <= ap_phi_mux_prev_phi_fu_124_p4(13 downto 8);
    tmp_fu_302_p3 <= ap_phi_mux_prev_phi_fu_124_p4(48 downto 48);
    tmp_s_fu_132_p4 <= ap_phi_mux_prev_phi_fu_124_p4(41 downto 36);
    trunc_ln123_4_fu_432_p1 <= ap_phi_mux_prev_phi_fu_124_p4(6 - 1 downto 0);
    trunc_ln123_fu_320_p1 <= ap_phi_mux_prev_phi_fu_124_p4(41 - 1 downto 0);
end behav;
